# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..types.connect_timeout_header import ConnectTimeoutHeader
from ..types.metrics_v1metric import MetricsV1Metric
from ..types.metrics_v1metric_dimension import MetricsV1MetricDimension
from ..types.metrics_v1metric_filter import MetricsV1MetricFilter
from ..types.metrics_v1metric_granularity import MetricsV1MetricGranularity
from ..types.metrics_v1query_aggregate_response import MetricsV1QueryAggregateResponse
from ..types.metrics_v1query_timeseries_response import MetricsV1QueryTimeseriesResponse
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawMetricsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def query_aggregate(
        self,
        *,
        connect_timeout_ms: typing.Optional[ConnectTimeoutHeader] = None,
        metrics: typing.Optional[typing.Sequence[MetricsV1Metric]] = OMIT,
        since_ms: typing.Optional[str] = OMIT,
        until_ms: typing.Optional[str] = OMIT,
        group_by: typing.Optional[MetricsV1MetricDimension] = OMIT,
        filters: typing.Optional[typing.Sequence[MetricsV1MetricFilter]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[MetricsV1QueryAggregateResponse]:
        """
        Parameters
        ----------
        connect_timeout_ms : typing.Optional[ConnectTimeoutHeader]
            Define the timeout, in ms

        metrics : typing.Optional[typing.Sequence[MetricsV1Metric]]

        since_ms : typing.Optional[str]
            inclusive

        until_ms : typing.Optional[str]
            exclusive; unset = now

        group_by : typing.Optional[MetricsV1MetricDimension]
            UNSPECIFIED = single total row, key ""

        filters : typing.Optional[typing.Sequence[MetricsV1MetricFilter]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[MetricsV1QueryAggregateResponse]
            Success
        """
        _response = self._client_wrapper.httpx_client.request(
            "metrics.v1.MetricsService/QueryAggregate",
            method="POST",
            json={
                "metrics": metrics,
                "sinceMs": since_ms,
                "untilMs": until_ms,
                "groupBy": group_by,
                "filters": convert_and_respect_annotation_metadata(
                    object_=filters, annotation=typing.Sequence[MetricsV1MetricFilter], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
                "Connect-Timeout-Ms": str(connect_timeout_ms) if connect_timeout_ms is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MetricsV1QueryAggregateResponse,
                    parse_obj_as(
                        type_=MetricsV1QueryAggregateResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def query_timeseries(
        self,
        *,
        connect_timeout_ms: typing.Optional[ConnectTimeoutHeader] = None,
        metrics: typing.Optional[typing.Sequence[MetricsV1Metric]] = OMIT,
        since_ms: typing.Optional[str] = OMIT,
        until_ms: typing.Optional[str] = OMIT,
        granularity: typing.Optional[MetricsV1MetricGranularity] = OMIT,
        tz_offset_minutes: typing.Optional[int] = OMIT,
        group_by: typing.Optional[MetricsV1MetricDimension] = OMIT,
        filters: typing.Optional[typing.Sequence[MetricsV1MetricFilter]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[MetricsV1QueryTimeseriesResponse]:
        """
        Parameters
        ----------
        connect_timeout_ms : typing.Optional[ConnectTimeoutHeader]
            Define the timeout, in ms

        metrics : typing.Optional[typing.Sequence[MetricsV1Metric]]
            metrics are computed together per bucket; point values align with this
             order positionally.

        since_ms : typing.Optional[str]
            inclusive

        until_ms : typing.Optional[str]
            exclusive; unset = now

        granularity : typing.Optional[MetricsV1MetricGranularity]

        tz_offset_minutes : typing.Optional[int]
            tz_offset_minutes shifts bucket boundaries east of UTC so DAY buckets
             match the viewer's local calendar day.

        group_by : typing.Optional[MetricsV1MetricDimension]
            UNSPECIFIED = one total series, key ""

        filters : typing.Optional[typing.Sequence[MetricsV1MetricFilter]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[MetricsV1QueryTimeseriesResponse]
            Success
        """
        _response = self._client_wrapper.httpx_client.request(
            "metrics.v1.MetricsService/QueryTimeseries",
            method="POST",
            json={
                "metrics": metrics,
                "sinceMs": since_ms,
                "untilMs": until_ms,
                "granularity": granularity,
                "tzOffsetMinutes": tz_offset_minutes,
                "groupBy": group_by,
                "filters": convert_and_respect_annotation_metadata(
                    object_=filters, annotation=typing.Sequence[MetricsV1MetricFilter], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
                "Connect-Timeout-Ms": str(connect_timeout_ms) if connect_timeout_ms is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MetricsV1QueryTimeseriesResponse,
                    parse_obj_as(
                        type_=MetricsV1QueryTimeseriesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawMetricsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def query_aggregate(
        self,
        *,
        connect_timeout_ms: typing.Optional[ConnectTimeoutHeader] = None,
        metrics: typing.Optional[typing.Sequence[MetricsV1Metric]] = OMIT,
        since_ms: typing.Optional[str] = OMIT,
        until_ms: typing.Optional[str] = OMIT,
        group_by: typing.Optional[MetricsV1MetricDimension] = OMIT,
        filters: typing.Optional[typing.Sequence[MetricsV1MetricFilter]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[MetricsV1QueryAggregateResponse]:
        """
        Parameters
        ----------
        connect_timeout_ms : typing.Optional[ConnectTimeoutHeader]
            Define the timeout, in ms

        metrics : typing.Optional[typing.Sequence[MetricsV1Metric]]

        since_ms : typing.Optional[str]
            inclusive

        until_ms : typing.Optional[str]
            exclusive; unset = now

        group_by : typing.Optional[MetricsV1MetricDimension]
            UNSPECIFIED = single total row, key ""

        filters : typing.Optional[typing.Sequence[MetricsV1MetricFilter]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[MetricsV1QueryAggregateResponse]
            Success
        """
        _response = await self._client_wrapper.httpx_client.request(
            "metrics.v1.MetricsService/QueryAggregate",
            method="POST",
            json={
                "metrics": metrics,
                "sinceMs": since_ms,
                "untilMs": until_ms,
                "groupBy": group_by,
                "filters": convert_and_respect_annotation_metadata(
                    object_=filters, annotation=typing.Sequence[MetricsV1MetricFilter], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
                "Connect-Timeout-Ms": str(connect_timeout_ms) if connect_timeout_ms is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MetricsV1QueryAggregateResponse,
                    parse_obj_as(
                        type_=MetricsV1QueryAggregateResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def query_timeseries(
        self,
        *,
        connect_timeout_ms: typing.Optional[ConnectTimeoutHeader] = None,
        metrics: typing.Optional[typing.Sequence[MetricsV1Metric]] = OMIT,
        since_ms: typing.Optional[str] = OMIT,
        until_ms: typing.Optional[str] = OMIT,
        granularity: typing.Optional[MetricsV1MetricGranularity] = OMIT,
        tz_offset_minutes: typing.Optional[int] = OMIT,
        group_by: typing.Optional[MetricsV1MetricDimension] = OMIT,
        filters: typing.Optional[typing.Sequence[MetricsV1MetricFilter]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[MetricsV1QueryTimeseriesResponse]:
        """
        Parameters
        ----------
        connect_timeout_ms : typing.Optional[ConnectTimeoutHeader]
            Define the timeout, in ms

        metrics : typing.Optional[typing.Sequence[MetricsV1Metric]]
            metrics are computed together per bucket; point values align with this
             order positionally.

        since_ms : typing.Optional[str]
            inclusive

        until_ms : typing.Optional[str]
            exclusive; unset = now

        granularity : typing.Optional[MetricsV1MetricGranularity]

        tz_offset_minutes : typing.Optional[int]
            tz_offset_minutes shifts bucket boundaries east of UTC so DAY buckets
             match the viewer's local calendar day.

        group_by : typing.Optional[MetricsV1MetricDimension]
            UNSPECIFIED = one total series, key ""

        filters : typing.Optional[typing.Sequence[MetricsV1MetricFilter]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[MetricsV1QueryTimeseriesResponse]
            Success
        """
        _response = await self._client_wrapper.httpx_client.request(
            "metrics.v1.MetricsService/QueryTimeseries",
            method="POST",
            json={
                "metrics": metrics,
                "sinceMs": since_ms,
                "untilMs": until_ms,
                "granularity": granularity,
                "tzOffsetMinutes": tz_offset_minutes,
                "groupBy": group_by,
                "filters": convert_and_respect_annotation_metadata(
                    object_=filters, annotation=typing.Sequence[MetricsV1MetricFilter], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
                "Connect-Timeout-Ms": str(connect_timeout_ms) if connect_timeout_ms is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MetricsV1QueryTimeseriesResponse,
                    parse_obj_as(
                        type_=MetricsV1QueryTimeseriesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
