// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: replication_streams.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const bumpReplicationStreamMembershipRevision = `-- name: BumpReplicationStreamMembershipRevision :exec
UPDATE replication_streams
SET membership_revision = membership_revision + 1
WHERE id = ?1
  AND tenant_id = ?2
`

type BumpReplicationStreamMembershipRevisionParams struct {
	ReplicationStreamID string
	TenantID            string
}

func (q *Queries) BumpReplicationStreamMembershipRevision(ctx context.Context, arg BumpReplicationStreamMembershipRevisionParams) error {
	_, err := q.db.ExecContext(ctx, bumpReplicationStreamMembershipRevision, arg.ReplicationStreamID, arg.TenantID)
	return err
}

const createReplicationStream = `-- name: CreateReplicationStream :one
INSERT INTO replication_streams (
  id, tenant_id, pipeline_id, route_key, generation,
  source_connection_id, sink_connection_id,
  consumer_name, consumer_config, continuity_fingerprint,
  status, created_from_pipeline_version_id, created_at, updated_at
) VALUES (
  ?1, ?2, ?3, ?4, ?5,
  ?6, ?7,
  ?8, ?9, ?10,
  0, ?11, ?12, ?13
)
RETURNING id, tenant_id, pipeline_id, route_key, generation, source_connection_id, sink_connection_id, consumer_name, consumer_config, continuity_fingerprint, status, created_from_pipeline_version_id, error, retired_at, created_by_user_id, updated_by_user_id, deleted_by_user_id, created_at, updated_at, membership_revision, current_run_id, desired_state, desired_revision, run_spec, last_epoch
`

type CreateReplicationStreamParams struct {
	ReplicationStreamID          string
	TenantID                     string
	PipelineID                   string
	RouteKey                     string
	Generation                   int64
	SourceConnectionID           string
	SinkConnectionID             string
	ConsumerName                 string
	ConsumerConfig               string
	ContinuityFingerprint        string
	CreatedFromPipelineVersionID string
	CreatedAt                    int64
	UpdatedAt                    int64
}

func (q *Queries) CreateReplicationStream(ctx context.Context, arg CreateReplicationStreamParams) (*ReplicationStream, error) {
	row := q.db.QueryRowContext(ctx, createReplicationStream,
		arg.ReplicationStreamID,
		arg.TenantID,
		arg.PipelineID,
		arg.RouteKey,
		arg.Generation,
		arg.SourceConnectionID,
		arg.SinkConnectionID,
		arg.ConsumerName,
		arg.ConsumerConfig,
		arg.ContinuityFingerprint,
		arg.CreatedFromPipelineVersionID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ReplicationStream
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PipelineID,
		&i.RouteKey,
		&i.Generation,
		&i.SourceConnectionID,
		&i.SinkConnectionID,
		&i.ConsumerName,
		&i.ConsumerConfig,
		&i.ContinuityFingerprint,
		&i.Status,
		&i.CreatedFromPipelineVersionID,
		&i.Error,
		&i.RetiredAt,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.DeletedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MembershipRevision,
		&i.CurrentRunID,
		&i.DesiredState,
		&i.DesiredRevision,
		&i.RunSpec,
		&i.LastEpoch,
	)
	return &i, err
}

const getActiveReplicationStream = `-- name: GetActiveReplicationStream :one
SELECT id, tenant_id, pipeline_id, route_key, generation, source_connection_id, sink_connection_id, consumer_name, consumer_config, continuity_fingerprint, status, created_from_pipeline_version_id, error, retired_at, created_by_user_id, updated_by_user_id, deleted_by_user_id, created_at, updated_at, membership_revision, current_run_id, desired_state, desired_revision, run_spec, last_epoch
FROM replication_streams
WHERE pipeline_id = ?1
  AND route_key = ?2
  AND status = 0
`

type GetActiveReplicationStreamParams struct {
	PipelineID string
	RouteKey   string
}

func (q *Queries) GetActiveReplicationStream(ctx context.Context, arg GetActiveReplicationStreamParams) (*ReplicationStream, error) {
	row := q.db.QueryRowContext(ctx, getActiveReplicationStream, arg.PipelineID, arg.RouteKey)
	var i ReplicationStream
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PipelineID,
		&i.RouteKey,
		&i.Generation,
		&i.SourceConnectionID,
		&i.SinkConnectionID,
		&i.ConsumerName,
		&i.ConsumerConfig,
		&i.ContinuityFingerprint,
		&i.Status,
		&i.CreatedFromPipelineVersionID,
		&i.Error,
		&i.RetiredAt,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.DeletedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MembershipRevision,
		&i.CurrentRunID,
		&i.DesiredState,
		&i.DesiredRevision,
		&i.RunSpec,
		&i.LastEpoch,
	)
	return &i, err
}

const getReplicationStream = `-- name: GetReplicationStream :one
SELECT id, tenant_id, pipeline_id, route_key, generation, source_connection_id, sink_connection_id, consumer_name, consumer_config, continuity_fingerprint, status, created_from_pipeline_version_id, error, retired_at, created_by_user_id, updated_by_user_id, deleted_by_user_id, created_at, updated_at, membership_revision, current_run_id, desired_state, desired_revision, run_spec, last_epoch
FROM replication_streams
WHERE id = ?1
`

func (q *Queries) GetReplicationStream(ctx context.Context, replicationStreamID string) (*ReplicationStream, error) {
	row := q.db.QueryRowContext(ctx, getReplicationStream, replicationStreamID)
	var i ReplicationStream
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PipelineID,
		&i.RouteKey,
		&i.Generation,
		&i.SourceConnectionID,
		&i.SinkConnectionID,
		&i.ConsumerName,
		&i.ConsumerConfig,
		&i.ContinuityFingerprint,
		&i.Status,
		&i.CreatedFromPipelineVersionID,
		&i.Error,
		&i.RetiredAt,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.DeletedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MembershipRevision,
		&i.CurrentRunID,
		&i.DesiredState,
		&i.DesiredRevision,
		&i.RunSpec,
		&i.LastEpoch,
	)
	return &i, err
}

const listReplicationStreamResources = `-- name: ListReplicationStreamResources :many
SELECT id, replication_stream_id, tenant_id, resource_name, status, bootstrap_mode, bootstrap_config, schema_fingerprint, bootstrap_run_id, bootstrap_started_at, activated_at, retired_at, error, created_by_user_id, updated_by_user_id, deleted_by_user_id, created_at, updated_at
FROM replication_stream_resources
WHERE replication_stream_id = ?1
ORDER BY resource_name
`

func (q *Queries) ListReplicationStreamResources(ctx context.Context, replicationStreamID string) ([]*ReplicationStreamResource, error) {
	rows, err := q.db.QueryContext(ctx, listReplicationStreamResources, replicationStreamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ReplicationStreamResource
	for rows.Next() {
		var i ReplicationStreamResource
		if err := rows.Scan(
			&i.ID,
			&i.ReplicationStreamID,
			&i.TenantID,
			&i.ResourceName,
			&i.Status,
			&i.BootstrapMode,
			&i.BootstrapConfig,
			&i.SchemaFingerprint,
			&i.BootstrapRunID,
			&i.BootstrapStartedAt,
			&i.ActivatedAt,
			&i.RetiredAt,
			&i.Error,
			&i.CreatedByUserID,
			&i.UpdatedByUserID,
			&i.DeletedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRetiredReplicationStreamsForRoute = `-- name: ListRetiredReplicationStreamsForRoute :many
SELECT id, tenant_id, pipeline_id, route_key, generation, source_connection_id, sink_connection_id, consumer_name, consumer_config, continuity_fingerprint, status, created_from_pipeline_version_id, error, retired_at, created_by_user_id, updated_by_user_id, deleted_by_user_id, created_at, updated_at, membership_revision, current_run_id, desired_state, desired_revision, run_spec, last_epoch
FROM replication_streams
WHERE pipeline_id = ?1
  AND route_key = ?2
  AND status = 1
  AND coalesce(json_type(consumer_config, '$._filament_cleanup_complete'), '') <> 'true'
ORDER BY generation
`

type ListRetiredReplicationStreamsForRouteParams struct {
	PipelineID string
	RouteKey   string
}

func (q *Queries) ListRetiredReplicationStreamsForRoute(ctx context.Context, arg ListRetiredReplicationStreamsForRouteParams) ([]*ReplicationStream, error) {
	rows, err := q.db.QueryContext(ctx, listRetiredReplicationStreamsForRoute, arg.PipelineID, arg.RouteKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ReplicationStream
	for rows.Next() {
		var i ReplicationStream
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PipelineID,
			&i.RouteKey,
			&i.Generation,
			&i.SourceConnectionID,
			&i.SinkConnectionID,
			&i.ConsumerName,
			&i.ConsumerConfig,
			&i.ContinuityFingerprint,
			&i.Status,
			&i.CreatedFromPipelineVersionID,
			&i.Error,
			&i.RetiredAt,
			&i.CreatedByUserID,
			&i.UpdatedByUserID,
			&i.DeletedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MembershipRevision,
			&i.CurrentRunID,
			&i.DesiredState,
			&i.DesiredRevision,
			&i.RunSpec,
			&i.LastEpoch,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPipelineForReplicationStream = `-- name: LockPipelineForReplicationStream :one

SELECT id
FROM pipelines
WHERE id = ?1
  AND tenant_id = ?2
  AND deleted_at IS NULL
`

type LockPipelineForReplicationStreamParams struct {
	PipelineID string
	TenantID   string
}

// Lock queries must run in the same transaction as their dependent writes.
// SQLite's single-writer connection supplies serialization instead of FOR UPDATE.
// IDs are supplied by Go; lifecycle stamps use unix milliseconds.
func (q *Queries) LockPipelineForReplicationStream(ctx context.Context, arg LockPipelineForReplicationStreamParams) (string, error) {
	row := q.db.QueryRowContext(ctx, lockPipelineForReplicationStream, arg.PipelineID, arg.TenantID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const lockReplicationStream = `-- name: LockReplicationStream :one
SELECT id
FROM replication_streams
WHERE id = ?1
  AND tenant_id = ?2
  AND status = 0
`

type LockReplicationStreamParams struct {
	ReplicationStreamID string
	TenantID            string
}

func (q *Queries) LockReplicationStream(ctx context.Context, arg LockReplicationStreamParams) (string, error) {
	row := q.db.QueryRowContext(ctx, lockReplicationStream, arg.ReplicationStreamID, arg.TenantID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const markReplicationStreamCleaned = `-- name: MarkReplicationStreamCleaned :exec
UPDATE replication_streams
SET consumer_config = json_set(consumer_config, '$._filament_cleanup_complete', json('true')),
    updated_at = ?1
WHERE id = ?2
  AND status = 1
`

type MarkReplicationStreamCleanedParams struct {
	UpdatedAt           int64
	ReplicationStreamID string
}

func (q *Queries) MarkReplicationStreamCleaned(ctx context.Context, arg MarkReplicationStreamCleanedParams) error {
	_, err := q.db.ExecContext(ctx, markReplicationStreamCleaned, arg.UpdatedAt, arg.ReplicationStreamID)
	return err
}

const nextReplicationStreamGeneration = `-- name: NextReplicationStreamGeneration :one
SELECT CAST(COALESCE(MAX(generation), 0) + 1 AS INTEGER)
FROM replication_streams
WHERE pipeline_id = ?1
  AND route_key = ?2
`

type NextReplicationStreamGenerationParams struct {
	PipelineID string
	RouteKey   string
}

func (q *Queries) NextReplicationStreamGeneration(ctx context.Context, arg NextReplicationStreamGenerationParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextReplicationStreamGeneration, arg.PipelineID, arg.RouteKey)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const retireReplicationStream = `-- name: RetireReplicationStream :exec
UPDATE replication_streams
SET status = 1, retired_at = ?1, error = NULL, updated_at = ?2
WHERE id = ?3
  AND status = 0
`

type RetireReplicationStreamParams struct {
	RetiredAt           sql.NullInt64
	UpdatedAt           int64
	ReplicationStreamID string
}

func (q *Queries) RetireReplicationStream(ctx context.Context, arg RetireReplicationStreamParams) error {
	_, err := q.db.ExecContext(ctx, retireReplicationStream, arg.RetiredAt, arg.UpdatedAt, arg.ReplicationStreamID)
	return err
}

const retireReplicationStreamResources = `-- name: RetireReplicationStreamResources :exec
UPDATE replication_stream_resources
SET status = 3, retired_at = ?1, updated_at = ?2
WHERE replication_stream_id = ?3
  AND status <> 3
  AND resource_name NOT IN (SELECT CAST(value AS TEXT) FROM json_each(CAST(?4 AS TEXT)))
`

type RetireReplicationStreamResourcesParams struct {
	RetiredAt           sql.NullInt64
	UpdatedAt           int64
	ReplicationStreamID string
	ResourceNames       string
}

// resource_names is a JSON array of names to retain; [] retires every resource.
func (q *Queries) RetireReplicationStreamResources(ctx context.Context, arg RetireReplicationStreamResourcesParams) error {
	_, err := q.db.ExecContext(ctx, retireReplicationStreamResources,
		arg.RetiredAt,
		arg.UpdatedAt,
		arg.ReplicationStreamID,
		arg.ResourceNames,
	)
	return err
}

const upsertReplicationStreamResource = `-- name: UpsertReplicationStreamResource :exec
INSERT INTO replication_stream_resources (
  id, replication_stream_id, tenant_id, resource_name, status,
  bootstrap_mode, bootstrap_config, created_at, updated_at
) VALUES (
  ?1, ?2, ?3, ?4, 0,
  ?5, ?6, ?7, ?8
)
ON CONFLICT (replication_stream_id, resource_name) DO UPDATE
SET status = CASE
      WHEN replication_stream_resources.status = 3 THEN 0
      ELSE replication_stream_resources.status
    END,
    bootstrap_mode = EXCLUDED.bootstrap_mode,
    bootstrap_config = EXCLUDED.bootstrap_config,
    bootstrap_run_id = CASE
      WHEN replication_stream_resources.status = 3 THEN NULL
      ELSE replication_stream_resources.bootstrap_run_id
    END,
    bootstrap_started_at = CASE
      WHEN replication_stream_resources.status = 3 THEN NULL
      ELSE replication_stream_resources.bootstrap_started_at
    END,
    retired_at = CASE
      WHEN replication_stream_resources.status = 3 THEN NULL
      ELSE replication_stream_resources.retired_at
    END,
    activated_at = CASE
      WHEN replication_stream_resources.status = 3 THEN NULL
      ELSE replication_stream_resources.activated_at
    END,
    error = CASE
      WHEN replication_stream_resources.status = 3 THEN NULL
      ELSE replication_stream_resources.error
    END,
    updated_at = excluded.updated_at
`

type UpsertReplicationStreamResourceParams struct {
	ResourceID          string
	ReplicationStreamID string
	TenantID            string
	ResourceName        string
	BootstrapMode       string
	BootstrapConfig     string
	CreatedAt           int64
	UpdatedAt           int64
}

func (q *Queries) UpsertReplicationStreamResource(ctx context.Context, arg UpsertReplicationStreamResourceParams) error {
	_, err := q.db.ExecContext(ctx, upsertReplicationStreamResource,
		arg.ResourceID,
		arg.ReplicationStreamID,
		arg.TenantID,
		arg.ResourceName,
		arg.BootstrapMode,
		arg.BootstrapConfig,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
