// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stream_epochs.sql

package sqlcgen

import (
	"context"
)

const advanceStreamEpoch = `-- name: AdvanceStreamEpoch :execrows
UPDATE replication_streams SET last_epoch = ?1 WHERE id = ?2 AND tenant_id = ?3 AND last_epoch = ?4
`

type AdvanceStreamEpochParams struct {
	Epoch         int64
	StreamID      string
	TenantID      string
	PreviousEpoch int64
}

func (q *Queries) AdvanceStreamEpoch(ctx context.Context, arg AdvanceStreamEpochParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, advanceStreamEpoch,
		arg.Epoch,
		arg.StreamID,
		arg.TenantID,
		arg.PreviousEpoch,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createStreamEpoch = `-- name: CreateStreamEpoch :one
INSERT INTO stream_epochs(stream_id,tenant_id,epoch,attempt_token,certificate,positions)
VALUES(?1,?2,?3,?4,?5,?6) RETURNING stream_id, tenant_id, epoch, attempt_token, certificate, positions, committed_at
`

type CreateStreamEpochParams struct {
	StreamID     string
	TenantID     string
	Epoch        int64
	AttemptToken int64
	Certificate  []byte
	Positions    string
}

func (q *Queries) CreateStreamEpoch(ctx context.Context, arg CreateStreamEpochParams) (*StreamEpoch, error) {
	row := q.db.QueryRowContext(ctx, createStreamEpoch,
		arg.StreamID,
		arg.TenantID,
		arg.Epoch,
		arg.AttemptToken,
		arg.Certificate,
		arg.Positions,
	)
	var i StreamEpoch
	err := row.Scan(
		&i.StreamID,
		&i.TenantID,
		&i.Epoch,
		&i.AttemptToken,
		&i.Certificate,
		&i.Positions,
		&i.CommittedAt,
	)
	return &i, err
}

const getStreamEpoch = `-- name: GetStreamEpoch :one
SELECT stream_id, tenant_id, epoch, attempt_token, certificate, positions, committed_at FROM stream_epochs WHERE stream_id = ?1 AND tenant_id = ?2 AND epoch = ?3
`

type GetStreamEpochParams struct {
	StreamID string
	TenantID string
	Epoch    int64
}

func (q *Queries) GetStreamEpoch(ctx context.Context, arg GetStreamEpochParams) (*StreamEpoch, error) {
	row := q.db.QueryRowContext(ctx, getStreamEpoch, arg.StreamID, arg.TenantID, arg.Epoch)
	var i StreamEpoch
	err := row.Scan(
		&i.StreamID,
		&i.TenantID,
		&i.Epoch,
		&i.AttemptToken,
		&i.Certificate,
		&i.Positions,
		&i.CommittedAt,
	)
	return &i, err
}
