# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.connect_timeout_header import ConnectTimeoutHeader
from ..types.google_protobuf_struct import GoogleProtobufStruct
from ..types.ingestion_v1connector_kind import IngestionV1ConnectorKind
from ..types.ingestion_v1discover_resources_response import IngestionV1DiscoverResourcesResponse
from ..types.ingestion_v1get_connector_response import IngestionV1GetConnectorResponse
from ..types.ingestion_v1get_resource_columns_response import IngestionV1GetResourceColumnsResponse
from ..types.ingestion_v1list_connectors_response import IngestionV1ListConnectorsResponse
from ..types.ingestion_v1pagination_request import IngestionV1PaginationRequest
from ..types.ingestion_v1sorting_request import IngestionV1SortingRequest
from ..types.ingestion_v1validate_config_response import IngestionV1ValidateConfigResponse
from .raw_client import AsyncRawConnectorClient, RawConnectorClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ConnectorClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawConnectorClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawConnectorClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawConnectorClient
        """
        return self._raw_client

    def discover_resources(
        self,
        *,
        connect_timeout_ms: typing.Optional[ConnectTimeoutHeader] = None,
        connector: typing.Optional[str] = OMIT,
        config: typing.Optional[GoogleProtobufStruct] = OMIT,
        refresh: typing.Optional[bool] = OMIT,
        connection_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> IngestionV1DiscoverResourcesResponse:
        """
        Parameters
        ----------
        connect_timeout_ms : typing.Optional[ConnectTimeoutHeader]
            Define the timeout, in ms

        connector : typing.Optional[str]

        config : typing.Optional[GoogleProtobufStruct]

        refresh : typing.Optional[bool]

        connection_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IngestionV1DiscoverResourcesResponse
            Success

        Examples
        --------
        from filament import Filament

        client = Filament(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.connector.discover_resources(
            connect_timeout_ms=1000.0,
        )
        """
        _response = self._raw_client.discover_resources(
            connect_timeout_ms=connect_timeout_ms,
            connector=connector,
            config=config,
            refresh=refresh,
            connection_id=connection_id,
            request_options=request_options,
        )
        return _response.data

    def get(
        self,
        *,
        connect_timeout_ms: typing.Optional[ConnectTimeoutHeader] = None,
        connector: typing.Optional[str] = OMIT,
        kind: typing.Optional[IngestionV1ConnectorKind] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> IngestionV1GetConnectorResponse:
        """
        Parameters
        ----------
        connect_timeout_ms : typing.Optional[ConnectTimeoutHeader]
            Define the timeout, in ms

        connector : typing.Optional[str]

        kind : typing.Optional[IngestionV1ConnectorKind]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IngestionV1GetConnectorResponse
            Success

        Examples
        --------
        from filament import Filament

        client = Filament(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.connector.get(
            connect_timeout_ms=1000.0,
        )
        """
        _response = self._raw_client.get(
            connect_timeout_ms=connect_timeout_ms, connector=connector, kind=kind, request_options=request_options
        )
        return _response.data

    def get_resource_columns(
        self,
        *,
        connect_timeout_ms: typing.Optional[ConnectTimeoutHeader] = None,
        connector: typing.Optional[str] = OMIT,
        config: typing.Optional[GoogleProtobufStruct] = OMIT,
        connection_id: typing.Optional[str] = OMIT,
        resources: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> IngestionV1GetResourceColumnsResponse:
        """
        Parameters
        ----------
        connect_timeout_ms : typing.Optional[ConnectTimeoutHeader]
            Define the timeout, in ms

        connector : typing.Optional[str]

        config : typing.Optional[GoogleProtobufStruct]

        connection_id : typing.Optional[str]

        resources : typing.Optional[typing.Sequence[str]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IngestionV1GetResourceColumnsResponse
            Success

        Examples
        --------
        from filament import Filament

        client = Filament(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.connector.get_resource_columns(
            connect_timeout_ms=1000.0,
        )
        """
        _response = self._raw_client.get_resource_columns(
            connect_timeout_ms=connect_timeout_ms,
            connector=connector,
            config=config,
            connection_id=connection_id,
            resources=resources,
            request_options=request_options,
        )
        return _response.data

    def list(
        self,
        *,
        connect_timeout_ms: typing.Optional[ConnectTimeoutHeader] = None,
        kind: typing.Optional[IngestionV1ConnectorKind] = OMIT,
        pagination: typing.Optional[IngestionV1PaginationRequest] = OMIT,
        search: typing.Optional[str] = OMIT,
        sorting: typing.Optional[IngestionV1SortingRequest] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> IngestionV1ListConnectorsResponse:
        """
        Catalog of registered source/sink connectors and their config schemas.

        Parameters
        ----------
        connect_timeout_ms : typing.Optional[ConnectTimeoutHeader]
            Define the timeout, in ms

        kind : typing.Optional[IngestionV1ConnectorKind]

        pagination : typing.Optional[IngestionV1PaginationRequest]

        search : typing.Optional[str]

        sorting : typing.Optional[IngestionV1SortingRequest]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IngestionV1ListConnectorsResponse
            Success

        Examples
        --------
        from filament import Filament

        client = Filament(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.connector.list(
            connect_timeout_ms=1000.0,
        )
        """
        _response = self._raw_client.list(
            connect_timeout_ms=connect_timeout_ms,
            kind=kind,
            pagination=pagination,
            search=search,
            sorting=sorting,
            request_options=request_options,
        )
        return _response.data

    def validate_config(
        self,
        *,
        connect_timeout_ms: typing.Optional[ConnectTimeoutHeader] = None,
        kind: typing.Optional[IngestionV1ConnectorKind] = OMIT,
        connector: typing.Optional[str] = OMIT,
        config: typing.Optional[GoogleProtobufStruct] = OMIT,
        connection_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> IngestionV1ValidateConfigResponse:
        """
        Ephemeral source/sink operations; no persisted state.

        Parameters
        ----------
        connect_timeout_ms : typing.Optional[ConnectTimeoutHeader]
            Define the timeout, in ms

        kind : typing.Optional[IngestionV1ConnectorKind]

        connector : typing.Optional[str]

        config : typing.Optional[GoogleProtobufStruct]

        connection_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IngestionV1ValidateConfigResponse
            Success

        Examples
        --------
        from filament import Filament

        client = Filament(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.connector.validate_config(
            connect_timeout_ms=1000.0,
        )
        """
        _response = self._raw_client.validate_config(
            connect_timeout_ms=connect_timeout_ms,
            kind=kind,
            connector=connector,
            config=config,
            connection_id=connection_id,
            request_options=request_options,
        )
        return _response.data


class AsyncConnectorClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawConnectorClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawConnectorClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawConnectorClient
        """
        return self._raw_client

    async def discover_resources(
        self,
        *,
        connect_timeout_ms: typing.Optional[ConnectTimeoutHeader] = None,
        connector: typing.Optional[str] = OMIT,
        config: typing.Optional[GoogleProtobufStruct] = OMIT,
        refresh: typing.Optional[bool] = OMIT,
        connection_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> IngestionV1DiscoverResourcesResponse:
        """
        Parameters
        ----------
        connect_timeout_ms : typing.Optional[ConnectTimeoutHeader]
            Define the timeout, in ms

        connector : typing.Optional[str]

        config : typing.Optional[GoogleProtobufStruct]

        refresh : typing.Optional[bool]

        connection_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IngestionV1DiscoverResourcesResponse
            Success

        Examples
        --------
        import asyncio

        from filament import AsyncFilament

        client = AsyncFilament(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.connector.discover_resources(
                connect_timeout_ms=1000.0,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.discover_resources(
            connect_timeout_ms=connect_timeout_ms,
            connector=connector,
            config=config,
            refresh=refresh,
            connection_id=connection_id,
            request_options=request_options,
        )
        return _response.data

    async def get(
        self,
        *,
        connect_timeout_ms: typing.Optional[ConnectTimeoutHeader] = None,
        connector: typing.Optional[str] = OMIT,
        kind: typing.Optional[IngestionV1ConnectorKind] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> IngestionV1GetConnectorResponse:
        """
        Parameters
        ----------
        connect_timeout_ms : typing.Optional[ConnectTimeoutHeader]
            Define the timeout, in ms

        connector : typing.Optional[str]

        kind : typing.Optional[IngestionV1ConnectorKind]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IngestionV1GetConnectorResponse
            Success

        Examples
        --------
        import asyncio

        from filament import AsyncFilament

        client = AsyncFilament(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.connector.get(
                connect_timeout_ms=1000.0,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(
            connect_timeout_ms=connect_timeout_ms, connector=connector, kind=kind, request_options=request_options
        )
        return _response.data

    async def get_resource_columns(
        self,
        *,
        connect_timeout_ms: typing.Optional[ConnectTimeoutHeader] = None,
        connector: typing.Optional[str] = OMIT,
        config: typing.Optional[GoogleProtobufStruct] = OMIT,
        connection_id: typing.Optional[str] = OMIT,
        resources: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> IngestionV1GetResourceColumnsResponse:
        """
        Parameters
        ----------
        connect_timeout_ms : typing.Optional[ConnectTimeoutHeader]
            Define the timeout, in ms

        connector : typing.Optional[str]

        config : typing.Optional[GoogleProtobufStruct]

        connection_id : typing.Optional[str]

        resources : typing.Optional[typing.Sequence[str]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IngestionV1GetResourceColumnsResponse
            Success

        Examples
        --------
        import asyncio

        from filament import AsyncFilament

        client = AsyncFilament(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.connector.get_resource_columns(
                connect_timeout_ms=1000.0,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_resource_columns(
            connect_timeout_ms=connect_timeout_ms,
            connector=connector,
            config=config,
            connection_id=connection_id,
            resources=resources,
            request_options=request_options,
        )
        return _response.data

    async def list(
        self,
        *,
        connect_timeout_ms: typing.Optional[ConnectTimeoutHeader] = None,
        kind: typing.Optional[IngestionV1ConnectorKind] = OMIT,
        pagination: typing.Optional[IngestionV1PaginationRequest] = OMIT,
        search: typing.Optional[str] = OMIT,
        sorting: typing.Optional[IngestionV1SortingRequest] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> IngestionV1ListConnectorsResponse:
        """
        Catalog of registered source/sink connectors and their config schemas.

        Parameters
        ----------
        connect_timeout_ms : typing.Optional[ConnectTimeoutHeader]
            Define the timeout, in ms

        kind : typing.Optional[IngestionV1ConnectorKind]

        pagination : typing.Optional[IngestionV1PaginationRequest]

        search : typing.Optional[str]

        sorting : typing.Optional[IngestionV1SortingRequest]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IngestionV1ListConnectorsResponse
            Success

        Examples
        --------
        import asyncio

        from filament import AsyncFilament

        client = AsyncFilament(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.connector.list(
                connect_timeout_ms=1000.0,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            connect_timeout_ms=connect_timeout_ms,
            kind=kind,
            pagination=pagination,
            search=search,
            sorting=sorting,
            request_options=request_options,
        )
        return _response.data

    async def validate_config(
        self,
        *,
        connect_timeout_ms: typing.Optional[ConnectTimeoutHeader] = None,
        kind: typing.Optional[IngestionV1ConnectorKind] = OMIT,
        connector: typing.Optional[str] = OMIT,
        config: typing.Optional[GoogleProtobufStruct] = OMIT,
        connection_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> IngestionV1ValidateConfigResponse:
        """
        Ephemeral source/sink operations; no persisted state.

        Parameters
        ----------
        connect_timeout_ms : typing.Optional[ConnectTimeoutHeader]
            Define the timeout, in ms

        kind : typing.Optional[IngestionV1ConnectorKind]

        connector : typing.Optional[str]

        config : typing.Optional[GoogleProtobufStruct]

        connection_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IngestionV1ValidateConfigResponse
            Success

        Examples
        --------
        import asyncio

        from filament import AsyncFilament

        client = AsyncFilament(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.connector.validate_config(
                connect_timeout_ms=1000.0,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.validate_config(
            connect_timeout_ms=connect_timeout_ms,
            kind=kind,
            connector=connector,
            config=config,
            connection_id=connection_id,
            request_options=request_options,
        )
        return _response.data
