export const PIPELINES_TABLE_COLUMN_MIN_WIDTH_PIPELINE = 192;
export const PIPELINES_TABLE_COLUMN_WIDTH_FLOW = 192;
export const PIPELINES_TABLE_COLUMN_WIDTH_STATUS = 150;
export const PIPELINES_TABLE_COLUMN_WIDTH_LAST_RUN = 110;
export const PIPELINES_TABLE_COLUMN_WIDTH_LAST_DURATION = 100;
export const PIPELINES_TABLE_COLUMN_WIDTH_LAST_VOLUME = 100;
