export const PIPELINES_TABLE_COLUMN_WIDTH_CONNECTORS = 220;
export const PIPELINES_TABLE_COLUMN_WIDTH_LAST_RUN = 120;
export const PIPELINES_TABLE_COLUMN_WIDTH_LAST_VOLUME = 140;
export const PIPELINES_TABLE_COLUMN_WIDTH_VERSION = 60;
