export const PIPELINES_TABLE_COLUMN_WIDTH_CONNECTORS = 160;
export const PIPELINES_TABLE_COLUMN_WIDTH_STATUS = 130;
export const PIPELINES_TABLE_COLUMN_WIDTH_LAST_RUN = 110;
export const PIPELINES_TABLE_COLUMN_WIDTH_LAST_DURATION = 100;
export const PIPELINES_TABLE_COLUMN_WIDTH_LAST_VOLUME = 100;
