export const PIPELINE_NODE_WIDTH = 360;
export const PIPELINE_NODE_PADDING = 8;
export const PIPELINE_NODE_BORDER_RADIUS = 6;
export const PIPELINE_NODE_GAP = 8;

export const PIPELINE_NODE_PLACEHOLDER_SELECTOR_HEIGHT = 300;

export const PIPELINE_NODE_HANDLE_SLOT_SIZE = 24;
export const PIPELINE_NODE_TABLE_LIST_MAX_HEIGHT = 300;
