# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .auth_v1service_account import AuthV1ServiceAccount


class AuthV1ListServiceAccountsResponse(UniversalBaseModel):
    service_accounts: typing_extensions.Annotated[
        typing.Optional[typing.List[AuthV1ServiceAccount]],
        FieldMetadata(alias="serviceAccounts"),
        pydantic.Field(alias="serviceAccounts"),
    ] = None
    can_manage: typing_extensions.Annotated[
        typing.Optional[bool], FieldMetadata(alias="canManage"), pydantic.Field(alias="canManage")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
