# This file was auto-generated by Fern from our API Definition.

import typing

AuthV1GetSessionRequest = typing.Dict[str, typing.Any]
"""
GetSessionRequest resolves the caller behind the session cookie. It is the
 UI's sign-in check: unauthenticated means show the login page.
"""
