# This file was auto-generated by Fern from our API Definition.

import typing

from .google_protobuf_value import GoogleProtobufValue

GoogleProtobufListValue = typing.List[typing.Optional[GoogleProtobufValue]]
"""
A JSON array whose elements may be any JSON value.
"""
