# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .ingestion_v1pipeline_edge import IngestionV1PipelineEdge
from .ingestion_v1pipeline_node import IngestionV1PipelineNode


class IngestionV1PipelineGraph(UniversalBaseModel):
    nodes: typing.Optional[typing.List[IngestionV1PipelineNode]] = None
    edges: typing.Optional[typing.List[IngestionV1PipelineEdge]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
