# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .google_protobuf_struct import GoogleProtobufStruct


class IngestionV1RunEventFields(UniversalBaseModel):
    """
    RunEventFields contains the optional measurements carried by a run event.
    """

    records: typing.Optional[str] = None
    bytes: typing.Optional[str] = None
    uri: typing.Optional[str] = None
    crc: typing.Optional[int] = None
    error: typing.Optional[str] = None
    retry_after_ms: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="retryAfterMs"), pydantic.Field(alias="retryAfterMs")
    ] = None
    parents_total: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="parentsTotal"), pydantic.Field(alias="parentsTotal")
    ] = None
    checkpoint: typing.Optional[GoogleProtobufStruct] = pydantic.Field(default=None)
    """
    Legacy bounded cursor payload. Continuous progress is read through GetRun;
     continuous events do not carry raw customer cursors.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
