# This file was auto-generated by Fern from our API Definition.

import typing

IngestionV1ExecutionObservedState = typing.Union[
    typing.Literal[
        "EXECUTION_OBSERVED_STATE_UNSPECIFIED",
        "EXECUTION_OBSERVED_STATE_STARTING",
        "EXECUTION_OBSERVED_STATE_RUNNING",
        "EXECUTION_OBSERVED_STATE_DRAINING",
        "EXECUTION_OBSERVED_STATE_PAUSED",
        "EXECUTION_OBSERVED_STATE_STOPPED",
        "EXECUTION_OBSERVED_STATE_RETRYING",
        "EXECUTION_OBSERVED_STATE_BLOCKED",
        "EXECUTION_OBSERVED_STATE_FAILED",
    ],
    typing.Any,
]
