# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs
from ..core.serialization import FieldMetadata
from .ingestion_v1config_schema import IngestionV1ConfigSchema
from .ingestion_v1connector_kind import IngestionV1ConnectorKind
from .ingestion_v1connector_maturity import IngestionV1ConnectorMaturity
from .ingestion_v1replication_mode import IngestionV1ReplicationMode


class IngestionV1ConnectorSpec(UniversalBaseModel):
    """
    ConnectorSpec describes one registered source or sink connector.
    """

    name: typing.Optional[str] = None
    display_name: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="displayName"), pydantic.Field(alias="displayName")
    ] = None
    kind: typing.Optional[IngestionV1ConnectorKind] = None
    version: typing.Optional[str] = None
    modes: typing.Optional[typing.List[IngestionV1ReplicationMode]] = None
    config_schema: typing_extensions.Annotated[
        typing.Optional[IngestionV1ConfigSchema],
        FieldMetadata(alias="configSchema"),
        pydantic.Field(alias="configSchema"),
    ] = None
    description: typing.Optional[str] = None
    dark_logo_url: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="darkLogoUrl"), pydantic.Field(alias="darkLogoUrl")
    ] = None
    light_logo_url: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="lightLogoUrl"), pydantic.Field(alias="lightLogoUrl")
    ] = None
    schema_field: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="schemaField"), pydantic.Field(alias="schemaField")
    ] = None
    maturity: typing.Optional[IngestionV1ConnectorMaturity] = None
    api_version: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="apiVersion"), pydantic.Field(alias="apiVersion")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


update_forward_refs(IngestionV1ConnectorSpec)
