# This file was auto-generated by Fern from our API Definition.

import typing

IngestionV1ReplicationMode = typing.Union[
    typing.Literal["REPLICATION_MODE_UNSPECIFIED", "REPLICATION_MODE_STANDARD", "REPLICATION_MODE_CDC"], typing.Any
]
