# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .ingestion_v1pipeline_edge_run import IngestionV1PipelineEdgeRun


class IngestionV1RunPipelineResponse(UniversalBaseModel):
    edge_runs: typing_extensions.Annotated[
        typing.Optional[typing.List[IngestionV1PipelineEdgeRun]],
        FieldMetadata(alias="edgeRuns"),
        pydantic.Field(alias="edgeRuns"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
