# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class IngestionV1ResourceCursorConfig(UniversalBaseModel):
    resource: typing.Optional[str] = None
    field: typing.Optional[str] = None
    lookback_seconds: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="lookbackSeconds"), pydantic.Field(alias="lookbackSeconds")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
