# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .google_protobuf_struct import GoogleProtobufStruct
from .ingestion_v1notification_type import IngestionV1NotificationType
from .ingestion_v1notifier_event import IngestionV1NotifierEvent


class IngestionV1Notifier(UniversalBaseModel):
    """
    Notifier holds settings, plain config, and secret references, never secret
     values. Webhook config carries url; secret_refs carries headers. Slack
     config is empty; secret_refs carries url.
    """

    id: typing.Optional[str] = None
    tenant_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="tenantId"), pydantic.Field(alias="tenantId")
    ] = None
    pipeline_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="pipelineId"), pydantic.Field(alias="pipelineId")
    ] = None
    name: typing.Optional[str] = None
    notification_type: typing_extensions.Annotated[
        typing.Optional[IngestionV1NotificationType],
        FieldMetadata(alias="notificationType"),
        pydantic.Field(alias="notificationType"),
    ] = None
    is_enabled: typing_extensions.Annotated[
        typing.Optional[bool], FieldMetadata(alias="isEnabled"), pydantic.Field(alias="isEnabled")
    ] = None
    events: typing.Optional[typing.List[IngestionV1NotifierEvent]] = None
    resources: typing.Optional[typing.List[str]] = None
    config: typing.Optional[GoogleProtobufStruct] = None
    secret_refs: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, str]], FieldMetadata(alias="secretRefs"), pydantic.Field(alias="secretRefs")
    ] = None
    created_at: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")
    ] = None
    updated_at: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="updatedAt"), pydantic.Field(alias="updatedAt")
    ] = None
    deleted_at: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="deletedAt"), pydantic.Field(alias="deletedAt")
    ] = None
    created_by_user_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="createdByUserId"), pydantic.Field(alias="createdByUserId")
    ] = None
    updated_by_user_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="updatedByUserId"), pydantic.Field(alias="updatedByUserId")
    ] = None
    deleted_by_user_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="deletedByUserId"), pydantic.Field(alias="deletedByUserId")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
