# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .ingestion_v1rate_policy import IngestionV1RatePolicy


class IngestionV1RunOptions(UniversalBaseModel):
    """
    RunOptions overrides the engine's throughput defaults for a run. Every field
     is optional: a zero value defers to the engine default downstream.
    """

    fetch_size: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="fetchSize"), pydantic.Field(alias="fetchSize")
    ] = None
    batch_max_rows: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="batchMaxRows"), pydantic.Field(alias="batchMaxRows")
    ] = None
    batch_max_bytes: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="batchMaxBytes"), pydantic.Field(alias="batchMaxBytes")
    ] = None
    rate_limit: typing_extensions.Annotated[
        typing.Optional[IngestionV1RatePolicy], FieldMetadata(alias="rateLimit"), pydantic.Field(alias="rateLimit")
    ] = None
    snapshot_parallelism: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="snapshotParallelism"), pydantic.Field(alias="snapshotParallelism")
    ] = None
    checkpoint_every: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="checkpointEvery"), pydantic.Field(alias="checkpointEvery")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
