# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .ingestion_v1pagination_response import IngestionV1PaginationResponse
from .ingestion_v1run_info import IngestionV1RunInfo


class IngestionV1ListRunsResponse(UniversalBaseModel):
    runs: typing.Optional[typing.List[IngestionV1RunInfo]] = None
    pagination: typing.Optional[IngestionV1PaginationResponse] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
