# This file was auto-generated by Fern from our API Definition.

import typing

IngestionV1NotificationType = typing.Union[
    typing.Literal["NOTIFICATION_TYPE_UNSPECIFIED", "NOTIFICATION_TYPE_WEBHOOK", "NOTIFICATION_TYPE_SLACK"], typing.Any
]
