# This file was auto-generated by Fern from our API Definition.

import typing

IngestionV1RunStatus = typing.Union[
    typing.Literal[
        "RUN_STATUS_UNSPECIFIED",
        "RUN_STATUS_REQUESTED",
        "RUN_STATUS_RUNNING",
        "RUN_STATUS_COMPLETED",
        "RUN_STATUS_FAILED",
        "RUN_STATUS_CANCELED",
        "RUN_STATUS_PAUSED",
        "RUN_STATUS_PARTIAL",
        "RUN_STATUS_SCHEDULED",
    ],
    typing.Any,
]
