# This file was auto-generated by Fern from our API Definition.

import typing

IngestionV1RunSignal = typing.Union[
    typing.Literal["RUN_SIGNAL_UNSPECIFIED", "RUN_SIGNAL_PAUSE", "RUN_SIGNAL_RESUME", "RUN_SIGNAL_CANCEL"], typing.Any
]
