# This file was auto-generated by Fern from our API Definition.

import typing

MetricsV1Metric = typing.Union[
    typing.Literal[
        "METRIC_UNSPECIFIED",
        "METRIC_RUN_COUNT",
        "METRIC_RUN_RECORDS",
        "METRIC_RUN_BYTES",
        "METRIC_RUN_DURATION",
        "METRIC_RUN_MEMORY_USAGE",
        "METRIC_RUN_CPU_USAGE",
    ],
    typing.Any,
]
