// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: catalog/v1/catalog.proto

package catalogv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/galaxy-io/filament/api/catalog/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// CatalogServiceName is the fully-qualified name of the CatalogService service.
	CatalogServiceName = "catalog.v1.CatalogService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CatalogServiceDescribeProcedure is the fully-qualified name of the CatalogService's Describe RPC.
	CatalogServiceDescribeProcedure = "/catalog.v1.CatalogService/Describe"
	// CatalogServicePlanReplicationStreamProcedure is the fully-qualified name of the CatalogService's
	// PlanReplicationStream RPC.
	CatalogServicePlanReplicationStreamProcedure = "/catalog.v1.CatalogService/PlanReplicationStream"
	// CatalogServiceValidateProcedure is the fully-qualified name of the CatalogService's Validate RPC.
	CatalogServiceValidateProcedure = "/catalog.v1.CatalogService/Validate"
	// CatalogServiceTestConnectionProcedure is the fully-qualified name of the CatalogService's
	// TestConnection RPC.
	CatalogServiceTestConnectionProcedure = "/catalog.v1.CatalogService/TestConnection"
	// CatalogServiceDiscoverProcedure is the fully-qualified name of the CatalogService's Discover RPC.
	CatalogServiceDiscoverProcedure = "/catalog.v1.CatalogService/Discover"
	// CatalogServiceInspectProcedure is the fully-qualified name of the CatalogService's Inspect RPC.
	CatalogServiceInspectProcedure = "/catalog.v1.CatalogService/Inspect"
)

// CatalogServiceClient is a client for the catalog.v1.CatalogService service.
type CatalogServiceClient interface {
	// Describe returns connector specs and driver contracts. They are fixed for
	// the life of the host process.
	Describe(context.Context, *connect.Request[v1.DescribeRequest]) (*connect.Response[v1.DescribeResponse], error)
	// PlanReplicationStream asks a streaming source to plan its consumer.
	PlanReplicationStream(context.Context, *connect.Request[v1.PlanReplicationStreamRequest]) (*connect.Response[v1.PlanReplicationStreamResponse], error)
	// Validate runs the connector's pure config validation.
	Validate(context.Context, *connect.Request[v1.ValidateRequest]) (*connect.Response[v1.ValidateResponse], error)
	// TestConnection runs the connector's live probe.
	TestConnection(context.Context, *connect.Request[v1.TestConnectionRequest]) (*connect.Response[v1.TestConnectionResponse], error)
	// Discover configures the source and lists its resources.
	Discover(context.Context, *connect.Request[v1.DiscoverRequest]) (*connect.Response[v1.DiscoverResponse], error)
	// Inspect configures the source once and reports each resource's primary
	// key and columns.
	Inspect(context.Context, *connect.Request[v1.InspectRequest]) (*connect.Response[v1.InspectResponse], error)
}

// NewCatalogServiceClient constructs a client for the catalog.v1.CatalogService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCatalogServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CatalogServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	catalogServiceMethods := v1.File_catalog_v1_catalog_proto.Services().ByName("CatalogService").Methods()
	return &catalogServiceClient{
		describe: connect.NewClient[v1.DescribeRequest, v1.DescribeResponse](
			httpClient,
			baseURL+CatalogServiceDescribeProcedure,
			connect.WithSchema(catalogServiceMethods.ByName("Describe")),
			connect.WithClientOptions(opts...),
		),
		planReplicationStream: connect.NewClient[v1.PlanReplicationStreamRequest, v1.PlanReplicationStreamResponse](
			httpClient,
			baseURL+CatalogServicePlanReplicationStreamProcedure,
			connect.WithSchema(catalogServiceMethods.ByName("PlanReplicationStream")),
			connect.WithClientOptions(opts...),
		),
		validate: connect.NewClient[v1.ValidateRequest, v1.ValidateResponse](
			httpClient,
			baseURL+CatalogServiceValidateProcedure,
			connect.WithSchema(catalogServiceMethods.ByName("Validate")),
			connect.WithClientOptions(opts...),
		),
		testConnection: connect.NewClient[v1.TestConnectionRequest, v1.TestConnectionResponse](
			httpClient,
			baseURL+CatalogServiceTestConnectionProcedure,
			connect.WithSchema(catalogServiceMethods.ByName("TestConnection")),
			connect.WithClientOptions(opts...),
		),
		discover: connect.NewClient[v1.DiscoverRequest, v1.DiscoverResponse](
			httpClient,
			baseURL+CatalogServiceDiscoverProcedure,
			connect.WithSchema(catalogServiceMethods.ByName("Discover")),
			connect.WithClientOptions(opts...),
		),
		inspect: connect.NewClient[v1.InspectRequest, v1.InspectResponse](
			httpClient,
			baseURL+CatalogServiceInspectProcedure,
			connect.WithSchema(catalogServiceMethods.ByName("Inspect")),
			connect.WithClientOptions(opts...),
		),
	}
}

// catalogServiceClient implements CatalogServiceClient.
type catalogServiceClient struct {
	describe              *connect.Client[v1.DescribeRequest, v1.DescribeResponse]
	planReplicationStream *connect.Client[v1.PlanReplicationStreamRequest, v1.PlanReplicationStreamResponse]
	validate              *connect.Client[v1.ValidateRequest, v1.ValidateResponse]
	testConnection        *connect.Client[v1.TestConnectionRequest, v1.TestConnectionResponse]
	discover              *connect.Client[v1.DiscoverRequest, v1.DiscoverResponse]
	inspect               *connect.Client[v1.InspectRequest, v1.InspectResponse]
}

// Describe calls catalog.v1.CatalogService.Describe.
func (c *catalogServiceClient) Describe(ctx context.Context, req *connect.Request[v1.DescribeRequest]) (*connect.Response[v1.DescribeResponse], error) {
	return c.describe.CallUnary(ctx, req)
}

// PlanReplicationStream calls catalog.v1.CatalogService.PlanReplicationStream.
func (c *catalogServiceClient) PlanReplicationStream(ctx context.Context, req *connect.Request[v1.PlanReplicationStreamRequest]) (*connect.Response[v1.PlanReplicationStreamResponse], error) {
	return c.planReplicationStream.CallUnary(ctx, req)
}

// Validate calls catalog.v1.CatalogService.Validate.
func (c *catalogServiceClient) Validate(ctx context.Context, req *connect.Request[v1.ValidateRequest]) (*connect.Response[v1.ValidateResponse], error) {
	return c.validate.CallUnary(ctx, req)
}

// TestConnection calls catalog.v1.CatalogService.TestConnection.
func (c *catalogServiceClient) TestConnection(ctx context.Context, req *connect.Request[v1.TestConnectionRequest]) (*connect.Response[v1.TestConnectionResponse], error) {
	return c.testConnection.CallUnary(ctx, req)
}

// Discover calls catalog.v1.CatalogService.Discover.
func (c *catalogServiceClient) Discover(ctx context.Context, req *connect.Request[v1.DiscoverRequest]) (*connect.Response[v1.DiscoverResponse], error) {
	return c.discover.CallUnary(ctx, req)
}

// Inspect calls catalog.v1.CatalogService.Inspect.
func (c *catalogServiceClient) Inspect(ctx context.Context, req *connect.Request[v1.InspectRequest]) (*connect.Response[v1.InspectResponse], error) {
	return c.inspect.CallUnary(ctx, req)
}

// CatalogServiceHandler is an implementation of the catalog.v1.CatalogService service.
type CatalogServiceHandler interface {
	// Describe returns connector specs and driver contracts. They are fixed for
	// the life of the host process.
	Describe(context.Context, *connect.Request[v1.DescribeRequest]) (*connect.Response[v1.DescribeResponse], error)
	// PlanReplicationStream asks a streaming source to plan its consumer.
	PlanReplicationStream(context.Context, *connect.Request[v1.PlanReplicationStreamRequest]) (*connect.Response[v1.PlanReplicationStreamResponse], error)
	// Validate runs the connector's pure config validation.
	Validate(context.Context, *connect.Request[v1.ValidateRequest]) (*connect.Response[v1.ValidateResponse], error)
	// TestConnection runs the connector's live probe.
	TestConnection(context.Context, *connect.Request[v1.TestConnectionRequest]) (*connect.Response[v1.TestConnectionResponse], error)
	// Discover configures the source and lists its resources.
	Discover(context.Context, *connect.Request[v1.DiscoverRequest]) (*connect.Response[v1.DiscoverResponse], error)
	// Inspect configures the source once and reports each resource's primary
	// key and columns.
	Inspect(context.Context, *connect.Request[v1.InspectRequest]) (*connect.Response[v1.InspectResponse], error)
}

// NewCatalogServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCatalogServiceHandler(svc CatalogServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	catalogServiceMethods := v1.File_catalog_v1_catalog_proto.Services().ByName("CatalogService").Methods()
	catalogServiceDescribeHandler := connect.NewUnaryHandler(
		CatalogServiceDescribeProcedure,
		svc.Describe,
		connect.WithSchema(catalogServiceMethods.ByName("Describe")),
		connect.WithHandlerOptions(opts...),
	)
	catalogServicePlanReplicationStreamHandler := connect.NewUnaryHandler(
		CatalogServicePlanReplicationStreamProcedure,
		svc.PlanReplicationStream,
		connect.WithSchema(catalogServiceMethods.ByName("PlanReplicationStream")),
		connect.WithHandlerOptions(opts...),
	)
	catalogServiceValidateHandler := connect.NewUnaryHandler(
		CatalogServiceValidateProcedure,
		svc.Validate,
		connect.WithSchema(catalogServiceMethods.ByName("Validate")),
		connect.WithHandlerOptions(opts...),
	)
	catalogServiceTestConnectionHandler := connect.NewUnaryHandler(
		CatalogServiceTestConnectionProcedure,
		svc.TestConnection,
		connect.WithSchema(catalogServiceMethods.ByName("TestConnection")),
		connect.WithHandlerOptions(opts...),
	)
	catalogServiceDiscoverHandler := connect.NewUnaryHandler(
		CatalogServiceDiscoverProcedure,
		svc.Discover,
		connect.WithSchema(catalogServiceMethods.ByName("Discover")),
		connect.WithHandlerOptions(opts...),
	)
	catalogServiceInspectHandler := connect.NewUnaryHandler(
		CatalogServiceInspectProcedure,
		svc.Inspect,
		connect.WithSchema(catalogServiceMethods.ByName("Inspect")),
		connect.WithHandlerOptions(opts...),
	)
	return "/catalog.v1.CatalogService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CatalogServiceDescribeProcedure:
			catalogServiceDescribeHandler.ServeHTTP(w, r)
		case CatalogServicePlanReplicationStreamProcedure:
			catalogServicePlanReplicationStreamHandler.ServeHTTP(w, r)
		case CatalogServiceValidateProcedure:
			catalogServiceValidateHandler.ServeHTTP(w, r)
		case CatalogServiceTestConnectionProcedure:
			catalogServiceTestConnectionHandler.ServeHTTP(w, r)
		case CatalogServiceDiscoverProcedure:
			catalogServiceDiscoverHandler.ServeHTTP(w, r)
		case CatalogServiceInspectProcedure:
			catalogServiceInspectHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCatalogServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCatalogServiceHandler struct{}

func (UnimplementedCatalogServiceHandler) Describe(context.Context, *connect.Request[v1.DescribeRequest]) (*connect.Response[v1.DescribeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("catalog.v1.CatalogService.Describe is not implemented"))
}

func (UnimplementedCatalogServiceHandler) PlanReplicationStream(context.Context, *connect.Request[v1.PlanReplicationStreamRequest]) (*connect.Response[v1.PlanReplicationStreamResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("catalog.v1.CatalogService.PlanReplicationStream is not implemented"))
}

func (UnimplementedCatalogServiceHandler) Validate(context.Context, *connect.Request[v1.ValidateRequest]) (*connect.Response[v1.ValidateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("catalog.v1.CatalogService.Validate is not implemented"))
}

func (UnimplementedCatalogServiceHandler) TestConnection(context.Context, *connect.Request[v1.TestConnectionRequest]) (*connect.Response[v1.TestConnectionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("catalog.v1.CatalogService.TestConnection is not implemented"))
}

func (UnimplementedCatalogServiceHandler) Discover(context.Context, *connect.Request[v1.DiscoverRequest]) (*connect.Response[v1.DiscoverResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("catalog.v1.CatalogService.Discover is not implemented"))
}

func (UnimplementedCatalogServiceHandler) Inspect(context.Context, *connect.Request[v1.InspectRequest]) (*connect.Response[v1.InspectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("catalog.v1.CatalogService.Inspect is not implemented"))
}
