export const PIPELINE_CANVAS_TERMINAL_WIDTH = 640;
export const PIPELINE_CANVAS_TERMINAL_HEIGHT = 640;
export const PIPELINE_CANVAS_TERMINAL_RIGHT_OFFSET = 24;
export const PIPELINE_CANVAS_TERMINAL_NOTCH_WIDTH = 360;
