// This file was auto-generated by Fern from our API Definition.

/**
 * InviteMemberResponse carries the invitation an admin shares out of band.
 *  Nothing is emailed.
 */
export interface AuthV1InviteMemberResponse {
    userId?: string | undefined;
    code?: string | undefined;
}
