// This file was auto-generated by Fern from our API Definition.

import type * as Filament from "../index.js";

/**
 * A JSON array whose elements may be any JSON value.
 */
export type GoogleProtobufListValue = (Filament.GoogleProtobufValue | null)[];
