// This file was auto-generated by Fern from our API Definition.

import type * as Filament from "../index.js";

/**
 * NotifierInput replaces the rule's settings. Secret fields in config are
 *  extracted and stored as secrets; on update, an omitted secret field keeps
 *  the reference echoed in secret_refs.
 */
export interface IngestionV1NotifierInput {
    name?: string | undefined;
    notificationType?: Filament.IngestionV1NotificationType | undefined;
    isEnabled?: boolean | undefined;
    events?: Filament.IngestionV1NotifierEvent[] | undefined;
    /** Empty matches any resource. */
    resources?: string[] | undefined;
    config?: Filament.GoogleProtobufStruct | undefined;
    secretRefs?: Record<string, string> | undefined;
}
