// This file was auto-generated by Fern from our API Definition.

export interface IngestionV1TailRunRequest {
    runId?: string | undefined;
    /**
     * replay first emits events synthesized from the current snapshot (each marked
     *  replay=true) so progress is correct on reconnect, before live facts stream.
     */
    shouldReplay?: boolean | undefined;
}
