// This file was auto-generated by Fern from our API Definition.

/** RunStatus is the persisted lifecycle state of a run. */
export const IngestionV1RunStatus = {
    RunStatusUnspecified: "RUN_STATUS_UNSPECIFIED",
    RunStatusRequested: "RUN_STATUS_REQUESTED",
    RunStatusRunning: "RUN_STATUS_RUNNING",
    RunStatusCompleted: "RUN_STATUS_COMPLETED",
    RunStatusFailed: "RUN_STATUS_FAILED",
    RunStatusCanceled: "RUN_STATUS_CANCELED",
    RunStatusPaused: "RUN_STATUS_PAUSED",
    RunStatusPartial: "RUN_STATUS_PARTIAL",
    RunStatusScheduled: "RUN_STATUS_SCHEDULED",
} as const;
export type IngestionV1RunStatus = (typeof IngestionV1RunStatus)[keyof typeof IngestionV1RunStatus];
