// This file was auto-generated by Fern from our API Definition.

/**
 * ReplicationMode is how a connection replicates, decided at source creation:
 *  query-based reads (standard) or the change stream (CDC). Databases choose;
 *  APIs are implicitly standard.
 */
export const IngestionV1ReplicationMode = {
    ReplicationModeUnspecified: "REPLICATION_MODE_UNSPECIFIED",
    ReplicationModeStandard: "REPLICATION_MODE_STANDARD",
    ReplicationModeCdc: "REPLICATION_MODE_CDC",
} as const;
export type IngestionV1ReplicationMode = (typeof IngestionV1ReplicationMode)[keyof typeof IngestionV1ReplicationMode];
