// This file was auto-generated by Fern from our API Definition.

import type * as Filament from "../index.js";

/**
 * ConnectorSpec describes one registered source or sink connector.
 */
export interface IngestionV1ConnectorSpec {
    name?: string | undefined;
    displayName?: string | undefined;
    kind?: Filament.IngestionV1ConnectorKind | undefined;
    version?: string | undefined;
    modes?: Filament.IngestionV1ReplicationMode[] | undefined;
    configSchema?: Filament.IngestionV1ConfigSchema | undefined;
    description?: string | undefined;
    darkLogoUrl?: string | undefined;
    lightLogoUrl?: string | undefined;
    schemaField?: string | undefined;
    maturity?: Filament.IngestionV1ConnectorMaturity | undefined;
    apiVersion?: string | undefined;
    /** Concrete registration selected by a source catalog alias; empty otherwise. */
    aliasTarget?: string | undefined;
}
