// This file was auto-generated by Fern from our API Definition.

import type * as Filament from "../index.js";

/**
 * Continuous success confirms persisted intent, not completed worker drainage.
 *  Bounded responses leave execution_status absent.
 */
export interface IngestionV1SignalRunResponse {
    executionStatus?: Filament.IngestionV1ExecutionStatus | undefined;
}
