// This file was auto-generated by Fern from our API Definition.

/**
 * WorkerToleration mirrors a Kubernetes toleration. Fields are the Kubernetes
 *  strings verbatim: operator "Equal" (default) or "Exists"; effect
 *  "NoSchedule", "PreferNoSchedule", "NoExecute", or empty to match all.
 */
export interface IngestionV1WorkerToleration {
    key?: string | undefined;
    operator?: string | undefined;
    value?: string | undefined;
    effect?: string | undefined;
}
