// This file was auto-generated by Fern from our API Definition.

import type * as Filament from "../index.js";

export interface IngestionV1ResourceColumns {
    resource?: string | undefined;
    columns?: Filament.IngestionV1ResourceColumn[] | undefined;
}
