// This file was auto-generated by Fern from our API Definition.

import type * as Filament from "../index.js";

/**
 * ExecutionStatus is the user-facing state of continuous execution, loaded from
 *  durable state. GetRun/ListRuns remain authoritative after missed live events.
 *  Pause/resume and worker restarts retain the run ID; starting again after stop
 *  creates a new run. Desired and observed states can differ while draining.
 */
export interface IngestionV1ExecutionStatus {
    desiredState?: Filament.IngestionV1ExecutionDesiredState | undefined;
    observedState?: Filament.IngestionV1ExecutionObservedState | undefined;
    /** Opaque revision for SignalRunRequest.expected_revision; clients echo it. */
    revision?: string | undefined;
    /** User-facing explanation, including actionable blocked/failed conditions. */
    reason?: string | undefined;
    /** Epoch milliseconds of the most recent durable commit; zero means none yet. */
    lastCommittedAt?: string | undefined;
}
