// This file was auto-generated by Fern from our API Definition.

/** RunSignal is a lifecycle command sent to a run. */
export const IngestionV1RunSignal = {
    RunSignalUnspecified: "RUN_SIGNAL_UNSPECIFIED",
    RunSignalPause: "RUN_SIGNAL_PAUSE",
    RunSignalResume: "RUN_SIGNAL_RESUME",
    RunSignalCancel: "RUN_SIGNAL_CANCEL",
    RunSignalStop: "RUN_SIGNAL_STOP",
} as const;
export type IngestionV1RunSignal = (typeof IngestionV1RunSignal)[keyof typeof IngestionV1RunSignal];
