// This file was auto-generated by Fern from our API Definition.

import type * as Filament from "../index.js";

export interface IngestionV1ListConnectionsResponse {
    connections?: Filament.IngestionV1Connection[] | undefined;
    pagination?: Filament.IngestionV1PaginationResponse | undefined;
}
