// This file was auto-generated by Fern from our API Definition.

/**
 * EnumOption is one ordered choice for an enum or list config field.
 */
export interface IngestionV1EnumOption {
    value?: string | undefined;
    label?: string | undefined;
}
