// This file was auto-generated by Fern from our API Definition.

import type * as Filament from "../index.js";

export interface IngestionV1ValidatePipelineResponse {
    valid?: boolean | undefined;
    edges?: Filament.IngestionV1EdgeValidation[] | undefined;
    /** Graph-level failures: dangling node refs, unknown connections. */
    errors?: Filament.IngestionV1ValidationError[] | undefined;
}
