// This file was auto-generated by Fern from our API Definition.

/** MetricsGranularity is the bucket width for timeseries queries. */
export const MetricsV1MetricGranularity = {
    MetricGranularityUnspecified: "METRIC_GRANULARITY_UNSPECIFIED",
    MetricGranularityHour: "METRIC_GRANULARITY_HOUR",
    MetricGranularityDay: "METRIC_GRANULARITY_DAY",
} as const;
export type MetricsV1MetricGranularity = (typeof MetricsV1MetricGranularity)[keyof typeof MetricsV1MetricGranularity];
