// This file was auto-generated by Fern from our API Definition.

/**
 * Metric is an aggregatable measure over runs. RUN_COUNT/RUN_RECORDS/RUN_BYTES
 *  are sums; RUN_DURATION is the mean duration in milliseconds over terminal
 *  runs (percentile variants can be added as new values later).
 *  RUN_MEMORY_USAGE is the mean peak working set in bytes and RUN_CPU_USAGE the
 *  mean CPU seconds, both over runs that reported usage (a zero column means
 *  "no usage reported", e.g. runs outside a cgroup, and is excluded).
 */
export const MetricsV1Metric = {
    MetricUnspecified: "METRIC_UNSPECIFIED",
    MetricRunCount: "METRIC_RUN_COUNT",
    MetricRunRecords: "METRIC_RUN_RECORDS",
    MetricRunBytes: "METRIC_RUN_BYTES",
    MetricRunDuration: "METRIC_RUN_DURATION",
    MetricRunMemoryUsage: "METRIC_RUN_MEMORY_USAGE",
    MetricRunCpuUsage: "METRIC_RUN_CPU_USAGE",
} as const;
export type MetricsV1Metric = (typeof MetricsV1Metric)[keyof typeof MetricsV1Metric];
