// This file was auto-generated by Fern from our API Definition.

/** MetricDimension names a runs column usable for grouping and filtering. */
export const MetricsV1MetricDimension = {
    MetricDimensionUnspecified: "METRIC_DIMENSION_UNSPECIFIED",
    MetricDimensionTenantId: "METRIC_DIMENSION_TENANT_ID",
    MetricDimensionPipelineId: "METRIC_DIMENSION_PIPELINE_ID",
    MetricDimensionStatus: "METRIC_DIMENSION_STATUS",
} as const;
export type MetricsV1MetricDimension = (typeof MetricsV1MetricDimension)[keyof typeof MetricsV1MetricDimension];
