// This file was auto-generated by Fern from our API Definition.

import type * as Filament from "../../../../index.js";

/**
 * @example
 *     {
 *         "Connect-Timeout-Ms": 1000
 *     }
 */
export interface IngestionV1ValidatePipelineRequest {
    /** Define the timeout, in ms */
    "Connect-Timeout-Ms"?: Filament.ConnectTimeoutHeader;
    graph?: Filament.IngestionV1PipelineGraph;
    /** Unspecified means bounded. Validation and submission must use the same mode. */
    executionMode?: Filament.IngestionV1ExecutionMode;
}
