// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ConnectionKind string

const (
	ConnectionKindSource ConnectionKind = "source"
	ConnectionKindSink   ConnectionKind = "sink"
)

func (e *ConnectionKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConnectionKind(s)
	case string:
		*e = ConnectionKind(s)
	default:
		return fmt.Errorf("unsupported scan type for ConnectionKind: %T", src)
	}
	return nil
}

type NullConnectionKind struct {
	ConnectionKind ConnectionKind
	Valid          bool // Valid is true if ConnectionKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConnectionKind) Scan(value interface{}) error {
	if value == nil {
		ns.ConnectionKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConnectionKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConnectionKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConnectionKind), nil
}

type Connection struct {
	ID              string
	TenantID        string
	Kind            ConnectionKind
	Name            string
	Provider        string
	Config          []byte
	SecretRefs      []byte
	Version         int64
	IsDeleted       bool
	DeletedAt       pgtype.Timestamptz
	CreatedByUserID pgtype.Text
	UpdatedByUserID pgtype.Text
	DeletedByUserID pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type Pipeline struct {
	ID                  string
	TenantID            string
	Name                string
	Description         string
	CurrentVersionID    pgtype.Text
	WorkerConfiguration []byte
	IsDeleted           bool
	DeletedAt           pgtype.Timestamptz
	CreatedByUserID     pgtype.Text
	UpdatedByUserID     pgtype.Text
	DeletedByUserID     pgtype.Text
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type PipelineResourceCheckpoint struct {
	ID                string
	PipelineID        string
	PipelineVersionID string
	RouteKey          string
	ResourceName      string
	Cursor            []byte
	LastRunID         string
	CreatedByUserID   pgtype.Text
	UpdatedByUserID   pgtype.Text
	DeletedByUserID   pgtype.Text
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type PipelineVersion struct {
	ID              string
	PipelineID      string
	Version         int64
	Graph           []byte
	CreatedByUserID pgtype.Text
	UpdatedByUserID pgtype.Text
	DeletedByUserID pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type Run struct {
	ID                string
	TenantID          string
	PipelineID        pgtype.Text
	PipelineVersionID pgtype.Text
	ScheduleID        pgtype.Text
	Status            int16
	Request           []byte
	Records           int64
	Bytes             int64
	CpuSeconds        float64
	MemoryPeakBytes   int64
	ScheduledAt       pgtype.Timestamptz
	RequestedAt       pgtype.Timestamptz
	StartedAt         pgtype.Timestamptz
	EndedAt           pgtype.Timestamptz
	Error             pgtype.Text
	CreatedByUserID   pgtype.Text
	UpdatedByUserID   pgtype.Text
	DeletedByUserID   pgtype.Text
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type RunDedupSeen struct {
	ID              string
	TenantID        string
	RunID           string
	LastSeq         int64
	CreatedByUserID pgtype.Text
	UpdatedByUserID pgtype.Text
	DeletedByUserID pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type RunResourceCheckpoint struct {
	ID              string
	RunID           string
	ResourceName    string
	Cursor          []byte
	CreatedByUserID pgtype.Text
	UpdatedByUserID pgtype.Text
	DeletedByUserID pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type RunResourceState struct {
	ID              string
	RunID           string
	ResourceName    string
	TenantID        string
	Status          int16
	Records         int64
	Bytes           int64
	Error           pgtype.Text
	CreatedByUserID pgtype.Text
	UpdatedByUserID pgtype.Text
	DeletedByUserID pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type Schedule struct {
	ID              string
	TenantID        string
	PipelineID      string
	Name            pgtype.Text
	CronExpr        string
	Timezone        string
	OverlapPolicy   int16
	Enabled         bool
	LastFiredAt     pgtype.Timestamptz
	NextFireAt      pgtype.Timestamptz
	ClaimedAt       pgtype.Timestamptz
	CreatedByUserID pgtype.Text
	UpdatedByUserID pgtype.Text
	DeletedByUserID pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type Secret struct {
	ID              string
	TenantID        string
	Ref             string
	Ciphertext      []byte
	Nonce           []byte
	KeyID           string
	Metadata        []byte
	CreatedByUserID pgtype.Text
	UpdatedByUserID pgtype.Text
	DeletedByUserID pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type Tenant struct {
	ID              string
	Name            pgtype.Text
	CreatedByUserID pgtype.Text
	UpdatedByUserID pgtype.Text
	DeletedByUserID pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type User struct {
	ID              string
	TenantID        string
	ExternalID      string
	CreatedByUserID pgtype.Text
	UpdatedByUserID pgtype.Text
	DeletedByUserID pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}
