// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pipeline_resource_checkpoints.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteResourceCheckpoint = `-- name: DeleteResourceCheckpoint :exec
DELETE FROM pipeline_resource_checkpoints
WHERE pipeline_id = $1
  AND pipeline_version_id = $2
  AND route_key = $3
  AND resource_name = $4
`

type DeleteResourceCheckpointParams struct {
	PipelineID        string
	PipelineVersionID string
	RouteKey          string
	ResourceName      string
}

func (q *Queries) DeleteResourceCheckpoint(ctx context.Context, arg DeleteResourceCheckpointParams) error {
	_, err := q.db.Exec(ctx, deleteResourceCheckpoint,
		arg.PipelineID,
		arg.PipelineVersionID,
		arg.RouteKey,
		arg.ResourceName,
	)
	return err
}

const loadResourceCheckpoint = `-- name: LoadResourceCheckpoint :one
SELECT cursor, last_run_id, updated_at
FROM pipeline_resource_checkpoints
WHERE pipeline_id = $1
  AND pipeline_version_id = $2
  AND route_key = $3
  AND resource_name = $4
`

type LoadResourceCheckpointParams struct {
	PipelineID        string
	PipelineVersionID string
	RouteKey          string
	ResourceName      string
}

type LoadResourceCheckpointRow struct {
	Cursor    []byte
	LastRunID string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) LoadResourceCheckpoint(ctx context.Context, arg LoadResourceCheckpointParams) (*LoadResourceCheckpointRow, error) {
	row := q.db.QueryRow(ctx, loadResourceCheckpoint,
		arg.PipelineID,
		arg.PipelineVersionID,
		arg.RouteKey,
		arg.ResourceName,
	)
	var i LoadResourceCheckpointRow
	err := row.Scan(&i.Cursor, &i.LastRunID, &i.UpdatedAt)
	return &i, err
}

const saveResourceCheckpoint = `-- name: SaveResourceCheckpoint :exec
INSERT INTO pipeline_resource_checkpoints (
  tenant_id, pipeline_id, pipeline_version_id, route_key, resource_name, cursor, last_run_id, updated_at
)
SELECT tenant_id, $1, $2, $3, $4, $5, $6, now()
FROM pipelines
WHERE id = $1
ON CONFLICT (pipeline_id, pipeline_version_id, route_key, resource_name) DO UPDATE
SET cursor = EXCLUDED.cursor, last_run_id = EXCLUDED.last_run_id, updated_at = now()
`

type SaveResourceCheckpointParams struct {
	PipelineID        string
	PipelineVersionID string
	RouteKey          string
	ResourceName      string
	Cursor            []byte
	LastRunID         string
}

func (q *Queries) SaveResourceCheckpoint(ctx context.Context, arg SaveResourceCheckpointParams) error {
	_, err := q.db.Exec(ctx, saveResourceCheckpoint,
		arg.PipelineID,
		arg.PipelineVersionID,
		arg.RouteKey,
		arg.ResourceName,
		arg.Cursor,
		arg.LastRunID,
	)
	return err
}
