// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pipelines.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPipelineVersions = `-- name: CountPipelineVersions :one
SELECT count(*) FROM pipeline_versions
WHERE pipeline_id = $1
`

func (q *Queries) CountPipelineVersions(ctx context.Context, pipelineID string) (int64, error) {
	row := q.db.QueryRow(ctx, countPipelineVersions, pipelineID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPipelines = `-- name: CountPipelines :one
SELECT count(*) FROM pipelines
WHERE (nullif($1::text, '') IS NULL OR tenant_id = $1::uuid)
  AND ($2::boolean OR NOT is_deleted)
  AND (nullif($3::text, '') IS NULL
       OR name ILIKE '%' || $3 || '%' ESCAPE '\'
       OR description ILIKE '%' || $3 || '%' ESCAPE '\')
`

type CountPipelinesParams struct {
	TenantID       string
	IncludeDeleted bool
	Search         string
}

func (q *Queries) CountPipelines(ctx context.Context, arg CountPipelinesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPipelines, arg.TenantID, arg.IncludeDeleted, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPipeline = `-- name: CreatePipeline :one
INSERT INTO pipelines (id, tenant_id, name, description, worker_configuration, updated_at)
VALUES ($1, $2, $3, $4, COALESCE($5::jsonb, '{}'::jsonb), now())
RETURNING created_at
`

type CreatePipelineParams struct {
	PipelineID          string
	TenantID            string
	Name                string
	Description         string
	WorkerConfiguration []byte
}

func (q *Queries) CreatePipeline(ctx context.Context, arg CreatePipelineParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, createPipeline,
		arg.PipelineID,
		arg.TenantID,
		arg.Name,
		arg.Description,
		arg.WorkerConfiguration,
	)
	var created_at pgtype.Timestamptz
	err := row.Scan(&created_at)
	return created_at, err
}

const createPipelineVersion = `-- name: CreatePipelineVersion :one
WITH locked AS MATERIALIZED (
  SELECT id FROM pipelines WHERE id = $1 AND NOT is_deleted FOR UPDATE
), next AS (
  SELECT coalesce(max(v.version), 0) + 1 AS version
  FROM locked LEFT JOIN pipeline_versions v ON v.pipeline_id = locked.id
), inserted AS (
  INSERT INTO pipeline_versions (id, tenant_id, pipeline_id, version, graph)
  SELECT $2, p.tenant_id, $1, next.version, $3
  FROM next
  JOIN pipelines p ON p.id = $1
  RETURNING id, version, created_at
)
UPDATE pipelines p SET current_version_id = inserted.id, updated_at = now()
FROM inserted WHERE p.id = $1
RETURNING inserted.id, inserted.version, inserted.created_at
`

type CreatePipelineVersionParams struct {
	PipelineID string
	ID         string
	Graph      []byte
}

type CreatePipelineVersionRow struct {
	ID        string
	Version   int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreatePipelineVersion(ctx context.Context, arg CreatePipelineVersionParams) (*CreatePipelineVersionRow, error) {
	row := q.db.QueryRow(ctx, createPipelineVersion, arg.PipelineID, arg.ID, arg.Graph)
	var i CreatePipelineVersionRow
	err := row.Scan(&i.ID, &i.Version, &i.CreatedAt)
	return &i, err
}

const deletePipeline = `-- name: DeletePipeline :exec
UPDATE pipelines SET
  is_deleted = true,
  deleted_at = now(),
  name = name || '__deleted__' || to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
  updated_at = now()
WHERE id = $1 AND NOT is_deleted
`

func (q *Queries) DeletePipeline(ctx context.Context, pipelineID string) error {
	_, err := q.db.Exec(ctx, deletePipeline, pipelineID)
	return err
}

const getPipeline = `-- name: GetPipeline :one
SELECT id, tenant_id, name, description, current_version_id, worker_configuration,
       created_at, updated_at, deleted_at,
       created_by_user_id, updated_by_user_id, deleted_by_user_id
FROM pipelines WHERE id = $1
`

type GetPipelineRow struct {
	ID                  string
	TenantID            string
	Name                string
	Description         string
	CurrentVersionID    pgtype.Text
	WorkerConfiguration []byte
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	DeletedAt           pgtype.Timestamptz
	CreatedByUserID     pgtype.Text
	UpdatedByUserID     pgtype.Text
	DeletedByUserID     pgtype.Text
}

func (q *Queries) GetPipeline(ctx context.Context, pipelineID string) (*GetPipelineRow, error) {
	row := q.db.QueryRow(ctx, getPipeline, pipelineID)
	var i GetPipelineRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.CurrentVersionID,
		&i.WorkerConfiguration,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.DeletedByUserID,
	)
	return &i, err
}

const getPipelineVersion = `-- name: GetPipelineVersion :one
SELECT id, pipeline_id, version, graph, created_at, updated_at,
       created_by_user_id, updated_by_user_id, deleted_by_user_id FROM pipeline_versions
WHERE pipeline_id = $1
  AND (($2::bigint = 0 AND id = (SELECT current_version_id FROM pipelines WHERE pipelines.id = $1))
    OR version = $2)
`

type GetPipelineVersionParams struct {
	PipelineID string
	Version    int64
}

type GetPipelineVersionRow struct {
	ID              string
	PipelineID      string
	Version         int64
	Graph           []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	CreatedByUserID pgtype.Text
	UpdatedByUserID pgtype.Text
	DeletedByUserID pgtype.Text
}

func (q *Queries) GetPipelineVersion(ctx context.Context, arg GetPipelineVersionParams) (*GetPipelineVersionRow, error) {
	row := q.db.QueryRow(ctx, getPipelineVersion, arg.PipelineID, arg.Version)
	var i GetPipelineVersionRow
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.Version,
		&i.Graph,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.DeletedByUserID,
	)
	return &i, err
}

const listPipelineVersions = `-- name: ListPipelineVersions :many
SELECT id, pipeline_id, version, graph, created_at, updated_at,
       created_by_user_id, updated_by_user_id, deleted_by_user_id FROM pipeline_versions
WHERE pipeline_id = $1
ORDER BY
  CASE WHEN $2::text IN ('', 'version') AND NOT $3::boolean THEN version END ASC,
  CASE WHEN $2::text IN ('', 'version') AND $3::boolean THEN version END DESC,
  CASE WHEN $2::text = 'created_at' AND NOT $3::boolean THEN created_at END ASC,
  CASE WHEN $2::text = 'created_at' AND $3::boolean THEN created_at END DESC,
  CASE WHEN $2::text = 'updated_at' AND NOT $3::boolean THEN updated_at END ASC,
  CASE WHEN $2::text = 'updated_at' AND $3::boolean THEN updated_at END DESC,
  CASE WHEN NOT $3::boolean THEN id END ASC,
  CASE WHEN $3::boolean THEN id END DESC
LIMIT NULLIF($5::int, 0)
OFFSET $4::int
`

type ListPipelineVersionsParams struct {
	PipelineID string
	SortBy     string
	SortDesc   bool
	OffsetRows int32
	Lim        int32
}

type ListPipelineVersionsRow struct {
	ID              string
	PipelineID      string
	Version         int64
	Graph           []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	CreatedByUserID pgtype.Text
	UpdatedByUserID pgtype.Text
	DeletedByUserID pgtype.Text
}

func (q *Queries) ListPipelineVersions(ctx context.Context, arg ListPipelineVersionsParams) ([]*ListPipelineVersionsRow, error) {
	rows, err := q.db.Query(ctx, listPipelineVersions,
		arg.PipelineID,
		arg.SortBy,
		arg.SortDesc,
		arg.OffsetRows,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListPipelineVersionsRow
	for rows.Next() {
		var i ListPipelineVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.PipelineID,
			&i.Version,
			&i.Graph,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedByUserID,
			&i.UpdatedByUserID,
			&i.DeletedByUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPipelines = `-- name: ListPipelines :many
SELECT id, tenant_id, name, description, current_version_id, worker_configuration,
       created_at, updated_at, deleted_at,
       created_by_user_id, updated_by_user_id, deleted_by_user_id
FROM pipelines
WHERE (nullif($1::text, '') IS NULL OR tenant_id = $1::uuid)
  AND ($2::boolean OR NOT is_deleted)
  AND (nullif($3::text, '') IS NULL
       OR name ILIKE '%' || $3 || '%' ESCAPE '\'
       OR description ILIKE '%' || $3 || '%' ESCAPE '\')
ORDER BY
  CASE WHEN $4::text IN ('', 'id') AND NOT $5::boolean THEN id END ASC,
  CASE WHEN $4::text IN ('', 'id') AND $5::boolean THEN id END DESC,
  CASE WHEN $4::text = 'name' AND NOT $5::boolean THEN lower(name) END ASC,
  CASE WHEN $4::text = 'name' AND $5::boolean THEN lower(name) END DESC,
  CASE WHEN $4::text = 'created_at' AND NOT $5::boolean THEN created_at END ASC,
  CASE WHEN $4::text = 'created_at' AND $5::boolean THEN created_at END DESC,
  CASE WHEN $4::text = 'updated_at' AND NOT $5::boolean THEN updated_at END ASC,
  CASE WHEN $4::text = 'updated_at' AND $5::boolean THEN updated_at END DESC,
  CASE WHEN NOT $5::boolean THEN id END ASC,
  CASE WHEN $5::boolean THEN id END DESC
LIMIT NULLIF($7::int, 0)
OFFSET $6::int
`

type ListPipelinesParams struct {
	TenantID       string
	IncludeDeleted bool
	Search         string
	SortBy         string
	SortDesc       bool
	OffsetRows     int32
	Lim            int32
}

type ListPipelinesRow struct {
	ID                  string
	TenantID            string
	Name                string
	Description         string
	CurrentVersionID    pgtype.Text
	WorkerConfiguration []byte
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	DeletedAt           pgtype.Timestamptz
	CreatedByUserID     pgtype.Text
	UpdatedByUserID     pgtype.Text
	DeletedByUserID     pgtype.Text
}

func (q *Queries) ListPipelines(ctx context.Context, arg ListPipelinesParams) ([]*ListPipelinesRow, error) {
	rows, err := q.db.Query(ctx, listPipelines,
		arg.TenantID,
		arg.IncludeDeleted,
		arg.Search,
		arg.SortBy,
		arg.SortDesc,
		arg.OffsetRows,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListPipelinesRow
	for rows.Next() {
		var i ListPipelinesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.CurrentVersionID,
			&i.WorkerConfiguration,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedByUserID,
			&i.UpdatedByUserID,
			&i.DeletedByUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePipeline = `-- name: UpdatePipeline :execrows
UPDATE pipelines SET name = $1, description = $2,
  worker_configuration = COALESCE($3::jsonb, worker_configuration),
  updated_at = now()
WHERE id = $4 AND NOT is_deleted
`

type UpdatePipelineParams struct {
	Name                string
	Description         string
	WorkerConfiguration []byte
	PipelineID          string
}

func (q *Queries) UpdatePipeline(ctx context.Context, arg UpdatePipelineParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePipeline,
		arg.Name,
		arg.Description,
		arg.WorkerConfiguration,
		arg.PipelineID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
