// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: run_resource_checkpoints.sql

package sqlcgen

import (
	"context"
)

const loadCheckpoint = `-- name: LoadCheckpoint :one
SELECT cursor FROM run_resource_checkpoints WHERE run_id = $1 AND resource_name = $2
`

type LoadCheckpointParams struct {
	RunID        string
	ResourceName string
}

func (q *Queries) LoadCheckpoint(ctx context.Context, arg LoadCheckpointParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, loadCheckpoint, arg.RunID, arg.ResourceName)
	var cursor []byte
	err := row.Scan(&cursor)
	return cursor, err
}

const saveCheckpoint = `-- name: SaveCheckpoint :exec
INSERT INTO run_resource_checkpoints (tenant_id, run_id, resource_name, cursor, updated_at)
SELECT tenant_id, $1, $2, $3, now()
FROM runs
WHERE id = $1
ON CONFLICT (run_id, resource_name) DO UPDATE SET cursor = EXCLUDED.cursor, updated_at = now()
`

type SaveCheckpointParams struct {
	RunID        string
	ResourceName string
	Cursor       []byte
}

func (q *Queries) SaveCheckpoint(ctx context.Context, arg SaveCheckpointParams) error {
	_, err := q.db.Exec(ctx, saveCheckpoint, arg.RunID, arg.ResourceName, arg.Cursor)
	return err
}
