// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stream_runtime.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const changeStreamDesiredState = `-- name: ChangeStreamDesiredState :execrows
UPDATE replication_streams SET desired_state = $1, desired_revision = desired_revision + 1, updated_at = clock_timestamp()
WHERE id = $2 AND tenant_id = $3 AND desired_revision = $4 AND current_run_id IS NOT NULL
`

type ChangeStreamDesiredStateParams struct {
	DesiredState string
	StreamID     string
	TenantID     string
	Revision     int64
}

func (q *Queries) ChangeStreamDesiredState(ctx context.Context, arg ChangeStreamDesiredStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, changeStreamDesiredState,
		arg.DesiredState,
		arg.StreamID,
		arg.TenantID,
		arg.Revision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createStreamAttempt = `-- name: CreateStreamAttempt :one
INSERT INTO stream_attempts(stream_id,tenant_id,execution_id,desired_revision,request_ttl_us,expires_at)
VALUES($1,$2,$3,$4,$5,clock_timestamp() + $5::bigint * interval '1 microsecond') RETURNING token, stream_id, tenant_id, execution_id, desired_revision, request_ttl_us, started_at, expires_at, ended_at, termination, reason
`

type CreateStreamAttemptParams struct {
	StreamID        string
	TenantID        string
	ExecutionID     string
	DesiredRevision int64
	TtlUs           int64
}

func (q *Queries) CreateStreamAttempt(ctx context.Context, arg CreateStreamAttemptParams) (*StreamAttempt, error) {
	row := q.db.QueryRow(ctx, createStreamAttempt,
		arg.StreamID,
		arg.TenantID,
		arg.ExecutionID,
		arg.DesiredRevision,
		arg.TtlUs,
	)
	var i StreamAttempt
	err := row.Scan(
		&i.Token,
		&i.StreamID,
		&i.TenantID,
		&i.ExecutionID,
		&i.DesiredRevision,
		&i.RequestTtlUs,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.EndedAt,
		&i.Termination,
		&i.Reason,
	)
	return &i, err
}

const endStreamAttempt = `-- name: EndStreamAttempt :execrows
UPDATE stream_attempts SET ended_at = clock_timestamp(), termination = $1, reason = $2
WHERE token = $3 AND tenant_id = $4 AND ended_at IS NULL AND (NOT $5::boolean OR expires_at > clock_timestamp())
`

type EndStreamAttemptParams struct {
	Termination pgtype.Text
	Reason      string
	Token       int64
	TenantID    string
	RequireLive bool
}

func (q *Queries) EndStreamAttempt(ctx context.Context, arg EndStreamAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, endStreamAttempt,
		arg.Termination,
		arg.Reason,
		arg.Token,
		arg.TenantID,
		arg.RequireLive,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLatestRouteAttempt = `-- name: GetLatestRouteAttempt :one
SELECT a.token, a.stream_id, a.tenant_id, a.execution_id, a.desired_revision, a.request_ttl_us, a.started_at, a.expires_at, a.ended_at, a.termination, a.reason FROM stream_attempts a JOIN replication_streams s ON s.id = a.stream_id
WHERE s.pipeline_id = $1 AND s.route_key = $2 AND s.tenant_id = $3
ORDER BY a.token DESC LIMIT 1
`

type GetLatestRouteAttemptParams struct {
	PipelineID string
	Route      string
	TenantID   string
}

func (q *Queries) GetLatestRouteAttempt(ctx context.Context, arg GetLatestRouteAttemptParams) (*StreamAttempt, error) {
	row := q.db.QueryRow(ctx, getLatestRouteAttempt, arg.PipelineID, arg.Route, arg.TenantID)
	var i StreamAttempt
	err := row.Scan(
		&i.Token,
		&i.StreamID,
		&i.TenantID,
		&i.ExecutionID,
		&i.DesiredRevision,
		&i.RequestTtlUs,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.EndedAt,
		&i.Termination,
		&i.Reason,
	)
	return &i, err
}

const getLatestStreamAttempt = `-- name: GetLatestStreamAttempt :one
SELECT token, stream_id, tenant_id, execution_id, desired_revision, request_ttl_us, started_at, expires_at, ended_at, termination, reason FROM stream_attempts WHERE stream_id = $1 AND tenant_id = $2 ORDER BY token DESC LIMIT 1
`

type GetLatestStreamAttemptParams struct {
	StreamID string
	TenantID string
}

func (q *Queries) GetLatestStreamAttempt(ctx context.Context, arg GetLatestStreamAttemptParams) (*StreamAttempt, error) {
	row := q.db.QueryRow(ctx, getLatestStreamAttempt, arg.StreamID, arg.TenantID)
	var i StreamAttempt
	err := row.Scan(
		&i.Token,
		&i.StreamID,
		&i.TenantID,
		&i.ExecutionID,
		&i.DesiredRevision,
		&i.RequestTtlUs,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.EndedAt,
		&i.Termination,
		&i.Reason,
	)
	return &i, err
}

const getReplicationStreamPipelineID = `-- name: GetReplicationStreamPipelineID :one
SELECT pipeline_id FROM replication_streams WHERE id = $1 AND tenant_id = $2 AND generation = $3
`

type GetReplicationStreamPipelineIDParams struct {
	StreamID   string
	TenantID   string
	Generation int64
}

func (q *Queries) GetReplicationStreamPipelineID(ctx context.Context, arg GetReplicationStreamPipelineIDParams) (string, error) {
	row := q.db.QueryRow(ctx, getReplicationStreamPipelineID, arg.StreamID, arg.TenantID, arg.Generation)
	var pipeline_id string
	err := row.Scan(&pipeline_id)
	return pipeline_id, err
}

const getStreamAttemptByExecutionID = `-- name: GetStreamAttemptByExecutionID :one
SELECT token, stream_id, tenant_id, execution_id, desired_revision, request_ttl_us, started_at, expires_at, ended_at, termination, reason FROM stream_attempts WHERE tenant_id = $1 AND execution_id = $2
`

type GetStreamAttemptByExecutionIDParams struct {
	TenantID    string
	ExecutionID string
}

func (q *Queries) GetStreamAttemptByExecutionID(ctx context.Context, arg GetStreamAttemptByExecutionIDParams) (*StreamAttempt, error) {
	row := q.db.QueryRow(ctx, getStreamAttemptByExecutionID, arg.TenantID, arg.ExecutionID)
	var i StreamAttempt
	err := row.Scan(
		&i.Token,
		&i.StreamID,
		&i.TenantID,
		&i.ExecutionID,
		&i.DesiredRevision,
		&i.RequestTtlUs,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.EndedAt,
		&i.Termination,
		&i.Reason,
	)
	return &i, err
}

const getStreamExecution = `-- name: GetStreamExecution :one
SELECT coalesce(s.current_run_id::text, '')::text AS run_id,
 coalesce(s.run_spec->>'PipelineVersionID', '')::text AS pipeline_version_id,
 s.desired_state, s.desired_revision AS revision, s.run_spec, s.last_epoch
FROM replication_streams s
WHERE s.id = $1 AND s.tenant_id = $2 AND s.current_run_id IS NOT NULL
`

type GetStreamExecutionParams struct {
	StreamID string
	TenantID string
}

type GetStreamExecutionRow struct {
	RunID             string
	PipelineVersionID string
	DesiredState      string
	Revision          int64
	RunSpec           []byte
	LastEpoch         int64
}

func (q *Queries) GetStreamExecution(ctx context.Context, arg GetStreamExecutionParams) (*GetStreamExecutionRow, error) {
	row := q.db.QueryRow(ctx, getStreamExecution, arg.StreamID, arg.TenantID)
	var i GetStreamExecutionRow
	err := row.Scan(
		&i.RunID,
		&i.PipelineVersionID,
		&i.DesiredState,
		&i.Revision,
		&i.RunSpec,
		&i.LastEpoch,
	)
	return &i, err
}

const initializeStreamExecution = `-- name: InitializeStreamExecution :exec
UPDATE replication_streams SET current_run_id = $1, desired_state = 'enabled',
 desired_revision = 1, run_spec = $2, updated_at = clock_timestamp()
WHERE id = $3 AND tenant_id = $4 AND current_run_id IS NULL
`

type InitializeStreamExecutionParams struct {
	RunID    pgtype.Text
	RunSpec  []byte
	StreamID string
	TenantID string
}

func (q *Queries) InitializeStreamExecution(ctx context.Context, arg InitializeStreamExecutionParams) error {
	_, err := q.db.Exec(ctx, initializeStreamExecution,
		arg.RunID,
		arg.RunSpec,
		arg.StreamID,
		arg.TenantID,
	)
	return err
}

const latestStreamPositions = `-- name: LatestStreamPositions :one
SELECT e.positions FROM replication_streams s JOIN stream_epochs e ON e.stream_id = s.id AND e.epoch = s.last_epoch
WHERE s.id = $1 AND s.tenant_id = $2
`

type LatestStreamPositionsParams struct {
	StreamID string
	TenantID string
}

func (q *Queries) LatestStreamPositions(ctx context.Context, arg LatestStreamPositionsParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, latestStreamPositions, arg.StreamID, arg.TenantID)
	var positions []byte
	err := row.Scan(&positions)
	return positions, err
}

const listReconcilableStreamIDs = `-- name: ListReconcilableStreamIDs :many
SELECT id FROM replication_streams
WHERE tenant_id = $1 AND status = 0 AND current_run_id IS NOT NULL AND id::text > $2::text
ORDER BY id::text LIMIT $3
`

type ListReconcilableStreamIDsParams struct {
	TenantID  string
	AfterID   string
	PageLimit int32
}

func (q *Queries) ListReconcilableStreamIDs(ctx context.Context, arg ListReconcilableStreamIDsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listReconcilableStreamIDs, arg.TenantID, arg.AfterID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadRunRequest = `-- name: LoadRunRequest :one
SELECT r.request FROM runs r JOIN pipeline_versions v ON v.id = r.pipeline_version_id
WHERE r.id = $1 AND r.tenant_id = $2 AND r.pipeline_id = $3
AND r.pipeline_version_id = $4 AND v.tenant_id = $2
`

type LoadRunRequestParams struct {
	RunID             string
	TenantID          string
	PipelineID        pgtype.Text
	PipelineVersionID pgtype.Text
}

func (q *Queries) LoadRunRequest(ctx context.Context, arg LoadRunRequestParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, loadRunRequest,
		arg.RunID,
		arg.TenantID,
		arg.PipelineID,
		arg.PipelineVersionID,
	)
	var request []byte
	err := row.Scan(&request)
	return request, err
}

const lockReplicationStreamGeneration = `-- name: LockReplicationStreamGeneration :one
SELECT id, tenant_id, pipeline_id, route_key, generation, source_connection_id, sink_connection_id, consumer_name, consumer_config, continuity_fingerprint, status, created_from_pipeline_version_id, error, retired_at, created_by_user_id, updated_by_user_id, deleted_by_user_id, created_at, updated_at, membership_revision, current_run_id, desired_state, desired_revision, run_spec, last_epoch FROM replication_streams WHERE id = $1 AND tenant_id = $2 AND generation = $3 FOR UPDATE
`

type LockReplicationStreamGenerationParams struct {
	StreamID   string
	TenantID   string
	Generation int64
}

func (q *Queries) LockReplicationStreamGeneration(ctx context.Context, arg LockReplicationStreamGenerationParams) (*ReplicationStream, error) {
	row := q.db.QueryRow(ctx, lockReplicationStreamGeneration, arg.StreamID, arg.TenantID, arg.Generation)
	var i ReplicationStream
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PipelineID,
		&i.RouteKey,
		&i.Generation,
		&i.SourceConnectionID,
		&i.SinkConnectionID,
		&i.ConsumerName,
		&i.ConsumerConfig,
		&i.ContinuityFingerprint,
		&i.Status,
		&i.CreatedFromPipelineVersionID,
		&i.Error,
		&i.RetiredAt,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.DeletedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MembershipRevision,
		&i.CurrentRunID,
		&i.DesiredState,
		&i.DesiredRevision,
		&i.RunSpec,
		&i.LastEpoch,
	)
	return &i, err
}

const now = `-- name: Now :one
SELECT clock_timestamp()::timestamptz
`

func (q *Queries) Now(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, now)
	var column_1 pgtype.Timestamptz
	err := row.Scan(&column_1)
	return column_1, err
}

const renewStreamAttempt = `-- name: RenewStreamAttempt :execrows
UPDATE stream_attempts SET expires_at = GREATEST(expires_at, clock_timestamp() + $1::bigint * interval '1 microsecond')
WHERE token = $2 AND tenant_id = $3 AND ended_at IS NULL AND expires_at > clock_timestamp()
`

type RenewStreamAttemptParams struct {
	TtlUs    int64
	Token    int64
	TenantID string
}

func (q *Queries) RenewStreamAttempt(ctx context.Context, arg RenewStreamAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, renewStreamAttempt, arg.TtlUs, arg.Token, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
