// This file was auto-generated by Fern from our API Definition.

import type * as Filament from "../../../../index.js";

/**
 * @example
 *     {
 *         "Connect-Timeout-Ms": 1000
 *     }
 */
export interface IngestionV1GetRunRequest {
    /** Define the timeout, in ms */
    "Connect-Timeout-Ms"?: Filament.ConnectTimeoutHeader;
    runId?: string;
}
