apiVersion: v2
name: filament
description: A Helm chart for Filament

version: 0.0.28
appVersion: 0.0.29

dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 18.7.11
    condition: postgresql.enabled
  - name: nats
    version: 2.14.2
    repository: https://nats-io.github.io/k8s/helm/charts
    condition: nats.enabled
  - name: zitadel
    version: 10.0.4
    repository: https://charts.zitadel.com
    condition: zitadel.enabled
