export const PIPELINE_CARD_HEIGHT = 48;
export const PIPELINE_CARD_HEIGHT_COMPACT = 40;
export const PIPELINE_INDICATOR_WIDTH = 16;

export const PIPELINE_METRIC_COLUMN_WIDTH_CONNECTORS = 180;
export const PIPELINE_METRIC_COLUMN_WIDTH_LAST_RUN = 120;
export const PIPELINE_METRIC_COLUMN_WIDTH_VOLUME = 120;
export const PIPELINE_METRIC_COLUMN_WIDTH_VERSION = 100;
