// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ingestion/v1/connectors.proto

package ingestionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectorMaturity int32

const (
	ConnectorMaturity_CONNECTOR_MATURITY_UNSPECIFIED ConnectorMaturity = 0
	ConnectorMaturity_CONNECTOR_MATURITY_ALPHA       ConnectorMaturity = 1
	ConnectorMaturity_CONNECTOR_MATURITY_BETA        ConnectorMaturity = 2
	ConnectorMaturity_CONNECTOR_MATURITY_STABLE      ConnectorMaturity = 3
)

// Enum value maps for ConnectorMaturity.
var (
	ConnectorMaturity_name = map[int32]string{
		0: "CONNECTOR_MATURITY_UNSPECIFIED",
		1: "CONNECTOR_MATURITY_ALPHA",
		2: "CONNECTOR_MATURITY_BETA",
		3: "CONNECTOR_MATURITY_STABLE",
	}
	ConnectorMaturity_value = map[string]int32{
		"CONNECTOR_MATURITY_UNSPECIFIED": 0,
		"CONNECTOR_MATURITY_ALPHA":       1,
		"CONNECTOR_MATURITY_BETA":        2,
		"CONNECTOR_MATURITY_STABLE":      3,
	}
)

func (x ConnectorMaturity) Enum() *ConnectorMaturity {
	p := new(ConnectorMaturity)
	*p = x
	return p
}

func (x ConnectorMaturity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectorMaturity) Descriptor() protoreflect.EnumDescriptor {
	return file_ingestion_v1_connectors_proto_enumTypes[0].Descriptor()
}

func (ConnectorMaturity) Type() protoreflect.EnumType {
	return &file_ingestion_v1_connectors_proto_enumTypes[0]
}

func (x ConnectorMaturity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectorMaturity.Descriptor instead.
func (ConnectorMaturity) EnumDescriptor() ([]byte, []int) {
	return file_ingestion_v1_connectors_proto_rawDescGZIP(), []int{0}
}

// ConnectorSpec describes one registered source or sink connector.
type ConnectorSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Kind          ConnectorKind          `protobuf:"varint,3,opt,name=kind,proto3,enum=ingestion.v1.ConnectorKind" json:"kind,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Modes         []ReplicationMode      `protobuf:"varint,5,rep,packed,name=modes,proto3,enum=ingestion.v1.ReplicationMode" json:"modes,omitempty"`
	ConfigSchema  *ConfigSchema          `protobuf:"bytes,6,opt,name=config_schema,json=configSchema,proto3" json:"config_schema,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	DarkLogoUrl   string                 `protobuf:"bytes,9,opt,name=dark_logo_url,json=darkLogoUrl,proto3" json:"dark_logo_url,omitempty"`
	LightLogoUrl  string                 `protobuf:"bytes,10,opt,name=light_logo_url,json=lightLogoUrl,proto3" json:"light_logo_url,omitempty"`
	SchemaField   string                 `protobuf:"bytes,11,opt,name=schema_field,json=schemaField,proto3" json:"schema_field,omitempty"`
	Maturity      ConnectorMaturity      `protobuf:"varint,12,opt,name=maturity,proto3,enum=ingestion.v1.ConnectorMaturity" json:"maturity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectorSpec) Reset() {
	*x = ConnectorSpec{}
	mi := &file_ingestion_v1_connectors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectorSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectorSpec) ProtoMessage() {}

func (x *ConnectorSpec) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_connectors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectorSpec.ProtoReflect.Descriptor instead.
func (*ConnectorSpec) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_connectors_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectorSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConnectorSpec) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ConnectorSpec) GetKind() ConnectorKind {
	if x != nil {
		return x.Kind
	}
	return ConnectorKind_CONNECTOR_KIND_UNSPECIFIED
}

func (x *ConnectorSpec) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ConnectorSpec) GetModes() []ReplicationMode {
	if x != nil {
		return x.Modes
	}
	return nil
}

func (x *ConnectorSpec) GetConfigSchema() *ConfigSchema {
	if x != nil {
		return x.ConfigSchema
	}
	return nil
}

func (x *ConnectorSpec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ConnectorSpec) GetDarkLogoUrl() string {
	if x != nil {
		return x.DarkLogoUrl
	}
	return ""
}

func (x *ConnectorSpec) GetLightLogoUrl() string {
	if x != nil {
		return x.LightLogoUrl
	}
	return ""
}

func (x *ConnectorSpec) GetSchemaField() string {
	if x != nil {
		return x.SchemaField
	}
	return ""
}

func (x *ConnectorSpec) GetMaturity() ConnectorMaturity {
	if x != nil {
		return x.Maturity
	}
	return ConnectorMaturity_CONNECTOR_MATURITY_UNSPECIFIED
}

type ListConnectorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Kind          ConnectorKind          `protobuf:"varint,2,opt,name=kind,proto3,enum=ingestion.v1.ConnectorKind" json:"kind,omitempty"`
	Pagination    *PaginationRequest     `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Search        string                 `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	Sorting       *SortingRequest        `protobuf:"bytes,5,opt,name=sorting,proto3" json:"sorting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConnectorsRequest) Reset() {
	*x = ListConnectorsRequest{}
	mi := &file_ingestion_v1_connectors_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConnectorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConnectorsRequest) ProtoMessage() {}

func (x *ListConnectorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_connectors_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConnectorsRequest.ProtoReflect.Descriptor instead.
func (*ListConnectorsRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_connectors_proto_rawDescGZIP(), []int{1}
}

func (x *ListConnectorsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListConnectorsRequest) GetKind() ConnectorKind {
	if x != nil {
		return x.Kind
	}
	return ConnectorKind_CONNECTOR_KIND_UNSPECIFIED
}

func (x *ListConnectorsRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListConnectorsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListConnectorsRequest) GetSorting() *SortingRequest {
	if x != nil {
		return x.Sorting
	}
	return nil
}

type ListConnectorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connectors    []*ConnectorSpec       `protobuf:"bytes,1,rep,name=connectors,proto3" json:"connectors,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConnectorsResponse) Reset() {
	*x = ListConnectorsResponse{}
	mi := &file_ingestion_v1_connectors_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConnectorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConnectorsResponse) ProtoMessage() {}

func (x *ListConnectorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_connectors_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConnectorsResponse.ProtoReflect.Descriptor instead.
func (*ListConnectorsResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_connectors_proto_rawDescGZIP(), []int{2}
}

func (x *ListConnectorsResponse) GetConnectors() []*ConnectorSpec {
	if x != nil {
		return x.Connectors
	}
	return nil
}

func (x *ListConnectorsResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetConnectorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Connector     string                 `protobuf:"bytes,2,opt,name=connector,proto3" json:"connector,omitempty"`
	Kind          ConnectorKind          `protobuf:"varint,3,opt,name=kind,proto3,enum=ingestion.v1.ConnectorKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConnectorRequest) Reset() {
	*x = GetConnectorRequest{}
	mi := &file_ingestion_v1_connectors_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectorRequest) ProtoMessage() {}

func (x *GetConnectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_connectors_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectorRequest.ProtoReflect.Descriptor instead.
func (*GetConnectorRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_connectors_proto_rawDescGZIP(), []int{3}
}

func (x *GetConnectorRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetConnectorRequest) GetConnector() string {
	if x != nil {
		return x.Connector
	}
	return ""
}

func (x *GetConnectorRequest) GetKind() ConnectorKind {
	if x != nil {
		return x.Kind
	}
	return ConnectorKind_CONNECTOR_KIND_UNSPECIFIED
}

type GetConnectorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connector     *ConnectorSpec         `protobuf:"bytes,1,opt,name=connector,proto3" json:"connector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConnectorResponse) Reset() {
	*x = GetConnectorResponse{}
	mi := &file_ingestion_v1_connectors_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectorResponse) ProtoMessage() {}

func (x *GetConnectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_connectors_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectorResponse.ProtoReflect.Descriptor instead.
func (*GetConnectorResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_connectors_proto_rawDescGZIP(), []int{4}
}

func (x *GetConnectorResponse) GetConnector() *ConnectorSpec {
	if x != nil {
		return x.Connector
	}
	return nil
}

type ValidateConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Kind          ConnectorKind          `protobuf:"varint,2,opt,name=kind,proto3,enum=ingestion.v1.ConnectorKind" json:"kind,omitempty"`
	Connector     string                 `protobuf:"bytes,3,opt,name=connector,proto3" json:"connector,omitempty"`
	Config        *structpb.Struct       `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	ConnectionId  string                 `protobuf:"bytes,6,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateConfigRequest) Reset() {
	*x = ValidateConfigRequest{}
	mi := &file_ingestion_v1_connectors_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateConfigRequest) ProtoMessage() {}

func (x *ValidateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_connectors_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateConfigRequest.ProtoReflect.Descriptor instead.
func (*ValidateConfigRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_connectors_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateConfigRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ValidateConfigRequest) GetKind() ConnectorKind {
	if x != nil {
		return x.Kind
	}
	return ConnectorKind_CONNECTOR_KIND_UNSPECIFIED
}

func (x *ValidateConfigRequest) GetConnector() string {
	if x != nil {
		return x.Connector
	}
	return ""
}

func (x *ValidateConfigRequest) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ValidateConfigRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

type ValidationError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationError) Reset() {
	*x = ValidationError{}
	mi := &file_ingestion_v1_connectors_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationError) ProtoMessage() {}

func (x *ValidationError) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_connectors_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationError.ProtoReflect.Descriptor instead.
func (*ValidationError) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_connectors_proto_rawDescGZIP(), []int{6}
}

func (x *ValidationError) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ValidationError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ValidateConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Errors        []*ValidationError     `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateConfigResponse) Reset() {
	*x = ValidateConfigResponse{}
	mi := &file_ingestion_v1_connectors_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateConfigResponse) ProtoMessage() {}

func (x *ValidateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_connectors_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateConfigResponse.ProtoReflect.Descriptor instead.
func (*ValidateConfigResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_connectors_proto_rawDescGZIP(), []int{7}
}

func (x *ValidateConfigResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateConfigResponse) GetErrors() []*ValidationError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type DiscoverResourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Connector     string                 `protobuf:"bytes,2,opt,name=connector,proto3" json:"connector,omitempty"`
	Config        *structpb.Struct       `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	Refresh       bool                   `protobuf:"varint,4,opt,name=refresh,proto3" json:"refresh,omitempty"`
	ConnectionId  string                 `protobuf:"bytes,5,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverResourcesRequest) Reset() {
	*x = DiscoverResourcesRequest{}
	mi := &file_ingestion_v1_connectors_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverResourcesRequest) ProtoMessage() {}

func (x *DiscoverResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_connectors_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverResourcesRequest.ProtoReflect.Descriptor instead.
func (*DiscoverResourcesRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_connectors_proto_rawDescGZIP(), []int{8}
}

func (x *DiscoverResourcesRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DiscoverResourcesRequest) GetConnector() string {
	if x != nil {
		return x.Connector
	}
	return ""
}

func (x *DiscoverResourcesRequest) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *DiscoverResourcesRequest) GetRefresh() bool {
	if x != nil {
		return x.Refresh
	}
	return false
}

func (x *DiscoverResourcesRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsSelectable  bool                   `protobuf:"varint,2,opt,name=is_selectable,json=isSelectable,proto3" json:"is_selectable,omitempty"`
	PrimaryKey    []string               `protobuf:"bytes,3,rep,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`
	Selector      string                 `protobuf:"bytes,5,opt,name=selector,proto3" json:"selector,omitempty"`
	DisplayName   string                 `protobuf:"bytes,6,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_ingestion_v1_connectors_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_connectors_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_connectors_proto_rawDescGZIP(), []int{9}
}

func (x *Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resource) GetIsSelectable() bool {
	if x != nil {
		return x.IsSelectable
	}
	return false
}

func (x *Resource) GetPrimaryKey() []string {
	if x != nil {
		return x.PrimaryKey
	}
	return nil
}

func (x *Resource) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *Resource) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Resource) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DiscoverResourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resources     []*Resource            `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverResourcesResponse) Reset() {
	*x = DiscoverResourcesResponse{}
	mi := &file_ingestion_v1_connectors_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverResourcesResponse) ProtoMessage() {}

func (x *DiscoverResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_connectors_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverResourcesResponse.ProtoReflect.Descriptor instead.
func (*DiscoverResourcesResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_connectors_proto_rawDescGZIP(), []int{10}
}

func (x *DiscoverResourcesResponse) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

type GetResourceColumnsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Connector     string                 `protobuf:"bytes,2,opt,name=connector,proto3" json:"connector,omitempty"`
	Config        *structpb.Struct       `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	ConnectionId  string                 `protobuf:"bytes,4,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	Resources     []string               `protobuf:"bytes,5,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceColumnsRequest) Reset() {
	*x = GetResourceColumnsRequest{}
	mi := &file_ingestion_v1_connectors_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceColumnsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceColumnsRequest) ProtoMessage() {}

func (x *GetResourceColumnsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_connectors_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceColumnsRequest.ProtoReflect.Descriptor instead.
func (*GetResourceColumnsRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_connectors_proto_rawDescGZIP(), []int{11}
}

func (x *GetResourceColumnsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetResourceColumnsRequest) GetConnector() string {
	if x != nil {
		return x.Connector
	}
	return ""
}

func (x *GetResourceColumnsRequest) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *GetResourceColumnsRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *GetResourceColumnsRequest) GetResources() []string {
	if x != nil {
		return x.Resources
	}
	return nil
}

type ResourceColumn struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	LogicalType         string                 `protobuf:"bytes,2,opt,name=logical_type,json=logicalType,proto3" json:"logical_type,omitempty"`
	NativeType          string                 `protobuf:"bytes,3,opt,name=native_type,json=nativeType,proto3" json:"native_type,omitempty"`
	IsNullable          bool                   `protobuf:"varint,4,opt,name=is_nullable,json=isNullable,proto3" json:"is_nullable,omitempty"`
	IsPrimaryKey        bool                   `protobuf:"varint,5,opt,name=is_primary_key,json=isPrimaryKey,proto3" json:"is_primary_key,omitempty"`
	IsCursorEligible    bool                   `protobuf:"varint,6,opt,name=is_cursor_eligible,json=isCursorEligible,proto3" json:"is_cursor_eligible,omitempty"`
	IsCursorRecommended bool                   `protobuf:"varint,7,opt,name=is_cursor_recommended,json=isCursorRecommended,proto3" json:"is_cursor_recommended,omitempty"`
	RecommendationRank  int32                  `protobuf:"varint,8,opt,name=recommendation_rank,json=recommendationRank,proto3" json:"recommendation_rank,omitempty"`
	Warning             string                 `protobuf:"bytes,9,opt,name=warning,proto3" json:"warning,omitempty"`
	IsConfigurable      bool                   `protobuf:"varint,10,opt,name=is_configurable,json=isConfigurable,proto3" json:"is_configurable,omitempty"`
	SupportsLookback    bool                   `protobuf:"varint,11,opt,name=supports_lookback,json=supportsLookback,proto3" json:"supports_lookback,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ResourceColumn) Reset() {
	*x = ResourceColumn{}
	mi := &file_ingestion_v1_connectors_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceColumn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceColumn) ProtoMessage() {}

func (x *ResourceColumn) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_connectors_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceColumn.ProtoReflect.Descriptor instead.
func (*ResourceColumn) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_connectors_proto_rawDescGZIP(), []int{12}
}

func (x *ResourceColumn) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceColumn) GetLogicalType() string {
	if x != nil {
		return x.LogicalType
	}
	return ""
}

func (x *ResourceColumn) GetNativeType() string {
	if x != nil {
		return x.NativeType
	}
	return ""
}

func (x *ResourceColumn) GetIsNullable() bool {
	if x != nil {
		return x.IsNullable
	}
	return false
}

func (x *ResourceColumn) GetIsPrimaryKey() bool {
	if x != nil {
		return x.IsPrimaryKey
	}
	return false
}

func (x *ResourceColumn) GetIsCursorEligible() bool {
	if x != nil {
		return x.IsCursorEligible
	}
	return false
}

func (x *ResourceColumn) GetIsCursorRecommended() bool {
	if x != nil {
		return x.IsCursorRecommended
	}
	return false
}

func (x *ResourceColumn) GetRecommendationRank() int32 {
	if x != nil {
		return x.RecommendationRank
	}
	return 0
}

func (x *ResourceColumn) GetWarning() string {
	if x != nil {
		return x.Warning
	}
	return ""
}

func (x *ResourceColumn) GetIsConfigurable() bool {
	if x != nil {
		return x.IsConfigurable
	}
	return false
}

func (x *ResourceColumn) GetSupportsLookback() bool {
	if x != nil {
		return x.SupportsLookback
	}
	return false
}

type ResourceColumns struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Columns       []*ResourceColumn      `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceColumns) Reset() {
	*x = ResourceColumns{}
	mi := &file_ingestion_v1_connectors_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceColumns) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceColumns) ProtoMessage() {}

func (x *ResourceColumns) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_connectors_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceColumns.ProtoReflect.Descriptor instead.
func (*ResourceColumns) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_connectors_proto_rawDescGZIP(), []int{13}
}

func (x *ResourceColumns) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *ResourceColumns) GetColumns() []*ResourceColumn {
	if x != nil {
		return x.Columns
	}
	return nil
}

type GetResourceColumnsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resources     []*ResourceColumns     `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceColumnsResponse) Reset() {
	*x = GetResourceColumnsResponse{}
	mi := &file_ingestion_v1_connectors_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceColumnsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceColumnsResponse) ProtoMessage() {}

func (x *GetResourceColumnsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_connectors_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceColumnsResponse.ProtoReflect.Descriptor instead.
func (*GetResourceColumnsResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_connectors_proto_rawDescGZIP(), []int{14}
}

func (x *GetResourceColumnsResponse) GetResources() []*ResourceColumns {
	if x != nil {
		return x.Resources
	}
	return nil
}

var File_ingestion_v1_connectors_proto protoreflect.FileDescriptor

const file_ingestion_v1_connectors_proto_rawDesc = "" +
	"\n" +
	"\x1dingestion/v1/connectors.proto\x12\fingestion.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x19ingestion/v1/common.proto\x1a\x1dingestion/v1/pagination.proto\x1a\x1aingestion/v1/sorting.proto\"\xd3\x03\n" +
	"\rConnectorSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12/\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x1b.ingestion.v1.ConnectorKindR\x04kind\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x123\n" +
	"\x05modes\x18\x05 \x03(\x0e2\x1d.ingestion.v1.ReplicationModeR\x05modes\x12?\n" +
	"\rconfig_schema\x18\x06 \x01(\v2\x1a.ingestion.v1.ConfigSchemaR\fconfigSchema\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\"\n" +
	"\rdark_logo_url\x18\t \x01(\tR\vdarkLogoUrl\x12$\n" +
	"\x0elight_logo_url\x18\n" +
	" \x01(\tR\flightLogoUrl\x12!\n" +
	"\fschema_field\x18\v \x01(\tR\vschemaField\x12;\n" +
	"\bmaturity\x18\f \x01(\x0e2\x1f.ingestion.v1.ConnectorMaturityR\bmaturity\"\xf6\x01\n" +
	"\x15ListConnectorsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12/\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1b.ingestion.v1.ConnectorKindR\x04kind\x12?\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x1f.ingestion.v1.PaginationRequestR\n" +
	"pagination\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search\x126\n" +
	"\asorting\x18\x05 \x01(\v2\x1c.ingestion.v1.SortingRequestR\asorting\"\x97\x01\n" +
	"\x16ListConnectorsResponse\x12;\n" +
	"\n" +
	"connectors\x18\x01 \x03(\v2\x1b.ingestion.v1.ConnectorSpecR\n" +
	"connectors\x12@\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2 .ingestion.v1.PaginationResponseR\n" +
	"pagination\"\x81\x01\n" +
	"\x13GetConnectorRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1c\n" +
	"\tconnector\x18\x02 \x01(\tR\tconnector\x12/\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x1b.ingestion.v1.ConnectorKindR\x04kind\"Q\n" +
	"\x14GetConnectorResponse\x129\n" +
	"\tconnector\x18\x01 \x01(\v2\x1b.ingestion.v1.ConnectorSpecR\tconnector\"\xd9\x01\n" +
	"\x15ValidateConfigRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12/\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1b.ingestion.v1.ConnectorKindR\x04kind\x12\x1c\n" +
	"\tconnector\x18\x03 \x01(\tR\tconnector\x12/\n" +
	"\x06config\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x06config\x12#\n" +
	"\rconnection_id\x18\x06 \x01(\tR\fconnectionId\"A\n" +
	"\x0fValidationError\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"e\n" +
	"\x16ValidateConfigResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x125\n" +
	"\x06errors\x18\x02 \x03(\v2\x1d.ingestion.v1.ValidationErrorR\x06errors\"\xc5\x01\n" +
	"\x18DiscoverResourcesRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1c\n" +
	"\tconnector\x18\x02 \x01(\tR\tconnector\x12/\n" +
	"\x06config\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06config\x12\x18\n" +
	"\arefresh\x18\x04 \x01(\bR\arefresh\x12#\n" +
	"\rconnection_id\x18\x05 \x01(\tR\fconnectionId\"\xa2\x02\n" +
	"\bResource\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\ris_selectable\x18\x02 \x01(\bR\fisSelectable\x12\x1f\n" +
	"\vprimary_key\x18\x03 \x03(\tR\n" +
	"primaryKey\x12\x1a\n" +
	"\bselector\x18\x05 \x01(\tR\bselector\x12!\n" +
	"\fdisplay_name\x18\x06 \x01(\tR\vdisplayName\x12@\n" +
	"\bmetadata\x18\a \x03(\v2$.ingestion.v1.Resource.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Q\n" +
	"\x19DiscoverResourcesResponse\x124\n" +
	"\tresources\x18\x01 \x03(\v2\x16.ingestion.v1.ResourceR\tresources\"\xca\x01\n" +
	"\x19GetResourceColumnsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1c\n" +
	"\tconnector\x18\x02 \x01(\tR\tconnector\x12/\n" +
	"\x06config\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06config\x12#\n" +
	"\rconnection_id\x18\x04 \x01(\tR\fconnectionId\x12\x1c\n" +
	"\tresources\x18\x05 \x03(\tR\tresources\"\xb2\x03\n" +
	"\x0eResourceColumn\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\flogical_type\x18\x02 \x01(\tR\vlogicalType\x12\x1f\n" +
	"\vnative_type\x18\x03 \x01(\tR\n" +
	"nativeType\x12\x1f\n" +
	"\vis_nullable\x18\x04 \x01(\bR\n" +
	"isNullable\x12$\n" +
	"\x0eis_primary_key\x18\x05 \x01(\bR\fisPrimaryKey\x12,\n" +
	"\x12is_cursor_eligible\x18\x06 \x01(\bR\x10isCursorEligible\x122\n" +
	"\x15is_cursor_recommended\x18\a \x01(\bR\x13isCursorRecommended\x12/\n" +
	"\x13recommendation_rank\x18\b \x01(\x05R\x12recommendationRank\x12\x18\n" +
	"\awarning\x18\t \x01(\tR\awarning\x12'\n" +
	"\x0fis_configurable\x18\n" +
	" \x01(\bR\x0eisConfigurable\x12+\n" +
	"\x11supports_lookback\x18\v \x01(\bR\x10supportsLookback\"e\n" +
	"\x0fResourceColumns\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x126\n" +
	"\acolumns\x18\x02 \x03(\v2\x1c.ingestion.v1.ResourceColumnR\acolumns\"Y\n" +
	"\x1aGetResourceColumnsResponse\x12;\n" +
	"\tresources\x18\x01 \x03(\v2\x1d.ingestion.v1.ResourceColumnsR\tresources*\x91\x01\n" +
	"\x11ConnectorMaturity\x12\"\n" +
	"\x1eCONNECTOR_MATURITY_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18CONNECTOR_MATURITY_ALPHA\x10\x01\x12\x1b\n" +
	"\x17CONNECTOR_MATURITY_BETA\x10\x02\x12\x1d\n" +
	"\x19CONNECTOR_MATURITY_STABLE\x10\x03B\xb0\x01\n" +
	"\x10com.ingestion.v1B\x0fConnectorsProtoP\x01Z:github.com/galaxy-io/filament/api/ingestion/v1;ingestionv1\xa2\x02\x03IXX\xaa\x02\fIngestion.V1\xca\x02\fIngestion\\V1\xe2\x02\x18Ingestion\\V1\\GPBMetadata\xea\x02\rIngestion::V1b\x06proto3"

var (
	file_ingestion_v1_connectors_proto_rawDescOnce sync.Once
	file_ingestion_v1_connectors_proto_rawDescData []byte
)

func file_ingestion_v1_connectors_proto_rawDescGZIP() []byte {
	file_ingestion_v1_connectors_proto_rawDescOnce.Do(func() {
		file_ingestion_v1_connectors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ingestion_v1_connectors_proto_rawDesc), len(file_ingestion_v1_connectors_proto_rawDesc)))
	})
	return file_ingestion_v1_connectors_proto_rawDescData
}

var file_ingestion_v1_connectors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ingestion_v1_connectors_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_ingestion_v1_connectors_proto_goTypes = []any{
	(ConnectorMaturity)(0),             // 0: ingestion.v1.ConnectorMaturity
	(*ConnectorSpec)(nil),              // 1: ingestion.v1.ConnectorSpec
	(*ListConnectorsRequest)(nil),      // 2: ingestion.v1.ListConnectorsRequest
	(*ListConnectorsResponse)(nil),     // 3: ingestion.v1.ListConnectorsResponse
	(*GetConnectorRequest)(nil),        // 4: ingestion.v1.GetConnectorRequest
	(*GetConnectorResponse)(nil),       // 5: ingestion.v1.GetConnectorResponse
	(*ValidateConfigRequest)(nil),      // 6: ingestion.v1.ValidateConfigRequest
	(*ValidationError)(nil),            // 7: ingestion.v1.ValidationError
	(*ValidateConfigResponse)(nil),     // 8: ingestion.v1.ValidateConfigResponse
	(*DiscoverResourcesRequest)(nil),   // 9: ingestion.v1.DiscoverResourcesRequest
	(*Resource)(nil),                   // 10: ingestion.v1.Resource
	(*DiscoverResourcesResponse)(nil),  // 11: ingestion.v1.DiscoverResourcesResponse
	(*GetResourceColumnsRequest)(nil),  // 12: ingestion.v1.GetResourceColumnsRequest
	(*ResourceColumn)(nil),             // 13: ingestion.v1.ResourceColumn
	(*ResourceColumns)(nil),            // 14: ingestion.v1.ResourceColumns
	(*GetResourceColumnsResponse)(nil), // 15: ingestion.v1.GetResourceColumnsResponse
	nil,                                // 16: ingestion.v1.Resource.MetadataEntry
	(ConnectorKind)(0),                 // 17: ingestion.v1.ConnectorKind
	(ReplicationMode)(0),               // 18: ingestion.v1.ReplicationMode
	(*ConfigSchema)(nil),               // 19: ingestion.v1.ConfigSchema
	(*PaginationRequest)(nil),          // 20: ingestion.v1.PaginationRequest
	(*SortingRequest)(nil),             // 21: ingestion.v1.SortingRequest
	(*PaginationResponse)(nil),         // 22: ingestion.v1.PaginationResponse
	(*structpb.Struct)(nil),            // 23: google.protobuf.Struct
}
var file_ingestion_v1_connectors_proto_depIdxs = []int32{
	17, // 0: ingestion.v1.ConnectorSpec.kind:type_name -> ingestion.v1.ConnectorKind
	18, // 1: ingestion.v1.ConnectorSpec.modes:type_name -> ingestion.v1.ReplicationMode
	19, // 2: ingestion.v1.ConnectorSpec.config_schema:type_name -> ingestion.v1.ConfigSchema
	0,  // 3: ingestion.v1.ConnectorSpec.maturity:type_name -> ingestion.v1.ConnectorMaturity
	17, // 4: ingestion.v1.ListConnectorsRequest.kind:type_name -> ingestion.v1.ConnectorKind
	20, // 5: ingestion.v1.ListConnectorsRequest.pagination:type_name -> ingestion.v1.PaginationRequest
	21, // 6: ingestion.v1.ListConnectorsRequest.sorting:type_name -> ingestion.v1.SortingRequest
	1,  // 7: ingestion.v1.ListConnectorsResponse.connectors:type_name -> ingestion.v1.ConnectorSpec
	22, // 8: ingestion.v1.ListConnectorsResponse.pagination:type_name -> ingestion.v1.PaginationResponse
	17, // 9: ingestion.v1.GetConnectorRequest.kind:type_name -> ingestion.v1.ConnectorKind
	1,  // 10: ingestion.v1.GetConnectorResponse.connector:type_name -> ingestion.v1.ConnectorSpec
	17, // 11: ingestion.v1.ValidateConfigRequest.kind:type_name -> ingestion.v1.ConnectorKind
	23, // 12: ingestion.v1.ValidateConfigRequest.config:type_name -> google.protobuf.Struct
	7,  // 13: ingestion.v1.ValidateConfigResponse.errors:type_name -> ingestion.v1.ValidationError
	23, // 14: ingestion.v1.DiscoverResourcesRequest.config:type_name -> google.protobuf.Struct
	16, // 15: ingestion.v1.Resource.metadata:type_name -> ingestion.v1.Resource.MetadataEntry
	10, // 16: ingestion.v1.DiscoverResourcesResponse.resources:type_name -> ingestion.v1.Resource
	23, // 17: ingestion.v1.GetResourceColumnsRequest.config:type_name -> google.protobuf.Struct
	13, // 18: ingestion.v1.ResourceColumns.columns:type_name -> ingestion.v1.ResourceColumn
	14, // 19: ingestion.v1.GetResourceColumnsResponse.resources:type_name -> ingestion.v1.ResourceColumns
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_ingestion_v1_connectors_proto_init() }
func file_ingestion_v1_connectors_proto_init() {
	if File_ingestion_v1_connectors_proto != nil {
		return
	}
	file_ingestion_v1_common_proto_init()
	file_ingestion_v1_pagination_proto_init()
	file_ingestion_v1_sorting_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ingestion_v1_connectors_proto_rawDesc), len(file_ingestion_v1_connectors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ingestion_v1_connectors_proto_goTypes,
		DependencyIndexes: file_ingestion_v1_connectors_proto_depIdxs,
		EnumInfos:         file_ingestion_v1_connectors_proto_enumTypes,
		MessageInfos:      file_ingestion_v1_connectors_proto_msgTypes,
	}.Build()
	File_ingestion_v1_connectors_proto = out.File
	file_ingestion_v1_connectors_proto_goTypes = nil
	file_ingestion_v1_connectors_proto_depIdxs = nil
}
