// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ingestion/v1/runs.proto

package ingestionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RunStatus is the persisted lifecycle state of a run.
type RunStatus int32

const (
	RunStatus_RUN_STATUS_UNSPECIFIED RunStatus = 0
	RunStatus_RUN_STATUS_REQUESTED   RunStatus = 1
	RunStatus_RUN_STATUS_RUNNING     RunStatus = 2
	RunStatus_RUN_STATUS_COMPLETED   RunStatus = 3
	RunStatus_RUN_STATUS_FAILED      RunStatus = 4
	RunStatus_RUN_STATUS_CANCELED    RunStatus = 5
	RunStatus_RUN_STATUS_PAUSED      RunStatus = 6
	RunStatus_RUN_STATUS_PARTIAL     RunStatus = 7
	RunStatus_RUN_STATUS_SCHEDULED   RunStatus = 8
)

// Enum value maps for RunStatus.
var (
	RunStatus_name = map[int32]string{
		0: "RUN_STATUS_UNSPECIFIED",
		1: "RUN_STATUS_REQUESTED",
		2: "RUN_STATUS_RUNNING",
		3: "RUN_STATUS_COMPLETED",
		4: "RUN_STATUS_FAILED",
		5: "RUN_STATUS_CANCELED",
		6: "RUN_STATUS_PAUSED",
		7: "RUN_STATUS_PARTIAL",
		8: "RUN_STATUS_SCHEDULED",
	}
	RunStatus_value = map[string]int32{
		"RUN_STATUS_UNSPECIFIED": 0,
		"RUN_STATUS_REQUESTED":   1,
		"RUN_STATUS_RUNNING":     2,
		"RUN_STATUS_COMPLETED":   3,
		"RUN_STATUS_FAILED":      4,
		"RUN_STATUS_CANCELED":    5,
		"RUN_STATUS_PAUSED":      6,
		"RUN_STATUS_PARTIAL":     7,
		"RUN_STATUS_SCHEDULED":   8,
	}
)

func (x RunStatus) Enum() *RunStatus {
	p := new(RunStatus)
	*p = x
	return p
}

func (x RunStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RunStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_ingestion_v1_runs_proto_enumTypes[0].Descriptor()
}

func (RunStatus) Type() protoreflect.EnumType {
	return &file_ingestion_v1_runs_proto_enumTypes[0]
}

func (x RunStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RunStatus.Descriptor instead.
func (RunStatus) EnumDescriptor() ([]byte, []int) {
	return file_ingestion_v1_runs_proto_rawDescGZIP(), []int{0}
}

// RunSignal is a lifecycle command sent to a run.
type RunSignal int32

const (
	RunSignal_RUN_SIGNAL_UNSPECIFIED RunSignal = 0
	RunSignal_RUN_SIGNAL_PAUSE       RunSignal = 1
	RunSignal_RUN_SIGNAL_RESUME      RunSignal = 2
	RunSignal_RUN_SIGNAL_CANCEL      RunSignal = 3
)

// Enum value maps for RunSignal.
var (
	RunSignal_name = map[int32]string{
		0: "RUN_SIGNAL_UNSPECIFIED",
		1: "RUN_SIGNAL_PAUSE",
		2: "RUN_SIGNAL_RESUME",
		3: "RUN_SIGNAL_CANCEL",
	}
	RunSignal_value = map[string]int32{
		"RUN_SIGNAL_UNSPECIFIED": 0,
		"RUN_SIGNAL_PAUSE":       1,
		"RUN_SIGNAL_RESUME":      2,
		"RUN_SIGNAL_CANCEL":      3,
	}
)

func (x RunSignal) Enum() *RunSignal {
	p := new(RunSignal)
	*p = x
	return p
}

func (x RunSignal) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RunSignal) Descriptor() protoreflect.EnumDescriptor {
	return file_ingestion_v1_runs_proto_enumTypes[1].Descriptor()
}

func (RunSignal) Type() protoreflect.EnumType {
	return &file_ingestion_v1_runs_proto_enumTypes[1]
}

func (x RunSignal) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RunSignal.Descriptor instead.
func (RunSignal) EnumDescriptor() ([]byte, []int) {
	return file_ingestion_v1_runs_proto_rawDescGZIP(), []int{1}
}

// RatePolicy throttles source reads.
type RatePolicy struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RequestsPerSecond float64                `protobuf:"fixed64,1,opt,name=requests_per_second,json=requestsPerSecond,proto3" json:"requests_per_second,omitempty"`
	Burst             int32                  `protobuf:"varint,2,opt,name=burst,proto3" json:"burst,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RatePolicy) Reset() {
	*x = RatePolicy{}
	mi := &file_ingestion_v1_runs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RatePolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatePolicy) ProtoMessage() {}

func (x *RatePolicy) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_runs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatePolicy.ProtoReflect.Descriptor instead.
func (*RatePolicy) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_runs_proto_rawDescGZIP(), []int{0}
}

func (x *RatePolicy) GetRequestsPerSecond() float64 {
	if x != nil {
		return x.RequestsPerSecond
	}
	return 0
}

func (x *RatePolicy) GetBurst() int32 {
	if x != nil {
		return x.Burst
	}
	return 0
}

// RunOptions overrides the engine's throughput defaults for a run. Every field
// is optional: a zero value defers to the engine default downstream.
type RunOptions struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	FetchSize           int32                  `protobuf:"varint,1,opt,name=fetch_size,json=fetchSize,proto3" json:"fetch_size,omitempty"`
	BatchMaxRows        int32                  `protobuf:"varint,2,opt,name=batch_max_rows,json=batchMaxRows,proto3" json:"batch_max_rows,omitempty"`
	BatchMaxBytes       int64                  `protobuf:"varint,3,opt,name=batch_max_bytes,json=batchMaxBytes,proto3" json:"batch_max_bytes,omitempty"`
	RateLimit           *RatePolicy            `protobuf:"bytes,4,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`
	SnapshotParallelism int32                  `protobuf:"varint,5,opt,name=snapshot_parallelism,json=snapshotParallelism,proto3" json:"snapshot_parallelism,omitempty"`
	CheckpointEvery     int32                  `protobuf:"varint,6,opt,name=checkpoint_every,json=checkpointEvery,proto3" json:"checkpoint_every,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RunOptions) Reset() {
	*x = RunOptions{}
	mi := &file_ingestion_v1_runs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunOptions) ProtoMessage() {}

func (x *RunOptions) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_runs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunOptions.ProtoReflect.Descriptor instead.
func (*RunOptions) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_runs_proto_rawDescGZIP(), []int{1}
}

func (x *RunOptions) GetFetchSize() int32 {
	if x != nil {
		return x.FetchSize
	}
	return 0
}

func (x *RunOptions) GetBatchMaxRows() int32 {
	if x != nil {
		return x.BatchMaxRows
	}
	return 0
}

func (x *RunOptions) GetBatchMaxBytes() int64 {
	if x != nil {
		return x.BatchMaxBytes
	}
	return 0
}

func (x *RunOptions) GetRateLimit() *RatePolicy {
	if x != nil {
		return x.RateLimit
	}
	return nil
}

func (x *RunOptions) GetSnapshotParallelism() int32 {
	if x != nil {
		return x.SnapshotParallelism
	}
	return 0
}

func (x *RunOptions) GetCheckpointEvery() int32 {
	if x != nil {
		return x.CheckpointEvery
	}
	return 0
}

type RunPipelineRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	TenantId   string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PipelineId string                 `protobuf:"bytes,2,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	// client_token salts the idempotency key so a deliberate re-run differs from a
	// double-click; reusing a token dedupes to the same runs.
	ClientToken string `protobuf:"bytes,3,opt,name=client_token,json=clientToken,proto3" json:"client_token,omitempty"`
	// options overrides engine throughput defaults for every run this call
	// produces. Unset (or any zero field) defers to defaults.
	Options *RunOptions `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	// worker_configuration overrides the pipeline's own for this call only, field
	// by field: an empty field inherits the pipeline's value. The resolved result
	// is stamped onto each run, so editing the pipeline afterwards cannot change
	// a run already requested.
	WorkerConfiguration *WorkerConfiguration `protobuf:"bytes,5,opt,name=worker_configuration,json=workerConfiguration,proto3" json:"worker_configuration,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RunPipelineRequest) Reset() {
	*x = RunPipelineRequest{}
	mi := &file_ingestion_v1_runs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunPipelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunPipelineRequest) ProtoMessage() {}

func (x *RunPipelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_runs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunPipelineRequest.ProtoReflect.Descriptor instead.
func (*RunPipelineRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_runs_proto_rawDescGZIP(), []int{2}
}

func (x *RunPipelineRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RunPipelineRequest) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *RunPipelineRequest) GetClientToken() string {
	if x != nil {
		return x.ClientToken
	}
	return ""
}

func (x *RunPipelineRequest) GetOptions() *RunOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *RunPipelineRequest) GetWorkerConfiguration() *WorkerConfiguration {
	if x != nil {
		return x.WorkerConfiguration
	}
	return nil
}

// PipelineEdgeRun ties one compiled pipeline edge to the run it produced.
type PipelineEdgeRun struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PipelineEdgeKey string                 `protobuf:"bytes,1,opt,name=pipeline_edge_key,json=pipelineEdgeKey,proto3" json:"pipeline_edge_key,omitempty"`
	Run             *RunInfo               `protobuf:"bytes,2,opt,name=run,proto3" json:"run,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PipelineEdgeRun) Reset() {
	*x = PipelineEdgeRun{}
	mi := &file_ingestion_v1_runs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineEdgeRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineEdgeRun) ProtoMessage() {}

func (x *PipelineEdgeRun) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_runs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineEdgeRun.ProtoReflect.Descriptor instead.
func (*PipelineEdgeRun) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_runs_proto_rawDescGZIP(), []int{3}
}

func (x *PipelineEdgeRun) GetPipelineEdgeKey() string {
	if x != nil {
		return x.PipelineEdgeKey
	}
	return ""
}

func (x *PipelineEdgeRun) GetRun() *RunInfo {
	if x != nil {
		return x.Run
	}
	return nil
}

type RunPipelineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeRuns      []*PipelineEdgeRun     `protobuf:"bytes,1,rep,name=edge_runs,json=edgeRuns,proto3" json:"edge_runs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunPipelineResponse) Reset() {
	*x = RunPipelineResponse{}
	mi := &file_ingestion_v1_runs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunPipelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunPipelineResponse) ProtoMessage() {}

func (x *RunPipelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_runs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunPipelineResponse.ProtoReflect.Descriptor instead.
func (*RunPipelineResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_runs_proto_rawDescGZIP(), []int{4}
}

func (x *RunPipelineResponse) GetEdgeRuns() []*PipelineEdgeRun {
	if x != nil {
		return x.EdgeRuns
	}
	return nil
}

// RunResourceState reports progress for one resource in a run.
type RunResourceState struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ResourceName     string                 `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	Status           RunStatus              `protobuf:"varint,3,opt,name=status,proto3,enum=ingestion.v1.RunStatus" json:"status,omitempty"`
	RecordsProcessed int64                  `protobuf:"varint,4,opt,name=records_processed,json=recordsProcessed,proto3" json:"records_processed,omitempty"`
	BytesProcessed   int64                  `protobuf:"varint,5,opt,name=bytes_processed,json=bytesProcessed,proto3" json:"bytes_processed,omitempty"`
	Error            string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RunResourceState) Reset() {
	*x = RunResourceState{}
	mi := &file_ingestion_v1_runs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResourceState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResourceState) ProtoMessage() {}

func (x *RunResourceState) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_runs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResourceState.ProtoReflect.Descriptor instead.
func (*RunResourceState) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_runs_proto_rawDescGZIP(), []int{5}
}

func (x *RunResourceState) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *RunResourceState) GetStatus() RunStatus {
	if x != nil {
		return x.Status
	}
	return RunStatus_RUN_STATUS_UNSPECIFIED
}

func (x *RunResourceState) GetRecordsProcessed() int64 {
	if x != nil {
		return x.RecordsProcessed
	}
	return 0
}

func (x *RunResourceState) GetBytesProcessed() int64 {
	if x != nil {
		return x.BytesProcessed
	}
	return 0
}

func (x *RunResourceState) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// RunInfo is the run-level persisted state exposed by the API.
type RunInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TenantId           string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Id                 string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	PipelineId         string                 `protobuf:"bytes,3,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	PipelineVersionId  string                 `protobuf:"bytes,4,opt,name=pipeline_version_id,json=pipelineVersionId,proto3" json:"pipeline_version_id,omitempty"`
	Status             RunStatus              `protobuf:"varint,5,opt,name=status,proto3,enum=ingestion.v1.RunStatus" json:"status,omitempty"`
	RecordsProcessed   int64                  `protobuf:"varint,6,opt,name=records_processed,json=recordsProcessed,proto3" json:"records_processed,omitempty"`
	BytesProcessed     int64                  `protobuf:"varint,7,opt,name=bytes_processed,json=bytesProcessed,proto3" json:"bytes_processed,omitempty"`
	Error              string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	StartedAt          int64                  `protobuf:"varint,9,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt            int64                  `protobuf:"varint,10,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	SourceConnectionId string                 `protobuf:"bytes,11,opt,name=source_connection_id,json=sourceConnectionId,proto3" json:"source_connection_id,omitempty"`
	SinkConnectionId   string                 `protobuf:"bytes,12,opt,name=sink_connection_id,json=sinkConnectionId,proto3" json:"sink_connection_id,omitempty"`
	// Worker pod usage folded from run.heartbeat facts.
	CpuSeconds      float64 `protobuf:"fixed64,13,opt,name=cpu_seconds,json=cpuSeconds,proto3" json:"cpu_seconds,omitempty"`
	MemoryPeakBytes int64   `protobuf:"varint,14,opt,name=memory_peak_bytes,json=memoryPeakBytes,proto3" json:"memory_peak_bytes,omitempty"`
	// Lifecycle stamps in epoch millis; 0 means unset. created_at is row birth,
	// scheduled_at the intended fire time (scheduled runs only), requested_at
	// when the run was queued for dispatch. started_at/ended_at above are the
	// worker's own start and finish.
	CreatedAt     int64 `protobuf:"varint,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ScheduledAt   int64 `protobuf:"varint,16,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	RequestedAt   int64 `protobuf:"varint,17,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	UpdatedAt     int64 `protobuf:"varint,18,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunInfo) Reset() {
	*x = RunInfo{}
	mi := &file_ingestion_v1_runs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunInfo) ProtoMessage() {}

func (x *RunInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_runs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunInfo.ProtoReflect.Descriptor instead.
func (*RunInfo) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_runs_proto_rawDescGZIP(), []int{6}
}

func (x *RunInfo) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RunInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RunInfo) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *RunInfo) GetPipelineVersionId() string {
	if x != nil {
		return x.PipelineVersionId
	}
	return ""
}

func (x *RunInfo) GetStatus() RunStatus {
	if x != nil {
		return x.Status
	}
	return RunStatus_RUN_STATUS_UNSPECIFIED
}

func (x *RunInfo) GetRecordsProcessed() int64 {
	if x != nil {
		return x.RecordsProcessed
	}
	return 0
}

func (x *RunInfo) GetBytesProcessed() int64 {
	if x != nil {
		return x.BytesProcessed
	}
	return 0
}

func (x *RunInfo) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RunInfo) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *RunInfo) GetEndedAt() int64 {
	if x != nil {
		return x.EndedAt
	}
	return 0
}

func (x *RunInfo) GetSourceConnectionId() string {
	if x != nil {
		return x.SourceConnectionId
	}
	return ""
}

func (x *RunInfo) GetSinkConnectionId() string {
	if x != nil {
		return x.SinkConnectionId
	}
	return ""
}

func (x *RunInfo) GetCpuSeconds() float64 {
	if x != nil {
		return x.CpuSeconds
	}
	return 0
}

func (x *RunInfo) GetMemoryPeakBytes() int64 {
	if x != nil {
		return x.MemoryPeakBytes
	}
	return 0
}

func (x *RunInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *RunInfo) GetScheduledAt() int64 {
	if x != nil {
		return x.ScheduledAt
	}
	return 0
}

func (x *RunInfo) GetRequestedAt() int64 {
	if x != nil {
		return x.RequestedAt
	}
	return 0
}

func (x *RunInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type RunSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Run           *RunInfo               `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	Resources     []*RunResourceState    `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
	AtSeq         uint64                 `protobuf:"varint,3,opt,name=at_seq,json=atSeq,proto3" json:"at_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunSnapshot) Reset() {
	*x = RunSnapshot{}
	mi := &file_ingestion_v1_runs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunSnapshot) ProtoMessage() {}

func (x *RunSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_runs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunSnapshot.ProtoReflect.Descriptor instead.
func (*RunSnapshot) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_runs_proto_rawDescGZIP(), []int{7}
}

func (x *RunSnapshot) GetRun() *RunInfo {
	if x != nil {
		return x.Run
	}
	return nil
}

func (x *RunSnapshot) GetResources() []*RunResourceState {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *RunSnapshot) GetAtSeq() uint64 {
	if x != nil {
		return x.AtSeq
	}
	return 0
}

type GetRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRunRequest) Reset() {
	*x = GetRunRequest{}
	mi := &file_ingestion_v1_runs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunRequest) ProtoMessage() {}

func (x *GetRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_runs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunRequest.ProtoReflect.Descriptor instead.
func (*GetRunRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_runs_proto_rawDescGZIP(), []int{8}
}

func (x *GetRunRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type GetRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *RunSnapshot           `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRunResponse) Reset() {
	*x = GetRunResponse{}
	mi := &file_ingestion_v1_runs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunResponse) ProtoMessage() {}

func (x *GetRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_runs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunResponse.ProtoReflect.Descriptor instead.
func (*GetRunResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_runs_proto_rawDescGZIP(), []int{9}
}

func (x *GetRunResponse) GetSnapshot() *RunSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type ListRunsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TenantId          string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PipelineId        string                 `protobuf:"bytes,2,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	PipelineVersionId *string                `protobuf:"bytes,3,opt,name=pipeline_version_id,json=pipelineVersionId,proto3,oneof" json:"pipeline_version_id,omitempty"`
	Status            []RunStatus            `protobuf:"varint,4,rep,packed,name=status,proto3,enum=ingestion.v1.RunStatus" json:"status,omitempty"`
	Pagination        *PaginationRequest     `protobuf:"bytes,5,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// since_ms/until_ms window on started_at (inclusive/exclusive, epoch
	// millis); 0 means unbounded. Runs that never started are excluded.
	SinceMs       int64 `protobuf:"varint,6,opt,name=since_ms,json=sinceMs,proto3" json:"since_ms,omitempty"`
	UntilMs       int64 `protobuf:"varint,7,opt,name=until_ms,json=untilMs,proto3" json:"until_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunsRequest) Reset() {
	*x = ListRunsRequest{}
	mi := &file_ingestion_v1_runs_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunsRequest) ProtoMessage() {}

func (x *ListRunsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_runs_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunsRequest.ProtoReflect.Descriptor instead.
func (*ListRunsRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_runs_proto_rawDescGZIP(), []int{10}
}

func (x *ListRunsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListRunsRequest) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *ListRunsRequest) GetPipelineVersionId() string {
	if x != nil && x.PipelineVersionId != nil {
		return *x.PipelineVersionId
	}
	return ""
}

func (x *ListRunsRequest) GetStatus() []RunStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ListRunsRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListRunsRequest) GetSinceMs() int64 {
	if x != nil {
		return x.SinceMs
	}
	return 0
}

func (x *ListRunsRequest) GetUntilMs() int64 {
	if x != nil {
		return x.UntilMs
	}
	return 0
}

type ListRunsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runs          []*RunInfo             `protobuf:"bytes,1,rep,name=runs,proto3" json:"runs,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunsResponse) Reset() {
	*x = ListRunsResponse{}
	mi := &file_ingestion_v1_runs_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunsResponse) ProtoMessage() {}

func (x *ListRunsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_runs_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunsResponse.ProtoReflect.Descriptor instead.
func (*ListRunsResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_runs_proto_rawDescGZIP(), []int{11}
}

func (x *ListRunsResponse) GetRuns() []*RunInfo {
	if x != nil {
		return x.Runs
	}
	return nil
}

func (x *ListRunsResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type SignalRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Signal        RunSignal              `protobuf:"varint,3,opt,name=signal,proto3,enum=ingestion.v1.RunSignal" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalRunRequest) Reset() {
	*x = SignalRunRequest{}
	mi := &file_ingestion_v1_runs_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalRunRequest) ProtoMessage() {}

func (x *SignalRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_runs_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalRunRequest.ProtoReflect.Descriptor instead.
func (*SignalRunRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_runs_proto_rawDescGZIP(), []int{12}
}

func (x *SignalRunRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SignalRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *SignalRunRequest) GetSignal() RunSignal {
	if x != nil {
		return x.Signal
	}
	return RunSignal_RUN_SIGNAL_UNSPECIFIED
}

type SignalRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalRunResponse) Reset() {
	*x = SignalRunResponse{}
	mi := &file_ingestion_v1_runs_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalRunResponse) ProtoMessage() {}

func (x *SignalRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_runs_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalRunResponse.ProtoReflect.Descriptor instead.
func (*SignalRunResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_runs_proto_rawDescGZIP(), []int{13}
}

type TailRunRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TenantId string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	RunId    string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// replay first emits events synthesized from the current snapshot (each marked
	// replay=true) so progress is correct on reconnect, before live facts stream.
	ShouldReplay  bool `protobuf:"varint,3,opt,name=should_replay,json=shouldReplay,proto3" json:"should_replay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TailRunRequest) Reset() {
	*x = TailRunRequest{}
	mi := &file_ingestion_v1_runs_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TailRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailRunRequest) ProtoMessage() {}

func (x *TailRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_runs_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailRunRequest.ProtoReflect.Descriptor instead.
func (*TailRunRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_runs_proto_rawDescGZIP(), []int{14}
}

func (x *TailRunRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TailRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *TailRunRequest) GetShouldReplay() bool {
	if x != nil {
		return x.ShouldReplay
	}
	return false
}

// RunEventFields contains the optional measurements carried by a run event.
type RunEventFields struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RecordsProcessed int64                  `protobuf:"varint,1,opt,name=records_processed,json=recordsProcessed,proto3" json:"records_processed,omitempty"`
	BytesProcessed   int64                  `protobuf:"varint,2,opt,name=bytes_processed,json=bytesProcessed,proto3" json:"bytes_processed,omitempty"`
	Uri              string                 `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri,omitempty"`
	Crc              uint32                 `protobuf:"varint,4,opt,name=crc,proto3" json:"crc,omitempty"`
	Error            string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RunEventFields) Reset() {
	*x = RunEventFields{}
	mi := &file_ingestion_v1_runs_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunEventFields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunEventFields) ProtoMessage() {}

func (x *RunEventFields) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_runs_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunEventFields.ProtoReflect.Descriptor instead.
func (*RunEventFields) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_runs_proto_rawDescGZIP(), []int{15}
}

func (x *RunEventFields) GetRecordsProcessed() int64 {
	if x != nil {
		return x.RecordsProcessed
	}
	return 0
}

func (x *RunEventFields) GetBytesProcessed() int64 {
	if x != nil {
		return x.BytesProcessed
	}
	return 0
}

func (x *RunEventFields) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *RunEventFields) GetCrc() uint32 {
	if x != nil {
		return x.Crc
	}
	return 0
}

func (x *RunEventFields) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// RunEvent is the event envelope forwarded by the run stream. event_type is the
// wire token (e.g. "written", "completed"). replay marks a snapshot-synthesized
// event rather than a live fact.
type RunEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	RunId         string                 `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Resource      string                 `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`
	Seq           uint64                 `protobuf:"varint,5,opt,name=seq,proto3" json:"seq,omitempty"`
	OccurredAt    int64                  `protobuf:"varint,6,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Fields        *RunEventFields        `protobuf:"bytes,7,opt,name=fields,proto3" json:"fields,omitempty"`
	IsReplay      bool                   `protobuf:"varint,8,opt,name=is_replay,json=isReplay,proto3" json:"is_replay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunEvent) Reset() {
	*x = RunEvent{}
	mi := &file_ingestion_v1_runs_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunEvent) ProtoMessage() {}

func (x *RunEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_runs_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunEvent.ProtoReflect.Descriptor instead.
func (*RunEvent) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_runs_proto_rawDescGZIP(), []int{16}
}

func (x *RunEvent) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RunEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *RunEvent) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunEvent) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *RunEvent) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *RunEvent) GetOccurredAt() int64 {
	if x != nil {
		return x.OccurredAt
	}
	return 0
}

func (x *RunEvent) GetFields() *RunEventFields {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *RunEvent) GetIsReplay() bool {
	if x != nil {
		return x.IsReplay
	}
	return false
}

type TailRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *RunEvent              `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TailRunResponse) Reset() {
	*x = TailRunResponse{}
	mi := &file_ingestion_v1_runs_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TailRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailRunResponse) ProtoMessage() {}

func (x *TailRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_runs_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailRunResponse.ProtoReflect.Descriptor instead.
func (*TailRunResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_runs_proto_rawDescGZIP(), []int{17}
}

func (x *TailRunResponse) GetEvent() *RunEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

var File_ingestion_v1_runs_proto protoreflect.FileDescriptor

const file_ingestion_v1_runs_proto_rawDesc = "" +
	"\n" +
	"\x17ingestion/v1/runs.proto\x12\fingestion.v1\x1a\x19ingestion/v1/common.proto\x1a\x1dingestion/v1/pagination.proto\"R\n" +
	"\n" +
	"RatePolicy\x12.\n" +
	"\x13requests_per_second\x18\x01 \x01(\x01R\x11requestsPerSecond\x12\x14\n" +
	"\x05burst\x18\x02 \x01(\x05R\x05burst\"\x90\x02\n" +
	"\n" +
	"RunOptions\x12\x1d\n" +
	"\n" +
	"fetch_size\x18\x01 \x01(\x05R\tfetchSize\x12$\n" +
	"\x0ebatch_max_rows\x18\x02 \x01(\x05R\fbatchMaxRows\x12&\n" +
	"\x0fbatch_max_bytes\x18\x03 \x01(\x03R\rbatchMaxBytes\x127\n" +
	"\n" +
	"rate_limit\x18\x04 \x01(\v2\x18.ingestion.v1.RatePolicyR\trateLimit\x121\n" +
	"\x14snapshot_parallelism\x18\x05 \x01(\x05R\x13snapshotParallelism\x12)\n" +
	"\x10checkpoint_every\x18\x06 \x01(\x05R\x0fcheckpointEvery\"\xff\x01\n" +
	"\x12RunPipelineRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vpipeline_id\x18\x02 \x01(\tR\n" +
	"pipelineId\x12!\n" +
	"\fclient_token\x18\x03 \x01(\tR\vclientToken\x122\n" +
	"\aoptions\x18\x04 \x01(\v2\x18.ingestion.v1.RunOptionsR\aoptions\x12T\n" +
	"\x14worker_configuration\x18\x05 \x01(\v2!.ingestion.v1.WorkerConfigurationR\x13workerConfiguration\"f\n" +
	"\x0fPipelineEdgeRun\x12*\n" +
	"\x11pipeline_edge_key\x18\x01 \x01(\tR\x0fpipelineEdgeKey\x12'\n" +
	"\x03run\x18\x02 \x01(\v2\x15.ingestion.v1.RunInfoR\x03run\"Q\n" +
	"\x13RunPipelineResponse\x12:\n" +
	"\tedge_runs\x18\x01 \x03(\v2\x1d.ingestion.v1.PipelineEdgeRunR\bedgeRuns\"\xe3\x01\n" +
	"\x10RunResourceState\x12#\n" +
	"\rresource_name\x18\x01 \x01(\tR\fresourceName\x12/\n" +
	"\x06status\x18\x03 \x01(\x0e2\x17.ingestion.v1.RunStatusR\x06status\x12+\n" +
	"\x11records_processed\x18\x04 \x01(\x03R\x10recordsProcessed\x12'\n" +
	"\x0fbytes_processed\x18\x05 \x01(\x03R\x0ebytesProcessed\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05errorJ\x04\b\x02\x10\x03R\aenabled\"\x8f\x05\n" +
	"\aRunInfo\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1f\n" +
	"\vpipeline_id\x18\x03 \x01(\tR\n" +
	"pipelineId\x12.\n" +
	"\x13pipeline_version_id\x18\x04 \x01(\tR\x11pipelineVersionId\x12/\n" +
	"\x06status\x18\x05 \x01(\x0e2\x17.ingestion.v1.RunStatusR\x06status\x12+\n" +
	"\x11records_processed\x18\x06 \x01(\x03R\x10recordsProcessed\x12'\n" +
	"\x0fbytes_processed\x18\a \x01(\x03R\x0ebytesProcessed\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"started_at\x18\t \x01(\x03R\tstartedAt\x12\x19\n" +
	"\bended_at\x18\n" +
	" \x01(\x03R\aendedAt\x120\n" +
	"\x14source_connection_id\x18\v \x01(\tR\x12sourceConnectionId\x12,\n" +
	"\x12sink_connection_id\x18\f \x01(\tR\x10sinkConnectionId\x12\x1f\n" +
	"\vcpu_seconds\x18\r \x01(\x01R\n" +
	"cpuSeconds\x12*\n" +
	"\x11memory_peak_bytes\x18\x0e \x01(\x03R\x0fmemoryPeakBytes\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0f \x01(\x03R\tcreatedAt\x12!\n" +
	"\fscheduled_at\x18\x10 \x01(\x03R\vscheduledAt\x12!\n" +
	"\frequested_at\x18\x11 \x01(\x03R\vrequestedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x12 \x01(\x03R\tupdatedAt\"\x8b\x01\n" +
	"\vRunSnapshot\x12'\n" +
	"\x03run\x18\x01 \x01(\v2\x15.ingestion.v1.RunInfoR\x03run\x12<\n" +
	"\tresources\x18\x02 \x03(\v2\x1e.ingestion.v1.RunResourceStateR\tresources\x12\x15\n" +
	"\x06at_seq\x18\x03 \x01(\x04R\x05atSeq\"C\n" +
	"\rGetRunRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\"G\n" +
	"\x0eGetRunResponse\x125\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x19.ingestion.v1.RunSnapshotR\bsnapshot\"\xc4\x02\n" +
	"\x0fListRunsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vpipeline_id\x18\x02 \x01(\tR\n" +
	"pipelineId\x123\n" +
	"\x13pipeline_version_id\x18\x03 \x01(\tH\x00R\x11pipelineVersionId\x88\x01\x01\x12/\n" +
	"\x06status\x18\x04 \x03(\x0e2\x17.ingestion.v1.RunStatusR\x06status\x12?\n" +
	"\n" +
	"pagination\x18\x05 \x01(\v2\x1f.ingestion.v1.PaginationRequestR\n" +
	"pagination\x12\x19\n" +
	"\bsince_ms\x18\x06 \x01(\x03R\asinceMs\x12\x19\n" +
	"\buntil_ms\x18\a \x01(\x03R\auntilMsB\x16\n" +
	"\x14_pipeline_version_id\"\x7f\n" +
	"\x10ListRunsResponse\x12)\n" +
	"\x04runs\x18\x01 \x03(\v2\x15.ingestion.v1.RunInfoR\x04runs\x12@\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2 .ingestion.v1.PaginationResponseR\n" +
	"pagination\"w\n" +
	"\x10SignalRunRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12/\n" +
	"\x06signal\x18\x03 \x01(\x0e2\x17.ingestion.v1.RunSignalR\x06signal\"\x13\n" +
	"\x11SignalRunResponse\"i\n" +
	"\x0eTailRunRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12#\n" +
	"\rshould_replay\x18\x03 \x01(\bR\fshouldReplay\"\xa0\x01\n" +
	"\x0eRunEventFields\x12+\n" +
	"\x11records_processed\x18\x01 \x01(\x03R\x10recordsProcessed\x12'\n" +
	"\x0fbytes_processed\x18\x02 \x01(\x03R\x0ebytesProcessed\x12\x10\n" +
	"\x03uri\x18\x03 \x01(\tR\x03uri\x12\x10\n" +
	"\x03crc\x18\x04 \x01(\rR\x03crc\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"\xff\x01\n" +
	"\bRunEvent\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\x12\x1a\n" +
	"\bresource\x18\x04 \x01(\tR\bresource\x12\x10\n" +
	"\x03seq\x18\x05 \x01(\x04R\x03seq\x12\x1f\n" +
	"\voccurred_at\x18\x06 \x01(\x03R\n" +
	"occurredAt\x124\n" +
	"\x06fields\x18\a \x01(\v2\x1c.ingestion.v1.RunEventFieldsR\x06fields\x12\x1b\n" +
	"\tis_replay\x18\b \x01(\bR\bisReplay\"?\n" +
	"\x0fTailRunResponse\x12,\n" +
	"\x05event\x18\x01 \x01(\v2\x16.ingestion.v1.RunEventR\x05event*\xec\x01\n" +
	"\tRunStatus\x12\x1a\n" +
	"\x16RUN_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14RUN_STATUS_REQUESTED\x10\x01\x12\x16\n" +
	"\x12RUN_STATUS_RUNNING\x10\x02\x12\x18\n" +
	"\x14RUN_STATUS_COMPLETED\x10\x03\x12\x15\n" +
	"\x11RUN_STATUS_FAILED\x10\x04\x12\x17\n" +
	"\x13RUN_STATUS_CANCELED\x10\x05\x12\x15\n" +
	"\x11RUN_STATUS_PAUSED\x10\x06\x12\x16\n" +
	"\x12RUN_STATUS_PARTIAL\x10\a\x12\x18\n" +
	"\x14RUN_STATUS_SCHEDULED\x10\b*k\n" +
	"\tRunSignal\x12\x1a\n" +
	"\x16RUN_SIGNAL_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10RUN_SIGNAL_PAUSE\x10\x01\x12\x15\n" +
	"\x11RUN_SIGNAL_RESUME\x10\x02\x12\x15\n" +
	"\x11RUN_SIGNAL_CANCEL\x10\x03B\xaa\x01\n" +
	"\x10com.ingestion.v1B\tRunsProtoP\x01Z:github.com/galaxy-io/filament/api/ingestion/v1;ingestionv1\xa2\x02\x03IXX\xaa\x02\fIngestion.V1\xca\x02\fIngestion\\V1\xe2\x02\x18Ingestion\\V1\\GPBMetadata\xea\x02\rIngestion::V1b\x06proto3"

var (
	file_ingestion_v1_runs_proto_rawDescOnce sync.Once
	file_ingestion_v1_runs_proto_rawDescData []byte
)

func file_ingestion_v1_runs_proto_rawDescGZIP() []byte {
	file_ingestion_v1_runs_proto_rawDescOnce.Do(func() {
		file_ingestion_v1_runs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ingestion_v1_runs_proto_rawDesc), len(file_ingestion_v1_runs_proto_rawDesc)))
	})
	return file_ingestion_v1_runs_proto_rawDescData
}

var file_ingestion_v1_runs_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ingestion_v1_runs_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_ingestion_v1_runs_proto_goTypes = []any{
	(RunStatus)(0),              // 0: ingestion.v1.RunStatus
	(RunSignal)(0),              // 1: ingestion.v1.RunSignal
	(*RatePolicy)(nil),          // 2: ingestion.v1.RatePolicy
	(*RunOptions)(nil),          // 3: ingestion.v1.RunOptions
	(*RunPipelineRequest)(nil),  // 4: ingestion.v1.RunPipelineRequest
	(*PipelineEdgeRun)(nil),     // 5: ingestion.v1.PipelineEdgeRun
	(*RunPipelineResponse)(nil), // 6: ingestion.v1.RunPipelineResponse
	(*RunResourceState)(nil),    // 7: ingestion.v1.RunResourceState
	(*RunInfo)(nil),             // 8: ingestion.v1.RunInfo
	(*RunSnapshot)(nil),         // 9: ingestion.v1.RunSnapshot
	(*GetRunRequest)(nil),       // 10: ingestion.v1.GetRunRequest
	(*GetRunResponse)(nil),      // 11: ingestion.v1.GetRunResponse
	(*ListRunsRequest)(nil),     // 12: ingestion.v1.ListRunsRequest
	(*ListRunsResponse)(nil),    // 13: ingestion.v1.ListRunsResponse
	(*SignalRunRequest)(nil),    // 14: ingestion.v1.SignalRunRequest
	(*SignalRunResponse)(nil),   // 15: ingestion.v1.SignalRunResponse
	(*TailRunRequest)(nil),      // 16: ingestion.v1.TailRunRequest
	(*RunEventFields)(nil),      // 17: ingestion.v1.RunEventFields
	(*RunEvent)(nil),            // 18: ingestion.v1.RunEvent
	(*TailRunResponse)(nil),     // 19: ingestion.v1.TailRunResponse
	(*WorkerConfiguration)(nil), // 20: ingestion.v1.WorkerConfiguration
	(*PaginationRequest)(nil),   // 21: ingestion.v1.PaginationRequest
	(*PaginationResponse)(nil),  // 22: ingestion.v1.PaginationResponse
}
var file_ingestion_v1_runs_proto_depIdxs = []int32{
	2,  // 0: ingestion.v1.RunOptions.rate_limit:type_name -> ingestion.v1.RatePolicy
	3,  // 1: ingestion.v1.RunPipelineRequest.options:type_name -> ingestion.v1.RunOptions
	20, // 2: ingestion.v1.RunPipelineRequest.worker_configuration:type_name -> ingestion.v1.WorkerConfiguration
	8,  // 3: ingestion.v1.PipelineEdgeRun.run:type_name -> ingestion.v1.RunInfo
	5,  // 4: ingestion.v1.RunPipelineResponse.edge_runs:type_name -> ingestion.v1.PipelineEdgeRun
	0,  // 5: ingestion.v1.RunResourceState.status:type_name -> ingestion.v1.RunStatus
	0,  // 6: ingestion.v1.RunInfo.status:type_name -> ingestion.v1.RunStatus
	8,  // 7: ingestion.v1.RunSnapshot.run:type_name -> ingestion.v1.RunInfo
	7,  // 8: ingestion.v1.RunSnapshot.resources:type_name -> ingestion.v1.RunResourceState
	9,  // 9: ingestion.v1.GetRunResponse.snapshot:type_name -> ingestion.v1.RunSnapshot
	0,  // 10: ingestion.v1.ListRunsRequest.status:type_name -> ingestion.v1.RunStatus
	21, // 11: ingestion.v1.ListRunsRequest.pagination:type_name -> ingestion.v1.PaginationRequest
	8,  // 12: ingestion.v1.ListRunsResponse.runs:type_name -> ingestion.v1.RunInfo
	22, // 13: ingestion.v1.ListRunsResponse.pagination:type_name -> ingestion.v1.PaginationResponse
	1,  // 14: ingestion.v1.SignalRunRequest.signal:type_name -> ingestion.v1.RunSignal
	17, // 15: ingestion.v1.RunEvent.fields:type_name -> ingestion.v1.RunEventFields
	18, // 16: ingestion.v1.TailRunResponse.event:type_name -> ingestion.v1.RunEvent
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_ingestion_v1_runs_proto_init() }
func file_ingestion_v1_runs_proto_init() {
	if File_ingestion_v1_runs_proto != nil {
		return
	}
	file_ingestion_v1_common_proto_init()
	file_ingestion_v1_pagination_proto_init()
	file_ingestion_v1_runs_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ingestion_v1_runs_proto_rawDesc), len(file_ingestion_v1_runs_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ingestion_v1_runs_proto_goTypes,
		DependencyIndexes: file_ingestion_v1_runs_proto_depIdxs,
		EnumInfos:         file_ingestion_v1_runs_proto_enumTypes,
		MessageInfos:      file_ingestion_v1_runs_proto_msgTypes,
	}.Build()
	File_ingestion_v1_runs_proto = out.File
	file_ingestion_v1_runs_proto_goTypes = nil
	file_ingestion_v1_runs_proto_depIdxs = nil
}
