// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ingestion/v1/service.proto

package ingestionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_ingestion_v1_service_proto protoreflect.FileDescriptor

const file_ingestion_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1aingestion/v1/service.proto\x12\fingestion.v1\x1a\x1eingestion/v1/connections.proto\x1a\x1cingestion/v1/pipelines.proto\x1a\x1cingestion/v1/providers.proto\x1a\x17ingestion/v1/runs.proto\x1a\x1aingestion/v1/secrets.proto2\x8b\x15\n" +
	"\x10IngestionService\x12[\n" +
	"\x0eListConnectors\x12#.ingestion.v1.ListConnectorsRequest\x1a$.ingestion.v1.ListConnectorsResponse\x12[\n" +
	"\x0eValidateConfig\x12#.ingestion.v1.ValidateConfigRequest\x1a$.ingestion.v1.ValidateConfigResponse\x12d\n" +
	"\x11DiscoverResources\x12&.ingestion.v1.DiscoverResourcesRequest\x1a'.ingestion.v1.DiscoverResourcesResponse\x12L\n" +
	"\tPutSecret\x12\x1e.ingestion.v1.PutSecretRequest\x1a\x1f.ingestion.v1.PutSecretResponse\x12U\n" +
	"\fDeleteSecret\x12!.ingestion.v1.DeleteSecretRequest\x1a\".ingestion.v1.DeleteSecretResponse\x12a\n" +
	"\x10CreateConnection\x12%.ingestion.v1.CreateConnectionRequest\x1a&.ingestion.v1.CreateConnectionResponse\x12a\n" +
	"\x10UpdateConnection\x12%.ingestion.v1.UpdateConnectionRequest\x1a&.ingestion.v1.UpdateConnectionResponse\x12X\n" +
	"\rGetConnection\x12\".ingestion.v1.GetConnectionRequest\x1a#.ingestion.v1.GetConnectionResponse\x12^\n" +
	"\x0fListConnections\x12$.ingestion.v1.ListConnectionsRequest\x1a%.ingestion.v1.ListConnectionsResponse\x12a\n" +
	"\x10DeleteConnection\x12%.ingestion.v1.DeleteConnectionRequest\x1a&.ingestion.v1.DeleteConnectionResponse\x12[\n" +
	"\x0eCreatePipeline\x12#.ingestion.v1.CreatePipelineRequest\x1a$.ingestion.v1.CreatePipelineResponse\x12p\n" +
	"\x15CreatePipelineVersion\x12*.ingestion.v1.CreatePipelineVersionRequest\x1a+.ingestion.v1.CreatePipelineVersionResponse\x12[\n" +
	"\x0eUpdatePipeline\x12#.ingestion.v1.UpdatePipelineRequest\x1a$.ingestion.v1.UpdatePipelineResponse\x12R\n" +
	"\vGetPipeline\x12 .ingestion.v1.GetPipelineRequest\x1a!.ingestion.v1.GetPipelineResponse\x12g\n" +
	"\x12GetPipelineVersion\x12'.ingestion.v1.GetPipelineVersionRequest\x1a(.ingestion.v1.GetPipelineVersionResponse\x12m\n" +
	"\x14ListPipelineVersions\x12).ingestion.v1.ListPipelineVersionsRequest\x1a*.ingestion.v1.ListPipelineVersionsResponse\x12X\n" +
	"\rListPipelines\x12\".ingestion.v1.ListPipelinesRequest\x1a#.ingestion.v1.ListPipelinesResponse\x12[\n" +
	"\x0eDeletePipeline\x12#.ingestion.v1.DeletePipelineRequest\x1a$.ingestion.v1.DeletePipelineResponse\x12s\n" +
	"\x16CreatePipelineSchedule\x12+.ingestion.v1.CreatePipelineScheduleRequest\x1a,.ingestion.v1.CreatePipelineScheduleResponse\x12s\n" +
	"\x16UpdatePipelineSchedule\x12+.ingestion.v1.UpdatePipelineScheduleRequest\x1a,.ingestion.v1.UpdatePipelineScheduleResponse\x12s\n" +
	"\x16DeletePipelineSchedule\x12+.ingestion.v1.DeletePipelineScheduleRequest\x1a,.ingestion.v1.DeletePipelineScheduleResponse\x12p\n" +
	"\x15PausePipelineSchedule\x12*.ingestion.v1.PausePipelineScheduleRequest\x1a+.ingestion.v1.PausePipelineScheduleResponse\x12s\n" +
	"\x16ResumePipelineSchedule\x12+.ingestion.v1.ResumePipelineScheduleRequest\x1a,.ingestion.v1.ResumePipelineScheduleResponse\x12R\n" +
	"\vRunPipeline\x12 .ingestion.v1.RunPipelineRequest\x1a!.ingestion.v1.RunPipelineResponse\x12I\n" +
	"\bListRuns\x12\x1d.ingestion.v1.ListRunsRequest\x1a\x1e.ingestion.v1.ListRunsResponse\x12C\n" +
	"\x06GetRun\x12\x1b.ingestion.v1.GetRunRequest\x1a\x1c.ingestion.v1.GetRunResponse\x12L\n" +
	"\tSignalRun\x12\x1e.ingestion.v1.SignalRunRequest\x1a\x1f.ingestion.v1.SignalRunResponse\x12H\n" +
	"\aTailRun\x12\x1c.ingestion.v1.TailRunRequest\x1a\x1d.ingestion.v1.TailRunResponse0\x01B\xad\x01\n" +
	"\x10com.ingestion.v1B\fServiceProtoP\x01Z:github.com/galaxy-io/filament/api/ingestion/v1;ingestionv1\xa2\x02\x03IXX\xaa\x02\fIngestion.V1\xca\x02\fIngestion\\V1\xe2\x02\x18Ingestion\\V1\\GPBMetadata\xea\x02\rIngestion::V1b\x06proto3"

var file_ingestion_v1_service_proto_goTypes = []any{
	(*ListConnectorsRequest)(nil),          // 0: ingestion.v1.ListConnectorsRequest
	(*ValidateConfigRequest)(nil),          // 1: ingestion.v1.ValidateConfigRequest
	(*DiscoverResourcesRequest)(nil),       // 2: ingestion.v1.DiscoverResourcesRequest
	(*PutSecretRequest)(nil),               // 3: ingestion.v1.PutSecretRequest
	(*DeleteSecretRequest)(nil),            // 4: ingestion.v1.DeleteSecretRequest
	(*CreateConnectionRequest)(nil),        // 5: ingestion.v1.CreateConnectionRequest
	(*UpdateConnectionRequest)(nil),        // 6: ingestion.v1.UpdateConnectionRequest
	(*GetConnectionRequest)(nil),           // 7: ingestion.v1.GetConnectionRequest
	(*ListConnectionsRequest)(nil),         // 8: ingestion.v1.ListConnectionsRequest
	(*DeleteConnectionRequest)(nil),        // 9: ingestion.v1.DeleteConnectionRequest
	(*CreatePipelineRequest)(nil),          // 10: ingestion.v1.CreatePipelineRequest
	(*CreatePipelineVersionRequest)(nil),   // 11: ingestion.v1.CreatePipelineVersionRequest
	(*UpdatePipelineRequest)(nil),          // 12: ingestion.v1.UpdatePipelineRequest
	(*GetPipelineRequest)(nil),             // 13: ingestion.v1.GetPipelineRequest
	(*GetPipelineVersionRequest)(nil),      // 14: ingestion.v1.GetPipelineVersionRequest
	(*ListPipelineVersionsRequest)(nil),    // 15: ingestion.v1.ListPipelineVersionsRequest
	(*ListPipelinesRequest)(nil),           // 16: ingestion.v1.ListPipelinesRequest
	(*DeletePipelineRequest)(nil),          // 17: ingestion.v1.DeletePipelineRequest
	(*CreatePipelineScheduleRequest)(nil),  // 18: ingestion.v1.CreatePipelineScheduleRequest
	(*UpdatePipelineScheduleRequest)(nil),  // 19: ingestion.v1.UpdatePipelineScheduleRequest
	(*DeletePipelineScheduleRequest)(nil),  // 20: ingestion.v1.DeletePipelineScheduleRequest
	(*PausePipelineScheduleRequest)(nil),   // 21: ingestion.v1.PausePipelineScheduleRequest
	(*ResumePipelineScheduleRequest)(nil),  // 22: ingestion.v1.ResumePipelineScheduleRequest
	(*RunPipelineRequest)(nil),             // 23: ingestion.v1.RunPipelineRequest
	(*ListRunsRequest)(nil),                // 24: ingestion.v1.ListRunsRequest
	(*GetRunRequest)(nil),                  // 25: ingestion.v1.GetRunRequest
	(*SignalRunRequest)(nil),               // 26: ingestion.v1.SignalRunRequest
	(*TailRunRequest)(nil),                 // 27: ingestion.v1.TailRunRequest
	(*ListConnectorsResponse)(nil),         // 28: ingestion.v1.ListConnectorsResponse
	(*ValidateConfigResponse)(nil),         // 29: ingestion.v1.ValidateConfigResponse
	(*DiscoverResourcesResponse)(nil),      // 30: ingestion.v1.DiscoverResourcesResponse
	(*PutSecretResponse)(nil),              // 31: ingestion.v1.PutSecretResponse
	(*DeleteSecretResponse)(nil),           // 32: ingestion.v1.DeleteSecretResponse
	(*CreateConnectionResponse)(nil),       // 33: ingestion.v1.CreateConnectionResponse
	(*UpdateConnectionResponse)(nil),       // 34: ingestion.v1.UpdateConnectionResponse
	(*GetConnectionResponse)(nil),          // 35: ingestion.v1.GetConnectionResponse
	(*ListConnectionsResponse)(nil),        // 36: ingestion.v1.ListConnectionsResponse
	(*DeleteConnectionResponse)(nil),       // 37: ingestion.v1.DeleteConnectionResponse
	(*CreatePipelineResponse)(nil),         // 38: ingestion.v1.CreatePipelineResponse
	(*CreatePipelineVersionResponse)(nil),  // 39: ingestion.v1.CreatePipelineVersionResponse
	(*UpdatePipelineResponse)(nil),         // 40: ingestion.v1.UpdatePipelineResponse
	(*GetPipelineResponse)(nil),            // 41: ingestion.v1.GetPipelineResponse
	(*GetPipelineVersionResponse)(nil),     // 42: ingestion.v1.GetPipelineVersionResponse
	(*ListPipelineVersionsResponse)(nil),   // 43: ingestion.v1.ListPipelineVersionsResponse
	(*ListPipelinesResponse)(nil),          // 44: ingestion.v1.ListPipelinesResponse
	(*DeletePipelineResponse)(nil),         // 45: ingestion.v1.DeletePipelineResponse
	(*CreatePipelineScheduleResponse)(nil), // 46: ingestion.v1.CreatePipelineScheduleResponse
	(*UpdatePipelineScheduleResponse)(nil), // 47: ingestion.v1.UpdatePipelineScheduleResponse
	(*DeletePipelineScheduleResponse)(nil), // 48: ingestion.v1.DeletePipelineScheduleResponse
	(*PausePipelineScheduleResponse)(nil),  // 49: ingestion.v1.PausePipelineScheduleResponse
	(*ResumePipelineScheduleResponse)(nil), // 50: ingestion.v1.ResumePipelineScheduleResponse
	(*RunPipelineResponse)(nil),            // 51: ingestion.v1.RunPipelineResponse
	(*ListRunsResponse)(nil),               // 52: ingestion.v1.ListRunsResponse
	(*GetRunResponse)(nil),                 // 53: ingestion.v1.GetRunResponse
	(*SignalRunResponse)(nil),              // 54: ingestion.v1.SignalRunResponse
	(*TailRunResponse)(nil),                // 55: ingestion.v1.TailRunResponse
}
var file_ingestion_v1_service_proto_depIdxs = []int32{
	0,  // 0: ingestion.v1.IngestionService.ListConnectors:input_type -> ingestion.v1.ListConnectorsRequest
	1,  // 1: ingestion.v1.IngestionService.ValidateConfig:input_type -> ingestion.v1.ValidateConfigRequest
	2,  // 2: ingestion.v1.IngestionService.DiscoverResources:input_type -> ingestion.v1.DiscoverResourcesRequest
	3,  // 3: ingestion.v1.IngestionService.PutSecret:input_type -> ingestion.v1.PutSecretRequest
	4,  // 4: ingestion.v1.IngestionService.DeleteSecret:input_type -> ingestion.v1.DeleteSecretRequest
	5,  // 5: ingestion.v1.IngestionService.CreateConnection:input_type -> ingestion.v1.CreateConnectionRequest
	6,  // 6: ingestion.v1.IngestionService.UpdateConnection:input_type -> ingestion.v1.UpdateConnectionRequest
	7,  // 7: ingestion.v1.IngestionService.GetConnection:input_type -> ingestion.v1.GetConnectionRequest
	8,  // 8: ingestion.v1.IngestionService.ListConnections:input_type -> ingestion.v1.ListConnectionsRequest
	9,  // 9: ingestion.v1.IngestionService.DeleteConnection:input_type -> ingestion.v1.DeleteConnectionRequest
	10, // 10: ingestion.v1.IngestionService.CreatePipeline:input_type -> ingestion.v1.CreatePipelineRequest
	11, // 11: ingestion.v1.IngestionService.CreatePipelineVersion:input_type -> ingestion.v1.CreatePipelineVersionRequest
	12, // 12: ingestion.v1.IngestionService.UpdatePipeline:input_type -> ingestion.v1.UpdatePipelineRequest
	13, // 13: ingestion.v1.IngestionService.GetPipeline:input_type -> ingestion.v1.GetPipelineRequest
	14, // 14: ingestion.v1.IngestionService.GetPipelineVersion:input_type -> ingestion.v1.GetPipelineVersionRequest
	15, // 15: ingestion.v1.IngestionService.ListPipelineVersions:input_type -> ingestion.v1.ListPipelineVersionsRequest
	16, // 16: ingestion.v1.IngestionService.ListPipelines:input_type -> ingestion.v1.ListPipelinesRequest
	17, // 17: ingestion.v1.IngestionService.DeletePipeline:input_type -> ingestion.v1.DeletePipelineRequest
	18, // 18: ingestion.v1.IngestionService.CreatePipelineSchedule:input_type -> ingestion.v1.CreatePipelineScheduleRequest
	19, // 19: ingestion.v1.IngestionService.UpdatePipelineSchedule:input_type -> ingestion.v1.UpdatePipelineScheduleRequest
	20, // 20: ingestion.v1.IngestionService.DeletePipelineSchedule:input_type -> ingestion.v1.DeletePipelineScheduleRequest
	21, // 21: ingestion.v1.IngestionService.PausePipelineSchedule:input_type -> ingestion.v1.PausePipelineScheduleRequest
	22, // 22: ingestion.v1.IngestionService.ResumePipelineSchedule:input_type -> ingestion.v1.ResumePipelineScheduleRequest
	23, // 23: ingestion.v1.IngestionService.RunPipeline:input_type -> ingestion.v1.RunPipelineRequest
	24, // 24: ingestion.v1.IngestionService.ListRuns:input_type -> ingestion.v1.ListRunsRequest
	25, // 25: ingestion.v1.IngestionService.GetRun:input_type -> ingestion.v1.GetRunRequest
	26, // 26: ingestion.v1.IngestionService.SignalRun:input_type -> ingestion.v1.SignalRunRequest
	27, // 27: ingestion.v1.IngestionService.TailRun:input_type -> ingestion.v1.TailRunRequest
	28, // 28: ingestion.v1.IngestionService.ListConnectors:output_type -> ingestion.v1.ListConnectorsResponse
	29, // 29: ingestion.v1.IngestionService.ValidateConfig:output_type -> ingestion.v1.ValidateConfigResponse
	30, // 30: ingestion.v1.IngestionService.DiscoverResources:output_type -> ingestion.v1.DiscoverResourcesResponse
	31, // 31: ingestion.v1.IngestionService.PutSecret:output_type -> ingestion.v1.PutSecretResponse
	32, // 32: ingestion.v1.IngestionService.DeleteSecret:output_type -> ingestion.v1.DeleteSecretResponse
	33, // 33: ingestion.v1.IngestionService.CreateConnection:output_type -> ingestion.v1.CreateConnectionResponse
	34, // 34: ingestion.v1.IngestionService.UpdateConnection:output_type -> ingestion.v1.UpdateConnectionResponse
	35, // 35: ingestion.v1.IngestionService.GetConnection:output_type -> ingestion.v1.GetConnectionResponse
	36, // 36: ingestion.v1.IngestionService.ListConnections:output_type -> ingestion.v1.ListConnectionsResponse
	37, // 37: ingestion.v1.IngestionService.DeleteConnection:output_type -> ingestion.v1.DeleteConnectionResponse
	38, // 38: ingestion.v1.IngestionService.CreatePipeline:output_type -> ingestion.v1.CreatePipelineResponse
	39, // 39: ingestion.v1.IngestionService.CreatePipelineVersion:output_type -> ingestion.v1.CreatePipelineVersionResponse
	40, // 40: ingestion.v1.IngestionService.UpdatePipeline:output_type -> ingestion.v1.UpdatePipelineResponse
	41, // 41: ingestion.v1.IngestionService.GetPipeline:output_type -> ingestion.v1.GetPipelineResponse
	42, // 42: ingestion.v1.IngestionService.GetPipelineVersion:output_type -> ingestion.v1.GetPipelineVersionResponse
	43, // 43: ingestion.v1.IngestionService.ListPipelineVersions:output_type -> ingestion.v1.ListPipelineVersionsResponse
	44, // 44: ingestion.v1.IngestionService.ListPipelines:output_type -> ingestion.v1.ListPipelinesResponse
	45, // 45: ingestion.v1.IngestionService.DeletePipeline:output_type -> ingestion.v1.DeletePipelineResponse
	46, // 46: ingestion.v1.IngestionService.CreatePipelineSchedule:output_type -> ingestion.v1.CreatePipelineScheduleResponse
	47, // 47: ingestion.v1.IngestionService.UpdatePipelineSchedule:output_type -> ingestion.v1.UpdatePipelineScheduleResponse
	48, // 48: ingestion.v1.IngestionService.DeletePipelineSchedule:output_type -> ingestion.v1.DeletePipelineScheduleResponse
	49, // 49: ingestion.v1.IngestionService.PausePipelineSchedule:output_type -> ingestion.v1.PausePipelineScheduleResponse
	50, // 50: ingestion.v1.IngestionService.ResumePipelineSchedule:output_type -> ingestion.v1.ResumePipelineScheduleResponse
	51, // 51: ingestion.v1.IngestionService.RunPipeline:output_type -> ingestion.v1.RunPipelineResponse
	52, // 52: ingestion.v1.IngestionService.ListRuns:output_type -> ingestion.v1.ListRunsResponse
	53, // 53: ingestion.v1.IngestionService.GetRun:output_type -> ingestion.v1.GetRunResponse
	54, // 54: ingestion.v1.IngestionService.SignalRun:output_type -> ingestion.v1.SignalRunResponse
	55, // 55: ingestion.v1.IngestionService.TailRun:output_type -> ingestion.v1.TailRunResponse
	28, // [28:56] is the sub-list for method output_type
	0,  // [0:28] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_ingestion_v1_service_proto_init() }
func file_ingestion_v1_service_proto_init() {
	if File_ingestion_v1_service_proto != nil {
		return
	}
	file_ingestion_v1_connections_proto_init()
	file_ingestion_v1_pipelines_proto_init()
	file_ingestion_v1_providers_proto_init()
	file_ingestion_v1_runs_proto_init()
	file_ingestion_v1_secrets_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ingestion_v1_service_proto_rawDesc), len(file_ingestion_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ingestion_v1_service_proto_goTypes,
		DependencyIndexes: file_ingestion_v1_service_proto_depIdxs,
	}.Build()
	File_ingestion_v1_service_proto = out.File
	file_ingestion_v1_service_proto_goTypes = nil
	file_ingestion_v1_service_proto_depIdxs = nil
}
