// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ingestion/v1/transformations.proto

package ingestionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ListTransformFunctionsRequest asks for the transform catalog. With a
// logical_type only the functions that accept a column of that type are
// returned, so a builder can offer exactly what applies to the column at hand.
type ListTransformFunctionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogicalType   string                 `protobuf:"bytes,1,opt,name=logical_type,json=logicalType,proto3" json:"logical_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransformFunctionsRequest) Reset() {
	*x = ListTransformFunctionsRequest{}
	mi := &file_ingestion_v1_transformations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransformFunctionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransformFunctionsRequest) ProtoMessage() {}

func (x *ListTransformFunctionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_transformations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransformFunctionsRequest.ProtoReflect.Descriptor instead.
func (*ListTransformFunctionsRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_transformations_proto_rawDescGZIP(), []int{0}
}

func (x *ListTransformFunctionsRequest) GetLogicalType() string {
	if x != nil {
		return x.LogicalType
	}
	return ""
}

// TransformArgument is one positional argument of a catalog function. An empty
// logical_types accepts any type.
type TransformArgument struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Name         string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	LogicalTypes []string               `protobuf:"bytes,2,rep,name=logical_types,json=logicalTypes,proto3" json:"logical_types,omitempty"`
	IsColumn     bool                   `protobuf:"varint,3,opt,name=is_column,json=isColumn,proto3" json:"is_column,omitempty"`
	IsLiteral    bool                   `protobuf:"varint,4,opt,name=is_literal,json=isLiteral,proto3" json:"is_literal,omitempty"`
	IsOptional   bool                   `protobuf:"varint,5,opt,name=is_optional,json=isOptional,proto3" json:"is_optional,omitempty"`
	// is_variadic on the last argument lets a call repeat it any number of times.
	IsVariadic    bool `protobuf:"varint,6,opt,name=is_variadic,json=isVariadic,proto3" json:"is_variadic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformArgument) Reset() {
	*x = TransformArgument{}
	mi := &file_ingestion_v1_transformations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformArgument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformArgument) ProtoMessage() {}

func (x *TransformArgument) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_transformations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformArgument.ProtoReflect.Descriptor instead.
func (*TransformArgument) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_transformations_proto_rawDescGZIP(), []int{1}
}

func (x *TransformArgument) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TransformArgument) GetLogicalTypes() []string {
	if x != nil {
		return x.LogicalTypes
	}
	return nil
}

func (x *TransformArgument) GetIsColumn() bool {
	if x != nil {
		return x.IsColumn
	}
	return false
}

func (x *TransformArgument) GetIsLiteral() bool {
	if x != nil {
		return x.IsLiteral
	}
	return false
}

func (x *TransformArgument) GetIsOptional() bool {
	if x != nil {
		return x.IsOptional
	}
	return false
}

func (x *TransformArgument) GetIsVariadic() bool {
	if x != nil {
		return x.IsVariadic
	}
	return false
}

// TransformFunction is one catalog entry. name is what a definition calls;
// display_name is what a builder shows for it. operator_symbol is optional
// presentation metadata for a binary function that can use compact infix UI.
type TransformFunction struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Args           []*TransformArgument   `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Returns        string                 `protobuf:"bytes,4,opt,name=returns,proto3" json:"returns,omitempty"`
	DisplayName    string                 `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	SameType       bool                   `protobuf:"varint,6,opt,name=same_type,json=sameType,proto3" json:"same_type,omitempty"`
	ReturnsInput   bool                   `protobuf:"varint,7,opt,name=returns_input,json=returnsInput,proto3" json:"returns_input,omitempty"`
	OperatorSymbol string                 `protobuf:"bytes,8,opt,name=operator_symbol,json=operatorSymbol,proto3" json:"operator_symbol,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransformFunction) Reset() {
	*x = TransformFunction{}
	mi := &file_ingestion_v1_transformations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformFunction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformFunction) ProtoMessage() {}

func (x *TransformFunction) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_transformations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformFunction.ProtoReflect.Descriptor instead.
func (*TransformFunction) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_transformations_proto_rawDescGZIP(), []int{2}
}

func (x *TransformFunction) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TransformFunction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TransformFunction) GetArgs() []*TransformArgument {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *TransformFunction) GetReturns() string {
	if x != nil {
		return x.Returns
	}
	return ""
}

func (x *TransformFunction) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *TransformFunction) GetSameType() bool {
	if x != nil {
		return x.SameType
	}
	return false
}

func (x *TransformFunction) GetReturnsInput() bool {
	if x != nil {
		return x.ReturnsInput
	}
	return false
}

func (x *TransformFunction) GetOperatorSymbol() string {
	if x != nil {
		return x.OperatorSymbol
	}
	return ""
}

// ListTransformFunctionsResponse carries the catalog, the grammar version a
// definition must declare, and the grammar's JSON schema for client-side
// shape checks.
type ListTransformFunctionsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Functions      []*TransformFunction   `protobuf:"bytes,1,rep,name=functions,proto3" json:"functions,omitempty"`
	GrammarVersion int32                  `protobuf:"varint,2,opt,name=grammar_version,json=grammarVersion,proto3" json:"grammar_version,omitempty"`
	GrammarSchema  string                 `protobuf:"bytes,3,opt,name=grammar_schema,json=grammarSchema,proto3" json:"grammar_schema,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListTransformFunctionsResponse) Reset() {
	*x = ListTransformFunctionsResponse{}
	mi := &file_ingestion_v1_transformations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransformFunctionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransformFunctionsResponse) ProtoMessage() {}

func (x *ListTransformFunctionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_transformations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransformFunctionsResponse.ProtoReflect.Descriptor instead.
func (*ListTransformFunctionsResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_transformations_proto_rawDescGZIP(), []int{3}
}

func (x *ListTransformFunctionsResponse) GetFunctions() []*TransformFunction {
	if x != nil {
		return x.Functions
	}
	return nil
}

func (x *ListTransformFunctionsResponse) GetGrammarVersion() int32 {
	if x != nil {
		return x.GrammarVersion
	}
	return 0
}

func (x *ListTransformFunctionsResponse) GetGrammarSchema() string {
	if x != nil {
		return x.GrammarSchema
	}
	return ""
}

// ValidateTransformRequest compiles a transform against one resource's
// schema, read from the source connection, exactly as a run would. The
// transform is the same JSON object an edge carries.
type ValidateTransformRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SourceConnectionId string                 `protobuf:"bytes,1,opt,name=source_connection_id,json=sourceConnectionId,proto3" json:"source_connection_id,omitempty"`
	Resource           string                 `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Transform          *structpb.Struct       `protobuf:"bytes,3,opt,name=transform,proto3" json:"transform,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ValidateTransformRequest) Reset() {
	*x = ValidateTransformRequest{}
	mi := &file_ingestion_v1_transformations_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTransformRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTransformRequest) ProtoMessage() {}

func (x *ValidateTransformRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_transformations_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTransformRequest.ProtoReflect.Descriptor instead.
func (*ValidateTransformRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_transformations_proto_rawDescGZIP(), []int{4}
}

func (x *ValidateTransformRequest) GetSourceConnectionId() string {
	if x != nil {
		return x.SourceConnectionId
	}
	return ""
}

func (x *ValidateTransformRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *ValidateTransformRequest) GetTransform() *structpb.Struct {
	if x != nil {
		return x.Transform
	}
	return nil
}

// ValidateTransformResponse lists every issue with the path in the definition
// it sits at, or on success the columns the resource will have after the
// transform.
type ValidateTransformResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Issues        []*ValidationError     `protobuf:"bytes,2,rep,name=issues,proto3" json:"issues,omitempty"`
	OutputColumns []*ResourceColumn      `protobuf:"bytes,3,rep,name=output_columns,json=outputColumns,proto3" json:"output_columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTransformResponse) Reset() {
	*x = ValidateTransformResponse{}
	mi := &file_ingestion_v1_transformations_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTransformResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTransformResponse) ProtoMessage() {}

func (x *ValidateTransformResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_transformations_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTransformResponse.ProtoReflect.Descriptor instead.
func (*ValidateTransformResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_transformations_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateTransformResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateTransformResponse) GetIssues() []*ValidationError {
	if x != nil {
		return x.Issues
	}
	return nil
}

func (x *ValidateTransformResponse) GetOutputColumns() []*ResourceColumn {
	if x != nil {
		return x.OutputColumns
	}
	return nil
}

var File_ingestion_v1_transformations_proto protoreflect.FileDescriptor

const file_ingestion_v1_transformations_proto_rawDesc = "" +
	"\n" +
	"\"ingestion/v1/transformations.proto\x12\fingestion.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1dingestion/v1/connectors.proto\"B\n" +
	"\x1dListTransformFunctionsRequest\x12!\n" +
	"\flogical_type\x18\x01 \x01(\tR\vlogicalType\"\xca\x01\n" +
	"\x11TransformArgument\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rlogical_types\x18\x02 \x03(\tR\flogicalTypes\x12\x1b\n" +
	"\tis_column\x18\x03 \x01(\bR\bisColumn\x12\x1d\n" +
	"\n" +
	"is_literal\x18\x04 \x01(\bR\tisLiteral\x12\x1f\n" +
	"\vis_optional\x18\x05 \x01(\bR\n" +
	"isOptional\x12\x1f\n" +
	"\vis_variadic\x18\x06 \x01(\bR\n" +
	"isVariadic\"\xa6\x02\n" +
	"\x11TransformFunction\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x123\n" +
	"\x04args\x18\x03 \x03(\v2\x1f.ingestion.v1.TransformArgumentR\x04args\x12\x18\n" +
	"\areturns\x18\x04 \x01(\tR\areturns\x12!\n" +
	"\fdisplay_name\x18\x05 \x01(\tR\vdisplayName\x12\x1b\n" +
	"\tsame_type\x18\x06 \x01(\bR\bsameType\x12#\n" +
	"\rreturns_input\x18\a \x01(\bR\freturnsInput\x12'\n" +
	"\x0foperator_symbol\x18\b \x01(\tR\x0eoperatorSymbol\"\xaf\x01\n" +
	"\x1eListTransformFunctionsResponse\x12=\n" +
	"\tfunctions\x18\x01 \x03(\v2\x1f.ingestion.v1.TransformFunctionR\tfunctions\x12'\n" +
	"\x0fgrammar_version\x18\x02 \x01(\x05R\x0egrammarVersion\x12%\n" +
	"\x0egrammar_schema\x18\x03 \x01(\tR\rgrammarSchema\"\x9f\x01\n" +
	"\x18ValidateTransformRequest\x120\n" +
	"\x14source_connection_id\x18\x01 \x01(\tR\x12sourceConnectionId\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x125\n" +
	"\ttransform\x18\x03 \x01(\v2\x17.google.protobuf.StructR\ttransform\"\xad\x01\n" +
	"\x19ValidateTransformResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x125\n" +
	"\x06issues\x18\x02 \x03(\v2\x1d.ingestion.v1.ValidationErrorR\x06issues\x12C\n" +
	"\x0eoutput_columns\x18\x03 \x03(\v2\x1c.ingestion.v1.ResourceColumnR\routputColumnsB\xb5\x01\n" +
	"\x10com.ingestion.v1B\x14TransformationsProtoP\x01Z:github.com/galaxy-io/filament/api/ingestion/v1;ingestionv1\xa2\x02\x03IXX\xaa\x02\fIngestion.V1\xca\x02\fIngestion\\V1\xe2\x02\x18Ingestion\\V1\\GPBMetadata\xea\x02\rIngestion::V1b\x06proto3"

var (
	file_ingestion_v1_transformations_proto_rawDescOnce sync.Once
	file_ingestion_v1_transformations_proto_rawDescData []byte
)

func file_ingestion_v1_transformations_proto_rawDescGZIP() []byte {
	file_ingestion_v1_transformations_proto_rawDescOnce.Do(func() {
		file_ingestion_v1_transformations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ingestion_v1_transformations_proto_rawDesc), len(file_ingestion_v1_transformations_proto_rawDesc)))
	})
	return file_ingestion_v1_transformations_proto_rawDescData
}

var file_ingestion_v1_transformations_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_ingestion_v1_transformations_proto_goTypes = []any{
	(*ListTransformFunctionsRequest)(nil),  // 0: ingestion.v1.ListTransformFunctionsRequest
	(*TransformArgument)(nil),              // 1: ingestion.v1.TransformArgument
	(*TransformFunction)(nil),              // 2: ingestion.v1.TransformFunction
	(*ListTransformFunctionsResponse)(nil), // 3: ingestion.v1.ListTransformFunctionsResponse
	(*ValidateTransformRequest)(nil),       // 4: ingestion.v1.ValidateTransformRequest
	(*ValidateTransformResponse)(nil),      // 5: ingestion.v1.ValidateTransformResponse
	(*structpb.Struct)(nil),                // 6: google.protobuf.Struct
	(*ValidationError)(nil),                // 7: ingestion.v1.ValidationError
	(*ResourceColumn)(nil),                 // 8: ingestion.v1.ResourceColumn
}
var file_ingestion_v1_transformations_proto_depIdxs = []int32{
	1, // 0: ingestion.v1.TransformFunction.args:type_name -> ingestion.v1.TransformArgument
	2, // 1: ingestion.v1.ListTransformFunctionsResponse.functions:type_name -> ingestion.v1.TransformFunction
	6, // 2: ingestion.v1.ValidateTransformRequest.transform:type_name -> google.protobuf.Struct
	7, // 3: ingestion.v1.ValidateTransformResponse.issues:type_name -> ingestion.v1.ValidationError
	8, // 4: ingestion.v1.ValidateTransformResponse.output_columns:type_name -> ingestion.v1.ResourceColumn
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_ingestion_v1_transformations_proto_init() }
func file_ingestion_v1_transformations_proto_init() {
	if File_ingestion_v1_transformations_proto != nil {
		return
	}
	file_ingestion_v1_connectors_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ingestion_v1_transformations_proto_rawDesc), len(file_ingestion_v1_transformations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ingestion_v1_transformations_proto_goTypes,
		DependencyIndexes: file_ingestion_v1_transformations_proto_depIdxs,
		MessageInfos:      file_ingestion_v1_transformations_proto_msgTypes,
	}.Build()
	File_ingestion_v1_transformations_proto = out.File
	file_ingestion_v1_transformations_proto_goTypes = nil
	file_ingestion_v1_transformations_proto_depIdxs = nil
}
