apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "filament.controlPlane.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "filament.controlPlane.labels" . | nindent 4 }}
