apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "filament.control.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "filament.control.labels" . | nindent 4 }}
