{{- if and .Values.controlPlane.enabled (not .Values.controlPlane.serviceAccount.name) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "filament.controlPlane.serviceAccountName" . }}
  namespace: {{ include "filament.namespace" . }}
  labels:
    {{- include "filament.controlPlane.labels" . | nindent 4 }}
  {{- with .Values.controlPlane.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
