{{- if .Values.controlPlane.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "filament.controlPlane.serviceAccountName" . }}
  namespace: {{ include "filament.namespace" . }}
  labels:
    {{- include "filament.controlPlane.labels" . | nindent 4 }}
{{- end }}
