apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "filament.control.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  PERSISTENCE_MIGRATE: {{ .Values.persistence.migrate | quote }}

  # NATS
  NATS_URL: {{ .Values.eventBus.nats.url }}
  NATS_STREAM: {{ .Values.eventBus.nats.stream }}
  NATS_SUBJECTS: {{ .Values.eventBus.nats.subjects }}

  # Ingestion
  INGESTION_ADDR: ":{{ .Values.control.service.port }}"

  # Worker
  K8S_NAMESPACE: {{ .Release.Namespace }}
  K8S_WORKER_IMAGE: {{ .Values.control.dispatch.worker.image.repository }}:{{ .Values.control.dispatch.worker.image.tag }}
  K8S_WORKER_IMAGE_PULL_POLICY: {{ .Values.control.dispatch.worker.image.pullPolicy }}
  K8S_WORKER_SERVICE_ACCOUNT: {{ include "filament.worker.serviceAccountName" . | quote }}
  K8S_WORKER_RESTART_POLICY: {{ .Values.control.dispatch.worker.restartPolicy }}
  K8S_WORKER_PASSTHROUGH_ENV: {{ join "," .Values.control.dispatch.worker.passthroughEnv | quote }}
  {{- with .Values.control.dispatch.worker.terminationGraceSeconds }}
  K8S_WORKER_TERMINATION_GRACE_SECONDS: {{ . | quote }}
  {{- end }}
  {{- with .Values.control.dispatch.worker.activeDeadlineSeconds }}
  K8S_WORKER_ACTIVE_DEADLINE_SECONDS: {{ . | quote }}
  {{- end }}

  # Jobs
  K8S_JOB_NAME_PREFIX: {{ .Values.control.dispatch.job.namePrefix }}
  K8S_JOB_BACKOFF_LIMIT: {{ .Values.control.dispatch.job.backoffLimit | quote }}
  K8S_JOB_TTL_SECONDS_AFTER_FINISHED: {{ .Values.control.dispatch.job.ttlSecondsAfterFinished | quote }}
