{{- if and .Values.persistence.postgresql.dsn.value (not .Values.persistence.postgresql.dsn.existingSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-db" (include "filament.control.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "filament.control.labels" . | nindent 4 }}
type: Opaque
stringData:
  dsn: {{ .Values.persistence.postgresql.dsn.value | quote }}
{{- end }}
