{{- if .Values.controlPlane.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "filament.controlPlane.fullname" . }}
  namespace: {{ include "filament.namespace" . }}
  labels:
    {{- include "filament.controlPlane.labels" . | nindent 4 }}
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "filament.controlPlane.fullname" . }}
  namespace: {{ include "filament.namespace" . }}
  labels:
    {{- include "filament.controlPlane.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "filament.controlPlane.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "filament.controlPlane.serviceAccountName" . }}
    namespace: {{ include "filament.namespace" . }}
{{- end }}
