{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "filament.secretName" . }}
  namespace: {{ include "filament.namespace" . }}
  labels:
    {{- include "filament.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if eq .Values.persistence.type "postgresql" }}
  PERSISTENCE_DSN: {{ .Values.persistence.postgresql.dsn | b64enc | quote }}
  {{- end }}
  {{- if eq .Values.secrets.type "postgres" }}
  ENCRYPTION_KEY: {{ .Values.secrets.postgres.encryptionKey | b64enc | quote }}
  {{- end }}
  {{- if eq .Values.eventBus.type "nats" }}
  NATS_URL: {{ .Values.eventBus.nats.url | b64enc | quote }}
  {{- end }}
{{- end }}
