{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "filament.secretName" . }}
  namespace: {{ include "filament.namespace" . }}
  labels:
    {{- include "filament.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if eq .Values.persistence.type "postgresql" }}
  PERSISTENCE_DSN: {{ .Values.persistence.postgresql.dsn | b64enc | quote }}
  {{- end }}
  {{- if eq .Values.secrets.type "datastore" }}
  ENCRYPTION_KEY: {{ .Values.secrets.datastore.encryptionKey | b64enc | quote }}
  {{- end }}
  {{- if eq .Values.eventBus.type "nats" }}
  NATS_URL: {{ .Values.eventBus.nats.url | b64enc | quote }}
  {{- end }}
  {{- if and .Values.auth.enabled (eq .Values.auth.type "zitadel") (not (include "filament.auth.mintedPatSecret" .)) }}
  AUTH_PAT: {{ .Values.auth.zitadel.pat | b64enc | quote }}
  {{- end }}
{{- end }}
