apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "filament.server.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  # NATS
  NATS_URL: {{ .Values.eventBus.nats.url }}
  NATS_STREAM: {{ .Values.eventBus.nats.stream }}
  NATS_SUBJECTS: {{ .Values.eventBus.nats.subjects }}

  # Ingestion
  SERVER_ADDR: ":{{ .Values.server.service.port }}"
