{{- if .Values.controlPlane.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "filament.worker.serviceAccountName" . }}
  namespace: {{ include "filament.namespace" . }}
  labels:
    {{- include "filament.worker.labels" . | nindent 4 }}
{{- with .Values.controlPlane.dispatch.worker.image.pullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
