# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.auth_v1create_service_account_response import AuthV1CreateServiceAccountResponse
from ..types.auth_v1list_service_accounts_request import AuthV1ListServiceAccountsRequest
from ..types.auth_v1list_service_accounts_response import AuthV1ListServiceAccountsResponse
from ..types.auth_v1remove_service_account_response import AuthV1RemoveServiceAccountResponse
from ..types.auth_v1role import AuthV1Role
from ..types.auth_v1rotate_service_account_secret_response import AuthV1RotateServiceAccountSecretResponse
from ..types.connect_timeout_header import ConnectTimeoutHeader
from .raw_client import AsyncRawServiceAccountClient, RawServiceAccountClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ServiceAccountClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawServiceAccountClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawServiceAccountClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawServiceAccountClient
        """
        return self._raw_client

    def create(
        self,
        *,
        connect_timeout_ms: typing.Optional[ConnectTimeoutHeader] = None,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        role: typing.Optional[AuthV1Role] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AuthV1CreateServiceAccountResponse:
        """
        Parameters
        ----------
        connect_timeout_ms : typing.Optional[ConnectTimeoutHeader]
            Define the timeout, in ms

        name : typing.Optional[str]

        description : typing.Optional[str]

        role : typing.Optional[AuthV1Role]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AuthV1CreateServiceAccountResponse
            Success

        Examples
        --------
        from filament import Filament

        client = Filament(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.service_account.create(
            connect_timeout_ms=1000.0,
        )
        """
        _response = self._raw_client.create(
            connect_timeout_ms=connect_timeout_ms,
            name=name,
            description=description,
            role=role,
            request_options=request_options,
        )
        return _response.data

    def list(
        self,
        *,
        request: AuthV1ListServiceAccountsRequest,
        connect_timeout_ms: typing.Optional[ConnectTimeoutHeader] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AuthV1ListServiceAccountsResponse:
        """
        Service accounts; authenticated tenant administration. Secrets are only
         returned by create and rotate and cannot be retrieved later.

        Parameters
        ----------
        request : AuthV1ListServiceAccountsRequest

        connect_timeout_ms : typing.Optional[ConnectTimeoutHeader]
            Define the timeout, in ms

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AuthV1ListServiceAccountsResponse
            Success

        Examples
        --------
        from filament import Filament

        client = Filament(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.service_account.list(
            connect_timeout_ms=1000.0,
            request={"key": "value"},
        )
        """
        _response = self._raw_client.list(
            request=request, connect_timeout_ms=connect_timeout_ms, request_options=request_options
        )
        return _response.data

    def remove(
        self,
        *,
        connect_timeout_ms: typing.Optional[ConnectTimeoutHeader] = None,
        user_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AuthV1RemoveServiceAccountResponse:
        """
        Parameters
        ----------
        connect_timeout_ms : typing.Optional[ConnectTimeoutHeader]
            Define the timeout, in ms

        user_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AuthV1RemoveServiceAccountResponse
            Success

        Examples
        --------
        from filament import Filament

        client = Filament(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.service_account.remove(
            connect_timeout_ms=1000.0,
        )
        """
        _response = self._raw_client.remove(
            connect_timeout_ms=connect_timeout_ms, user_id=user_id, request_options=request_options
        )
        return _response.data

    def rotate_secret(
        self,
        *,
        connect_timeout_ms: typing.Optional[ConnectTimeoutHeader] = None,
        user_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AuthV1RotateServiceAccountSecretResponse:
        """
        Parameters
        ----------
        connect_timeout_ms : typing.Optional[ConnectTimeoutHeader]
            Define the timeout, in ms

        user_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AuthV1RotateServiceAccountSecretResponse
            Success

        Examples
        --------
        from filament import Filament

        client = Filament(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.service_account.rotate_secret(
            connect_timeout_ms=1000.0,
        )
        """
        _response = self._raw_client.rotate_secret(
            connect_timeout_ms=connect_timeout_ms, user_id=user_id, request_options=request_options
        )
        return _response.data


class AsyncServiceAccountClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawServiceAccountClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawServiceAccountClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawServiceAccountClient
        """
        return self._raw_client

    async def create(
        self,
        *,
        connect_timeout_ms: typing.Optional[ConnectTimeoutHeader] = None,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        role: typing.Optional[AuthV1Role] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AuthV1CreateServiceAccountResponse:
        """
        Parameters
        ----------
        connect_timeout_ms : typing.Optional[ConnectTimeoutHeader]
            Define the timeout, in ms

        name : typing.Optional[str]

        description : typing.Optional[str]

        role : typing.Optional[AuthV1Role]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AuthV1CreateServiceAccountResponse
            Success

        Examples
        --------
        import asyncio

        from filament import AsyncFilament

        client = AsyncFilament(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.service_account.create(
                connect_timeout_ms=1000.0,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            connect_timeout_ms=connect_timeout_ms,
            name=name,
            description=description,
            role=role,
            request_options=request_options,
        )
        return _response.data

    async def list(
        self,
        *,
        request: AuthV1ListServiceAccountsRequest,
        connect_timeout_ms: typing.Optional[ConnectTimeoutHeader] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AuthV1ListServiceAccountsResponse:
        """
        Service accounts; authenticated tenant administration. Secrets are only
         returned by create and rotate and cannot be retrieved later.

        Parameters
        ----------
        request : AuthV1ListServiceAccountsRequest

        connect_timeout_ms : typing.Optional[ConnectTimeoutHeader]
            Define the timeout, in ms

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AuthV1ListServiceAccountsResponse
            Success

        Examples
        --------
        import asyncio

        from filament import AsyncFilament

        client = AsyncFilament(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.service_account.list(
                connect_timeout_ms=1000.0,
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            request=request, connect_timeout_ms=connect_timeout_ms, request_options=request_options
        )
        return _response.data

    async def remove(
        self,
        *,
        connect_timeout_ms: typing.Optional[ConnectTimeoutHeader] = None,
        user_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AuthV1RemoveServiceAccountResponse:
        """
        Parameters
        ----------
        connect_timeout_ms : typing.Optional[ConnectTimeoutHeader]
            Define the timeout, in ms

        user_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AuthV1RemoveServiceAccountResponse
            Success

        Examples
        --------
        import asyncio

        from filament import AsyncFilament

        client = AsyncFilament(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.service_account.remove(
                connect_timeout_ms=1000.0,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.remove(
            connect_timeout_ms=connect_timeout_ms, user_id=user_id, request_options=request_options
        )
        return _response.data

    async def rotate_secret(
        self,
        *,
        connect_timeout_ms: typing.Optional[ConnectTimeoutHeader] = None,
        user_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AuthV1RotateServiceAccountSecretResponse:
        """
        Parameters
        ----------
        connect_timeout_ms : typing.Optional[ConnectTimeoutHeader]
            Define the timeout, in ms

        user_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AuthV1RotateServiceAccountSecretResponse
            Success

        Examples
        --------
        import asyncio

        from filament import AsyncFilament

        client = AsyncFilament(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.service_account.rotate_secret(
                connect_timeout_ms=1000.0,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.rotate_secret(
            connect_timeout_ms=connect_timeout_ms, user_id=user_id, request_options=request_options
        )
        return _response.data
