// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: auth/v1/members.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Role is a filament permission level. The vocabulary is filament's, not the
// provider's: an adapter maps whatever grants it stores onto these.
type Role int32

const (
	Role_ROLE_UNSPECIFIED Role = 0
	Role_ROLE_ADMIN       Role = 1
	Role_ROLE_CREATOR     Role = 2
	Role_ROLE_VIEWER      Role = 3
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_ADMIN",
		2: "ROLE_CREATOR",
		3: "ROLE_VIEWER",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"ROLE_ADMIN":       1,
		"ROLE_CREATOR":     2,
		"ROLE_VIEWER":      3,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_v1_members_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_auth_v1_members_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_auth_v1_members_proto_rawDescGZIP(), []int{0}
}

// Member is one user of a tenant.
type Member struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Role          Role                   `protobuf:"varint,4,opt,name=role,proto3,enum=auth.v1.Role" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_auth_v1_members_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_members_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_auth_v1_members_proto_rawDescGZIP(), []int{0}
}

func (x *Member) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Member) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Member) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Member) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

type ListMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersRequest) Reset() {
	*x = ListMembersRequest{}
	mi := &file_auth_v1_members_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersRequest) ProtoMessage() {}

func (x *ListMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_members_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersRequest.ProtoReflect.Descriptor instead.
func (*ListMembersRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_members_proto_rawDescGZIP(), []int{1}
}

func (x *ListMembersRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type ListMembersResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Members []*Member              `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	// can_manage reports whether the caller may invite, re-role, or remove.
	// The UI renders read-only when false.
	CanManage     bool `protobuf:"varint,2,opt,name=can_manage,json=canManage,proto3" json:"can_manage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersResponse) Reset() {
	*x = ListMembersResponse{}
	mi := &file_auth_v1_members_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersResponse) ProtoMessage() {}

func (x *ListMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_members_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersResponse.ProtoReflect.Descriptor instead.
func (*ListMembersResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_members_proto_rawDescGZIP(), []int{2}
}

func (x *ListMembersResponse) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *ListMembersResponse) GetCanManage() bool {
	if x != nil {
		return x.CanManage
	}
	return false
}

type InviteMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	GivenName     string                 `protobuf:"bytes,3,opt,name=given_name,json=givenName,proto3" json:"given_name,omitempty"`
	FamilyName    string                 `protobuf:"bytes,4,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
	Role          Role                   `protobuf:"varint,5,opt,name=role,proto3,enum=auth.v1.Role" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteMemberRequest) Reset() {
	*x = InviteMemberRequest{}
	mi := &file_auth_v1_members_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteMemberRequest) ProtoMessage() {}

func (x *InviteMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_members_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteMemberRequest.ProtoReflect.Descriptor instead.
func (*InviteMemberRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_members_proto_rawDescGZIP(), []int{3}
}

func (x *InviteMemberRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *InviteMemberRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *InviteMemberRequest) GetGivenName() string {
	if x != nil {
		return x.GivenName
	}
	return ""
}

func (x *InviteMemberRequest) GetFamilyName() string {
	if x != nil {
		return x.FamilyName
	}
	return ""
}

func (x *InviteMemberRequest) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

// InviteMemberResponse carries the invitation an admin shares out of band.
// Nothing is emailed.
type InviteMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteMemberResponse) Reset() {
	*x = InviteMemberResponse{}
	mi := &file_auth_v1_members_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteMemberResponse) ProtoMessage() {}

func (x *InviteMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_members_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteMemberResponse.ProtoReflect.Descriptor instead.
func (*InviteMemberResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_members_proto_rawDescGZIP(), []int{4}
}

func (x *InviteMemberResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *InviteMemberResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type SetMemberRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          Role                   `protobuf:"varint,3,opt,name=role,proto3,enum=auth.v1.Role" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMemberRoleRequest) Reset() {
	*x = SetMemberRoleRequest{}
	mi := &file_auth_v1_members_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMemberRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMemberRoleRequest) ProtoMessage() {}

func (x *SetMemberRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_members_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMemberRoleRequest.ProtoReflect.Descriptor instead.
func (*SetMemberRoleRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_members_proto_rawDescGZIP(), []int{5}
}

func (x *SetMemberRoleRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SetMemberRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetMemberRoleRequest) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

type SetMemberRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMemberRoleResponse) Reset() {
	*x = SetMemberRoleResponse{}
	mi := &file_auth_v1_members_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMemberRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMemberRoleResponse) ProtoMessage() {}

func (x *SetMemberRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_members_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMemberRoleResponse.ProtoReflect.Descriptor instead.
func (*SetMemberRoleResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_members_proto_rawDescGZIP(), []int{6}
}

type RemoveMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberRequest) Reset() {
	*x = RemoveMemberRequest{}
	mi := &file_auth_v1_members_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberRequest) ProtoMessage() {}

func (x *RemoveMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_members_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveMemberRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_members_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveMemberRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RemoveMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RemoveMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberResponse) Reset() {
	*x = RemoveMemberResponse{}
	mi := &file_auth_v1_members_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberResponse) ProtoMessage() {}

func (x *RemoveMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_members_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberResponse.ProtoReflect.Descriptor instead.
func (*RemoveMemberResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_members_proto_rawDescGZIP(), []int{8}
}

var File_auth_v1_members_proto protoreflect.FileDescriptor

const file_auth_v1_members_proto_rawDesc = "" +
	"\n" +
	"\x15auth/v1/members.proto\x12\aauth.v1\"n\n" +
	"\x06Member\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12!\n" +
	"\x04role\x18\x04 \x01(\x0e2\r.auth.v1.RoleR\x04role\"1\n" +
	"\x12ListMembersRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"_\n" +
	"\x13ListMembersResponse\x12)\n" +
	"\amembers\x18\x01 \x03(\v2\x0f.auth.v1.MemberR\amembers\x12\x1d\n" +
	"\n" +
	"can_manage\x18\x02 \x01(\bR\tcanManage\"\xab\x01\n" +
	"\x13InviteMemberRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"given_name\x18\x03 \x01(\tR\tgivenName\x12\x1f\n" +
	"\vfamily_name\x18\x04 \x01(\tR\n" +
	"familyName\x12!\n" +
	"\x04role\x18\x05 \x01(\x0e2\r.auth.v1.RoleR\x04role\"C\n" +
	"\x14InviteMemberResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"o\n" +
	"\x14SetMemberRoleRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\x04role\x18\x03 \x01(\x0e2\r.auth.v1.RoleR\x04role\"\x17\n" +
	"\x15SetMemberRoleResponse\"K\n" +
	"\x13RemoveMemberRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x16\n" +
	"\x14RemoveMemberResponse*O\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"ROLE_ADMIN\x10\x01\x12\x10\n" +
	"\fROLE_CREATOR\x10\x02\x12\x0f\n" +
	"\vROLE_VIEWER\x10\x03B\x8a\x01\n" +
	"\vcom.auth.v1B\fMembersProtoP\x01Z0github.com/galaxy-io/filament/api/auth/v1;authv1\xa2\x02\x03AXX\xaa\x02\aAuth.V1\xca\x02\aAuth\\V1\xe2\x02\x13Auth\\V1\\GPBMetadata\xea\x02\bAuth::V1b\x06proto3"

var (
	file_auth_v1_members_proto_rawDescOnce sync.Once
	file_auth_v1_members_proto_rawDescData []byte
)

func file_auth_v1_members_proto_rawDescGZIP() []byte {
	file_auth_v1_members_proto_rawDescOnce.Do(func() {
		file_auth_v1_members_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_members_proto_rawDesc), len(file_auth_v1_members_proto_rawDesc)))
	})
	return file_auth_v1_members_proto_rawDescData
}

var file_auth_v1_members_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_auth_v1_members_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_auth_v1_members_proto_goTypes = []any{
	(Role)(0),                     // 0: auth.v1.Role
	(*Member)(nil),                // 1: auth.v1.Member
	(*ListMembersRequest)(nil),    // 2: auth.v1.ListMembersRequest
	(*ListMembersResponse)(nil),   // 3: auth.v1.ListMembersResponse
	(*InviteMemberRequest)(nil),   // 4: auth.v1.InviteMemberRequest
	(*InviteMemberResponse)(nil),  // 5: auth.v1.InviteMemberResponse
	(*SetMemberRoleRequest)(nil),  // 6: auth.v1.SetMemberRoleRequest
	(*SetMemberRoleResponse)(nil), // 7: auth.v1.SetMemberRoleResponse
	(*RemoveMemberRequest)(nil),   // 8: auth.v1.RemoveMemberRequest
	(*RemoveMemberResponse)(nil),  // 9: auth.v1.RemoveMemberResponse
}
var file_auth_v1_members_proto_depIdxs = []int32{
	0, // 0: auth.v1.Member.role:type_name -> auth.v1.Role
	1, // 1: auth.v1.ListMembersResponse.members:type_name -> auth.v1.Member
	0, // 2: auth.v1.InviteMemberRequest.role:type_name -> auth.v1.Role
	0, // 3: auth.v1.SetMemberRoleRequest.role:type_name -> auth.v1.Role
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_auth_v1_members_proto_init() }
func file_auth_v1_members_proto_init() {
	if File_auth_v1_members_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_members_proto_rawDesc), len(file_auth_v1_members_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_v1_members_proto_goTypes,
		DependencyIndexes: file_auth_v1_members_proto_depIdxs,
		EnumInfos:         file_auth_v1_members_proto_enumTypes,
		MessageInfos:      file_auth_v1_members_proto_msgTypes,
	}.Build()
	File_auth_v1_members_proto = out.File
	file_auth_v1_members_proto_goTypes = nil
	file_auth_v1_members_proto_depIdxs = nil
}
