# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..types.connect_timeout_header import ConnectTimeoutHeader
from ..types.ingestion_v1create_pipeline_response import IngestionV1CreatePipelineResponse
from ..types.ingestion_v1delete_pipeline_response import IngestionV1DeletePipelineResponse
from ..types.ingestion_v1get_pipeline_response import IngestionV1GetPipelineResponse
from ..types.ingestion_v1list_pipelines_response import IngestionV1ListPipelinesResponse
from ..types.ingestion_v1pagination_request import IngestionV1PaginationRequest
from ..types.ingestion_v1pipeline_graph import IngestionV1PipelineGraph
from ..types.ingestion_v1pipeline_schedule_config import IngestionV1PipelineScheduleConfig
from ..types.ingestion_v1run_options import IngestionV1RunOptions
from ..types.ingestion_v1run_pipeline_response import IngestionV1RunPipelineResponse
from ..types.ingestion_v1sorting_request import IngestionV1SortingRequest
from ..types.ingestion_v1update_pipeline_response import IngestionV1UpdatePipelineResponse
from ..types.ingestion_v1validate_pipeline_response import IngestionV1ValidatePipelineResponse
from ..types.ingestion_v1worker_configuration import IngestionV1WorkerConfiguration
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawPipelineClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def create(
        self,
        *,
        connect_timeout_ms: typing.Optional[ConnectTimeoutHeader] = None,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        schedule: typing.Optional[IngestionV1PipelineScheduleConfig] = OMIT,
        worker_configuration: typing.Optional[IngestionV1WorkerConfiguration] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[IngestionV1CreatePipelineResponse]:
        """
        Pipelines; the persisted node graph.

        Parameters
        ----------
        connect_timeout_ms : typing.Optional[ConnectTimeoutHeader]
            Define the timeout, in ms

        name : typing.Optional[str]

        description : typing.Optional[str]

        schedule : typing.Optional[IngestionV1PipelineScheduleConfig]

        worker_configuration : typing.Optional[IngestionV1WorkerConfiguration]
            worker_configuration shapes this pipeline's runs. Omit it to configure the
             pipeline's workers later through UpdatePipeline.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[IngestionV1CreatePipelineResponse]
            Success
        """
        _response = self._client_wrapper.httpx_client.request(
            "ingestion.v1.IngestionService/CreatePipeline",
            method="POST",
            json={
                "name": name,
                "description": description,
                "schedule": convert_and_respect_annotation_metadata(
                    object_=schedule, annotation=IngestionV1PipelineScheduleConfig, direction="write"
                ),
                "workerConfiguration": convert_and_respect_annotation_metadata(
                    object_=worker_configuration, annotation=IngestionV1WorkerConfiguration, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
                "Connect-Timeout-Ms": str(connect_timeout_ms) if connect_timeout_ms is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    IngestionV1CreatePipelineResponse,
                    parse_obj_as(
                        type_=IngestionV1CreatePipelineResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete(
        self,
        *,
        connect_timeout_ms: typing.Optional[ConnectTimeoutHeader] = None,
        id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[IngestionV1DeletePipelineResponse]:
        """
        Parameters
        ----------
        connect_timeout_ms : typing.Optional[ConnectTimeoutHeader]
            Define the timeout, in ms

        id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[IngestionV1DeletePipelineResponse]
            Success
        """
        _response = self._client_wrapper.httpx_client.request(
            "ingestion.v1.IngestionService/DeletePipeline",
            method="POST",
            json={
                "id": id,
            },
            headers={
                "content-type": "application/json",
                "Connect-Timeout-Ms": str(connect_timeout_ms) if connect_timeout_ms is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    IngestionV1DeletePipelineResponse,
                    parse_obj_as(
                        type_=IngestionV1DeletePipelineResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get(
        self,
        *,
        connect_timeout_ms: typing.Optional[ConnectTimeoutHeader] = None,
        id: typing.Optional[str] = OMIT,
        include_versions: typing.Optional[bool] = OMIT,
        include_last_run: typing.Optional[bool] = OMIT,
        include_schedule: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[IngestionV1GetPipelineResponse]:
        """
        Parameters
        ----------
        connect_timeout_ms : typing.Optional[ConnectTimeoutHeader]
            Define the timeout, in ms

        id : typing.Optional[str]

        include_versions : typing.Optional[bool]

        include_last_run : typing.Optional[bool]

        include_schedule : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[IngestionV1GetPipelineResponse]
            Success
        """
        _response = self._client_wrapper.httpx_client.request(
            "ingestion.v1.IngestionService/GetPipeline",
            method="POST",
            json={
                "id": id,
                "includeVersions": include_versions,
                "includeLastRun": include_last_run,
                "includeSchedule": include_schedule,
            },
            headers={
                "content-type": "application/json",
                "Connect-Timeout-Ms": str(connect_timeout_ms) if connect_timeout_ms is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    IngestionV1GetPipelineResponse,
                    parse_obj_as(
                        type_=IngestionV1GetPipelineResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def list(
        self,
        *,
        connect_timeout_ms: typing.Optional[ConnectTimeoutHeader] = None,
        include_deleted: typing.Optional[bool] = OMIT,
        pagination: typing.Optional[IngestionV1PaginationRequest] = OMIT,
        include_versions: typing.Optional[bool] = OMIT,
        include_last_run: typing.Optional[bool] = OMIT,
        include_schedule: typing.Optional[bool] = OMIT,
        search: typing.Optional[str] = OMIT,
        sorting: typing.Optional[IngestionV1SortingRequest] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[IngestionV1ListPipelinesResponse]:
        """
        Parameters
        ----------
        connect_timeout_ms : typing.Optional[ConnectTimeoutHeader]
            Define the timeout, in ms

        include_deleted : typing.Optional[bool]

        pagination : typing.Optional[IngestionV1PaginationRequest]

        include_versions : typing.Optional[bool]

        include_last_run : typing.Optional[bool]

        include_schedule : typing.Optional[bool]

        search : typing.Optional[str]

        sorting : typing.Optional[IngestionV1SortingRequest]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[IngestionV1ListPipelinesResponse]
            Success
        """
        _response = self._client_wrapper.httpx_client.request(
            "ingestion.v1.IngestionService/ListPipelines",
            method="POST",
            json={
                "includeDeleted": include_deleted,
                "pagination": convert_and_respect_annotation_metadata(
                    object_=pagination, annotation=IngestionV1PaginationRequest, direction="write"
                ),
                "includeVersions": include_versions,
                "includeLastRun": include_last_run,
                "includeSchedule": include_schedule,
                "search": search,
                "sorting": convert_and_respect_annotation_metadata(
                    object_=sorting, annotation=IngestionV1SortingRequest, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
                "Connect-Timeout-Ms": str(connect_timeout_ms) if connect_timeout_ms is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    IngestionV1ListPipelinesResponse,
                    parse_obj_as(
                        type_=IngestionV1ListPipelinesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def run(
        self,
        *,
        connect_timeout_ms: typing.Optional[ConnectTimeoutHeader] = None,
        pipeline_id: typing.Optional[str] = OMIT,
        client_token: typing.Optional[str] = OMIT,
        options: typing.Optional[IngestionV1RunOptions] = OMIT,
        worker_configuration: typing.Optional[IngestionV1WorkerConfiguration] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[IngestionV1RunPipelineResponse]:
        """
        Runs; compile + submit a pipeline, then list / snapshot / signal.

        Parameters
        ----------
        connect_timeout_ms : typing.Optional[ConnectTimeoutHeader]
            Define the timeout, in ms

        pipeline_id : typing.Optional[str]

        client_token : typing.Optional[str]
            client_token salts the idempotency key so a deliberate re-run differs from a
             double-click; reusing a token dedupes to the same runs.

        options : typing.Optional[IngestionV1RunOptions]
            options overrides engine throughput defaults for every run this call
             produces. Unset (or any zero field) defers to defaults.

        worker_configuration : typing.Optional[IngestionV1WorkerConfiguration]
            worker_configuration overrides the pipeline's own for this call only, field
             by field: an empty field inherits the pipeline's value. The resolved result
             is stamped onto each run, so editing the pipeline afterwards cannot change
             a run already requested.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[IngestionV1RunPipelineResponse]
            Success
        """
        _response = self._client_wrapper.httpx_client.request(
            "ingestion.v1.IngestionService/RunPipeline",
            method="POST",
            json={
                "pipelineId": pipeline_id,
                "clientToken": client_token,
                "options": convert_and_respect_annotation_metadata(
                    object_=options, annotation=IngestionV1RunOptions, direction="write"
                ),
                "workerConfiguration": convert_and_respect_annotation_metadata(
                    object_=worker_configuration, annotation=IngestionV1WorkerConfiguration, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
                "Connect-Timeout-Ms": str(connect_timeout_ms) if connect_timeout_ms is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    IngestionV1RunPipelineResponse,
                    parse_obj_as(
                        type_=IngestionV1RunPipelineResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update(
        self,
        *,
        connect_timeout_ms: typing.Optional[ConnectTimeoutHeader] = None,
        pipeline_id: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        worker_configuration: typing.Optional[IngestionV1WorkerConfiguration] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[IngestionV1UpdatePipelineResponse]:
        """
        Parameters
        ----------
        connect_timeout_ms : typing.Optional[ConnectTimeoutHeader]
            Define the timeout, in ms

        pipeline_id : typing.Optional[str]

        name : typing.Optional[str]

        description : typing.Optional[str]

        worker_configuration : typing.Optional[IngestionV1WorkerConfiguration]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[IngestionV1UpdatePipelineResponse]
            Success
        """
        _response = self._client_wrapper.httpx_client.request(
            "ingestion.v1.IngestionService/UpdatePipeline",
            method="POST",
            json={
                "pipelineId": pipeline_id,
                "name": name,
                "description": description,
                "workerConfiguration": convert_and_respect_annotation_metadata(
                    object_=worker_configuration, annotation=IngestionV1WorkerConfiguration, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
                "Connect-Timeout-Ms": str(connect_timeout_ms) if connect_timeout_ms is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    IngestionV1UpdatePipelineResponse,
                    parse_obj_as(
                        type_=IngestionV1UpdatePipelineResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def validate(
        self,
        *,
        connect_timeout_ms: typing.Optional[ConnectTimeoutHeader] = None,
        graph: typing.Optional[IngestionV1PipelineGraph] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[IngestionV1ValidatePipelineResponse]:
        """
        Pipeline options and validation are resolved for the complete graph.

        Parameters
        ----------
        connect_timeout_ms : typing.Optional[ConnectTimeoutHeader]
            Define the timeout, in ms

        graph : typing.Optional[IngestionV1PipelineGraph]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[IngestionV1ValidatePipelineResponse]
            Success
        """
        _response = self._client_wrapper.httpx_client.request(
            "ingestion.v1.IngestionService/ValidatePipeline",
            method="POST",
            json={
                "graph": convert_and_respect_annotation_metadata(
                    object_=graph, annotation=IngestionV1PipelineGraph, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
                "Connect-Timeout-Ms": str(connect_timeout_ms) if connect_timeout_ms is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    IngestionV1ValidatePipelineResponse,
                    parse_obj_as(
                        type_=IngestionV1ValidatePipelineResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawPipelineClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def create(
        self,
        *,
        connect_timeout_ms: typing.Optional[ConnectTimeoutHeader] = None,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        schedule: typing.Optional[IngestionV1PipelineScheduleConfig] = OMIT,
        worker_configuration: typing.Optional[IngestionV1WorkerConfiguration] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[IngestionV1CreatePipelineResponse]:
        """
        Pipelines; the persisted node graph.

        Parameters
        ----------
        connect_timeout_ms : typing.Optional[ConnectTimeoutHeader]
            Define the timeout, in ms

        name : typing.Optional[str]

        description : typing.Optional[str]

        schedule : typing.Optional[IngestionV1PipelineScheduleConfig]

        worker_configuration : typing.Optional[IngestionV1WorkerConfiguration]
            worker_configuration shapes this pipeline's runs. Omit it to configure the
             pipeline's workers later through UpdatePipeline.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[IngestionV1CreatePipelineResponse]
            Success
        """
        _response = await self._client_wrapper.httpx_client.request(
            "ingestion.v1.IngestionService/CreatePipeline",
            method="POST",
            json={
                "name": name,
                "description": description,
                "schedule": convert_and_respect_annotation_metadata(
                    object_=schedule, annotation=IngestionV1PipelineScheduleConfig, direction="write"
                ),
                "workerConfiguration": convert_and_respect_annotation_metadata(
                    object_=worker_configuration, annotation=IngestionV1WorkerConfiguration, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
                "Connect-Timeout-Ms": str(connect_timeout_ms) if connect_timeout_ms is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    IngestionV1CreatePipelineResponse,
                    parse_obj_as(
                        type_=IngestionV1CreatePipelineResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete(
        self,
        *,
        connect_timeout_ms: typing.Optional[ConnectTimeoutHeader] = None,
        id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[IngestionV1DeletePipelineResponse]:
        """
        Parameters
        ----------
        connect_timeout_ms : typing.Optional[ConnectTimeoutHeader]
            Define the timeout, in ms

        id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[IngestionV1DeletePipelineResponse]
            Success
        """
        _response = await self._client_wrapper.httpx_client.request(
            "ingestion.v1.IngestionService/DeletePipeline",
            method="POST",
            json={
                "id": id,
            },
            headers={
                "content-type": "application/json",
                "Connect-Timeout-Ms": str(connect_timeout_ms) if connect_timeout_ms is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    IngestionV1DeletePipelineResponse,
                    parse_obj_as(
                        type_=IngestionV1DeletePipelineResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get(
        self,
        *,
        connect_timeout_ms: typing.Optional[ConnectTimeoutHeader] = None,
        id: typing.Optional[str] = OMIT,
        include_versions: typing.Optional[bool] = OMIT,
        include_last_run: typing.Optional[bool] = OMIT,
        include_schedule: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[IngestionV1GetPipelineResponse]:
        """
        Parameters
        ----------
        connect_timeout_ms : typing.Optional[ConnectTimeoutHeader]
            Define the timeout, in ms

        id : typing.Optional[str]

        include_versions : typing.Optional[bool]

        include_last_run : typing.Optional[bool]

        include_schedule : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[IngestionV1GetPipelineResponse]
            Success
        """
        _response = await self._client_wrapper.httpx_client.request(
            "ingestion.v1.IngestionService/GetPipeline",
            method="POST",
            json={
                "id": id,
                "includeVersions": include_versions,
                "includeLastRun": include_last_run,
                "includeSchedule": include_schedule,
            },
            headers={
                "content-type": "application/json",
                "Connect-Timeout-Ms": str(connect_timeout_ms) if connect_timeout_ms is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    IngestionV1GetPipelineResponse,
                    parse_obj_as(
                        type_=IngestionV1GetPipelineResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def list(
        self,
        *,
        connect_timeout_ms: typing.Optional[ConnectTimeoutHeader] = None,
        include_deleted: typing.Optional[bool] = OMIT,
        pagination: typing.Optional[IngestionV1PaginationRequest] = OMIT,
        include_versions: typing.Optional[bool] = OMIT,
        include_last_run: typing.Optional[bool] = OMIT,
        include_schedule: typing.Optional[bool] = OMIT,
        search: typing.Optional[str] = OMIT,
        sorting: typing.Optional[IngestionV1SortingRequest] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[IngestionV1ListPipelinesResponse]:
        """
        Parameters
        ----------
        connect_timeout_ms : typing.Optional[ConnectTimeoutHeader]
            Define the timeout, in ms

        include_deleted : typing.Optional[bool]

        pagination : typing.Optional[IngestionV1PaginationRequest]

        include_versions : typing.Optional[bool]

        include_last_run : typing.Optional[bool]

        include_schedule : typing.Optional[bool]

        search : typing.Optional[str]

        sorting : typing.Optional[IngestionV1SortingRequest]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[IngestionV1ListPipelinesResponse]
            Success
        """
        _response = await self._client_wrapper.httpx_client.request(
            "ingestion.v1.IngestionService/ListPipelines",
            method="POST",
            json={
                "includeDeleted": include_deleted,
                "pagination": convert_and_respect_annotation_metadata(
                    object_=pagination, annotation=IngestionV1PaginationRequest, direction="write"
                ),
                "includeVersions": include_versions,
                "includeLastRun": include_last_run,
                "includeSchedule": include_schedule,
                "search": search,
                "sorting": convert_and_respect_annotation_metadata(
                    object_=sorting, annotation=IngestionV1SortingRequest, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
                "Connect-Timeout-Ms": str(connect_timeout_ms) if connect_timeout_ms is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    IngestionV1ListPipelinesResponse,
                    parse_obj_as(
                        type_=IngestionV1ListPipelinesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def run(
        self,
        *,
        connect_timeout_ms: typing.Optional[ConnectTimeoutHeader] = None,
        pipeline_id: typing.Optional[str] = OMIT,
        client_token: typing.Optional[str] = OMIT,
        options: typing.Optional[IngestionV1RunOptions] = OMIT,
        worker_configuration: typing.Optional[IngestionV1WorkerConfiguration] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[IngestionV1RunPipelineResponse]:
        """
        Runs; compile + submit a pipeline, then list / snapshot / signal.

        Parameters
        ----------
        connect_timeout_ms : typing.Optional[ConnectTimeoutHeader]
            Define the timeout, in ms

        pipeline_id : typing.Optional[str]

        client_token : typing.Optional[str]
            client_token salts the idempotency key so a deliberate re-run differs from a
             double-click; reusing a token dedupes to the same runs.

        options : typing.Optional[IngestionV1RunOptions]
            options overrides engine throughput defaults for every run this call
             produces. Unset (or any zero field) defers to defaults.

        worker_configuration : typing.Optional[IngestionV1WorkerConfiguration]
            worker_configuration overrides the pipeline's own for this call only, field
             by field: an empty field inherits the pipeline's value. The resolved result
             is stamped onto each run, so editing the pipeline afterwards cannot change
             a run already requested.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[IngestionV1RunPipelineResponse]
            Success
        """
        _response = await self._client_wrapper.httpx_client.request(
            "ingestion.v1.IngestionService/RunPipeline",
            method="POST",
            json={
                "pipelineId": pipeline_id,
                "clientToken": client_token,
                "options": convert_and_respect_annotation_metadata(
                    object_=options, annotation=IngestionV1RunOptions, direction="write"
                ),
                "workerConfiguration": convert_and_respect_annotation_metadata(
                    object_=worker_configuration, annotation=IngestionV1WorkerConfiguration, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
                "Connect-Timeout-Ms": str(connect_timeout_ms) if connect_timeout_ms is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    IngestionV1RunPipelineResponse,
                    parse_obj_as(
                        type_=IngestionV1RunPipelineResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update(
        self,
        *,
        connect_timeout_ms: typing.Optional[ConnectTimeoutHeader] = None,
        pipeline_id: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        worker_configuration: typing.Optional[IngestionV1WorkerConfiguration] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[IngestionV1UpdatePipelineResponse]:
        """
        Parameters
        ----------
        connect_timeout_ms : typing.Optional[ConnectTimeoutHeader]
            Define the timeout, in ms

        pipeline_id : typing.Optional[str]

        name : typing.Optional[str]

        description : typing.Optional[str]

        worker_configuration : typing.Optional[IngestionV1WorkerConfiguration]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[IngestionV1UpdatePipelineResponse]
            Success
        """
        _response = await self._client_wrapper.httpx_client.request(
            "ingestion.v1.IngestionService/UpdatePipeline",
            method="POST",
            json={
                "pipelineId": pipeline_id,
                "name": name,
                "description": description,
                "workerConfiguration": convert_and_respect_annotation_metadata(
                    object_=worker_configuration, annotation=IngestionV1WorkerConfiguration, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
                "Connect-Timeout-Ms": str(connect_timeout_ms) if connect_timeout_ms is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    IngestionV1UpdatePipelineResponse,
                    parse_obj_as(
                        type_=IngestionV1UpdatePipelineResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def validate(
        self,
        *,
        connect_timeout_ms: typing.Optional[ConnectTimeoutHeader] = None,
        graph: typing.Optional[IngestionV1PipelineGraph] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[IngestionV1ValidatePipelineResponse]:
        """
        Pipeline options and validation are resolved for the complete graph.

        Parameters
        ----------
        connect_timeout_ms : typing.Optional[ConnectTimeoutHeader]
            Define the timeout, in ms

        graph : typing.Optional[IngestionV1PipelineGraph]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[IngestionV1ValidatePipelineResponse]
            Success
        """
        _response = await self._client_wrapper.httpx_client.request(
            "ingestion.v1.IngestionService/ValidatePipeline",
            method="POST",
            json={
                "graph": convert_and_respect_annotation_metadata(
                    object_=graph, annotation=IngestionV1PipelineGraph, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
                "Connect-Timeout-Ms": str(connect_timeout_ms) if connect_timeout_ms is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    IngestionV1ValidatePipelineResponse,
                    parse_obj_as(
                        type_=IngestionV1ValidatePipelineResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
