export const PIPELINE_CANVAS_PANEL_WIDTH = 540;
export const PIPELINE_CANVAS_PANEL_COLLAPSED_WIDTH = 28;
export const PIPELINE_CANVAS_PANEL_INSET = 12;
export const PIPELINE_CANVAS_PANEL_HEADER_HEIGHT = 40;
